### ISSUE TITLE
Ensure that the intellectual description is displayed before the container information in the search results

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#10]
At the moment, the default display is structured as the following:
![image](https://user-images.githubusercontent.com/1443986/66130292-7b338900-e5bf-11e9-8c8d-8c5f183ac741.png)

...and the item view is structured as the this:
![image](https://user-images.githubusercontent.com/1443986/66130772-470c9800-e5c0-11e9-97a3-5fe1f3286e8c.png)

Please note that in these cases, information about the parent collection is limited or not present at all.  This lies in contrast to the current design and layout for containers in the PULFA 2.0 site:
![image](https://user-images.githubusercontent.com/1443986/66130718-2cd2ba00-e5c0-11e9-86cb-6cd0e12cf0e6.png)

**Comment by tpendragon** [comment]
This is vastly different after wireframe work and implementation. The wireframe was agreed on, so I'm closing this.
