### ISSUE TITLE
Use the Blacklight range limit plugin for parsing and visualizing date ranges

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#100]
While looking to facet upon date ranges or search for specific date ranges, UX design should be undertaken to assess and identify methods of indicating to users that a substantial number of items might be undated within collections

**Comment by jrgriffiniii** [comment]
What should the warning for this look like? Wireframing will be needed in order to advance this.

**Comment by jrgriffiniii** [comment]
A dialogue modal would be very disruptive - this should be in the location in the facet as a static message (perhaps using a Bootstrap alert color).

**Comment by sdellis** [comment]
We could avoid any warning with a better representation of the data in the facet. The Date Range facet in  PulfaLight should be consistent with the Date Range facet in OrangeLight, which gives a histogram of date ranges in the results and a link to "undated" material that can't be represented. See screen shot (although I don't know why it spans beyond the current year). 

![Screen Shot 2020-03-30 at 12.02.31 PM.png](https://images.zenhubusercontent.com/5cba15f2e89c9c3b0c58e0d1/ae1140b9-d3c0-4126-8dc9-a555d954927d)

**Comment by jrgriffiniii** [comment]
Invalid date years should not be rendered in the slider.

**Comment by jrgriffiniii** [comment]
There are three possible cases which cannot be parsed into datestamps:

- Dates not examined (there may be dates but these were not found by those producing the EADs)
- Dates not found
- Dates which exist, but which cannot be parsed (e. g. "Easter Morning")

Facets will not directly map to the text which is rendered in the field for the record in all cases.

**Comment by jrgriffiniii** [comment]
I can advance this by first installing the range limit plugin.

**Comment by jrgriffiniii** [comment]
There are some problems with integrating this, as while it was apparently already configured on one of the facet fields, both the JavaScript is breaking, primarily due to the `blacklight_range_limit/_range_limit_panel.html.erb` partial not being rendered properly.

**Comment by jrgriffiniii** [comment]
Resolved by #220
