### ISSUE TITLE
Your Account at top of page confusing for researchers

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1009]
Are we able to just get rid of the Your Account button at the top of the page? This is only useful for PU researchers and it is super confusing to our outside researchers which likely outnumber our PU ones.
Thoughts @faithc

**Comment by faithc** [comment]
I defer to you on this one, @ccleeton. :) I'm fine with removing it.

**Comment by ccleeton** [comment]
I would say lets remove it but if we can have a conversation about why it only goes to CAS login and not just the aeon login screen that would be good.
I am hoping this is a quick one and we might be able to get it in the sprint

**Comment by ccleeton** [comment]
Closing because we redirected to the aeon login page
