### ISSUE TITLE
[PULFALight/staging] ArgumentError: wrong number of arguments (given 0, expected 1)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#103]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/59448049)

**Comment by jrgriffiniii** [comment]
This seems to be related to an upstream issue in ArcLight, as currently http://arclight-demo.projectblacklight.org/catalog/heschelabrahamaspace_ref5110_s4o/raw for http://arclight-demo.projectblacklight.org/catalog/heschelabrahamaspace_ref5110_s4o returns a 500 error status.

**Comment by seanaery** [comment]
Hi @jrgriffiniii -- I also encountered this problem in the fall and logged it as an ArcLight bug here: https://github.com/projectblacklight/arclight/issues/741 I'm unsure how to troubleshoot it further, but we are really interested in getting that fixed.

**Comment by hackmastera** [comment]
How can this be replicated?

**Comment by jrgriffiniii** [comment]
This was resolved with https://github.com/pulibrary/pulfalight/pull/215
