### ISSUE TITLE
Document what to do if you can't access the aspace api

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1034]
There's relevant new documentation for this: https://github.com/pulibrary/pul-the-hard-way/tree/398e701e4ee21cce74314cb051dadf5901ae54a2/services/vpn

We should have something in the pulfalight repo that points there and also points to exactly who we contact since this happens so frequently.

**Comment by hackartisan** [comment]
Do you have to have an account on their zendesk to get this done? https://lyrasis.zendesk.com/hc/en-us

**Comment by tpendragon** [comment]
No, you just email `support@lyrasis.zendesk.com`
