### ISSUE TITLE
Can the "Welcome to the new Finding Aids site!" banner come down?

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1045]
I understand that the general public does not have the same access policy as the Princeton community due to the pandemic, so there may be a desire to continue to inform the public about access restrictions/options for the public. If this is going to be a long-term policy, I think it would be best to integrate it into the site as the banner is really intended for information that is temporary in nature. 

@ccleeton 
@slogue

**Comment by slogue** [comment]
Shaun, I'm hopeful that the COVID policies are temporary and will be lifted at some point in the near future. Until that happens, though, I would like to keep the banner in place. Thanks!

**Comment by ccleeton** [comment]
I would at least like to take the New Finding Aids text down and just leave the access link

**Comment by ccleeton** [comment]
@sdellis I was able to confirm with @slogue today that we can remove the New finding aids text and just leave the access link.

Is this something that we can do out of cycle?

**Comment by ccleeton** [comment]
@slogue Would you be ok with moving the covid info out of the banner

**Comment by slogue** [comment]
At this point, most of the COVID restrictions have lifted, so I think we can just take it out of the banner. I was waiting for that to happen and then forgot about this ticket.

**Comment by ccleeton** [comment]
@sdellis So we can get rid of all the top banner!!!
