### ISSUE TITLE
No site in aeon request

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1046]
Some boxes do not have a site associated with them. It should state “MUDD” but it’s blank. Though the location for them is “Mudd” that still does not fix matters. The site location is uneditable by us as staff and by the researcher. The boxes are therefore unable to be seen or printed by the staff in the reading room at Mudd and it’s caused an enormous amount of confusion with multiple staff members. The most we could do is complete a manual request by typing all pertinent information, but this is unfeasible and impossible if the staff doesn’t even know materials are hidden from their queue view.
AC109, Box 39 (i.e. TN 322754)
AC109, Box 211 (i.e. TN 332783)
AC184, Box 6 (i.e. TN 333120)
MC247, Box 116 (i.e. TN 332934)
MC247, Box 120 (i.e. TN 332935)
(This set is confusing as Box 3 and Box 236 * do * have “Mudd” as the site)

To replicate you only have to request one box.

Note that https://github.com/pulibrary/pulfalight/pull/1028 was merged 7 days ago -- it may be worth checking when it was deployed. This problem was encountered several times in the past week, with the following timestamps:

- AC109, Box 39 (i.e. TN 322754) - requested 4/26 2:24pm
- AC109, Box 211 (i.e. TN 332783) - 4/26 4:35pm
- AC184, Box 6 (i.e. TN 333120) - requested 4/29 2:45pm
- MC247, Box 116 (i.e. TN 332934) - requested 4/27 3:14pm
- MC247, Box 120 (i.e. TN 332935) - requested 4/27 3:14pm

Please communicate with Mandy on this issue.

### Sudden priority justification
Without this field staff can't fulfill requests.

**Comment by tpendragon** [comment]
I'm having a hard time replicating this, but the timeline does seem to fit with the deploy of #1028.

**Comment by tpendragon** [comment]
Mandy and Will did some more digging. It looks like this happens when you request two folders in the same box.

I think we need to add a grouping: first entry for the Site field.
