### ISSUE TITLE
Users should be able to submit corrections for content in a collection or component

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#105]
Wireframe: https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/screen/8511ff6c-e5b8-4a41-9926-9c90325d315a

This is similar to #104, and is also currently supported with PULFA 2.0 with a "Suggest a correction" link:

![image](https://user-images.githubusercontent.com/1443986/73424334-86dc5580-42fc-11ea-9ccf-06e50a65bb06.png)

![image](https://user-images.githubusercontent.com/1443986/73424377-a5dae780-42fc-11ea-8932-ce13e7ad6560.png)

**Comment by sdellis** [comment]
From @faithc on 3/12/2020 ... all of these changes should make it into PulfaLight: 

I’d like to request changes to the current mapping of the Suggest a Correction feature on the finding aids website. Please route Suggest a Correction submissions for EADs associated with all repositories other than “univarchives” and “publicpolicy” to mssdiv@princeton.edu. (EADs associated with the “mss” repository are already currently routed to mssdiv@princeton.edu; this will not change.) In other words, in addition to the “mss” repo, please route Suggest a Correction submissions to mssdiv@princeton.edu for EADs associated with the following repositories:

cotsen
ea
eng
ga
lae
rarebooks
selectors

Please let me know if you have any questions; and thanks for your assistance.
