### ISSUE TITLE
Make mockup for more clarity on the grouped collection results

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1050]
Right now there is not enough distinction between the collection and the top three sub-component results. We need to create more clarity or even do away with the sub-component results. It would be nice to add keyword highlighting to the components, if we keep them.

<img width="1003" alt="Screen Shot 2022-05-03 at 10 23 15 AM" src="https://user-images.githubusercontent.com/609368/166471878-9f17264a-6cff-417b-be51-bee4938110f2.png">

**Comment by sdellis** [comment]
During testing, participants struggled to distinguish between collection-level records and their nested sub-components in the “Group by Collections” search results. Better visual distinction from collection level records (via nesting, contrast, etc), removal of sub-components in these results, or possibly more contrast with the collection-level records would be an improvement. See [the Highlight Reel ](https://drive.google.com/drive/folders/1SlKD4_kWFiuIMT4WHiu6LzoJ0noouYYe)for more info on the issue.

**Comment by sdellis** [comment]
Ideas:
1. Clearer Nesting/hierarchy for sub-component results
2. Say "Top x results for your search in this collection"
3. Better distinguish the collection record (icons, color bg, etc.)
4. Can we filter out the collection in the sub-component results?
5. Possible link from the collection record to "preview these results in this collection" (runs the search within the collection)
6. Should "Group by Collection" still be the default?

Success Criteria for this ticket is a set of wireframe options.

**Comment by ccleeton** [comment]
I like the indentation and the white space vs blue. I am finding the icons a bit confusing to know what level things are box vs folder vs item.

**Comment by faithc** [comment]
We had discussed the use of these icons when we initially began developing the site. I've always thought they were confusing and not helpful especially since we don't privilege containers in how we describe materials. I think displaying hierarchy/context (which I think is captured in this issue, https://github.com/pulibrary/pulfalight/issues/1153, is more helpful.

**Comment by sdellis** [comment]
@ccleeton  and @faithc just to clarify, are you suggesting we do away with the icons all together in the search results and simply provide the hierarchy/context through the breadcrumbs? That full breadcrumb seems important to the completion of this ticket. Was it withheld from this cycle's priority tickets' queue for a particular reason?

I think that appropriate icons for Collections, Series, and Components would allow people to distinguish among them, and I believe there is usability value in that, but I'm open to your thoughts on it.

**Comment by faithc** [comment]
I think we probably need to do some user testing before getting rid of the icons, but I'm personally not a fan. Ha 

I agree about the breadcrumbs. I don't think we withheld that ticket purposely; we may not have included it given how many tickets we had already earmarked aside from this one. I also just realized that it was related in drafting my previous comment.

**Comment by sdellis** [comment]
Ok, sounds good. Other than the icons, how do you feel about the rest of the design, @faithc ?

**Comment by faithc** [comment]
I think it looks good!

**Comment by ccleeton** [comment]
I like the icons just find the specific ones we have now a bit confusting. I agree that testing would be helpful and maybe a key (guide) somewhere would be good.
Overall I think the design is clearer and I asked one other PS person what they thought and they agreed it was more clear.

**Comment by sdellis** [comment]
Implementation Ticket: https://github.com/pulibrary/pulfalight/issues/1289

**Comment by sdellis** [comment]
After revisiting this, my only additional suggestion for implementing the mockup is to give the grouping boxes (both gray and white) rounded corners. Everything else on the page has rounded corners, so it would look more consistent. Not a blocker though!
