### ISSUE TITLE
Add library location to breadcrumbs in search results, show page

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1051]
Final decisions:

- Add a link to the library before the other breadcrumbs in the search results; if clicked it takes you to the "Access & Use" tab of the collection show page.
- Add breadcrumbs to the top each component content area, above the component title. functionality the same as the breadcrumb on the search results page.

Additional requirements were moved to new issues:
- #1167
- #1168

**Comment by tpendragon** [comment]
The use case is: I want to visit Princeton and I need to know which buildings I need to go to.

**Comment by tpendragon** [comment]
Labels should be "Mudd Library" or "Firestone Library"

**Comment by ccleeton** [comment]
I think having the image as a link to access and use makes alot of sense.
And the caption works too.

**Comment by hackartisan** [comment]
@ccleeton make the image a link to the "access and use" tab? Or a link to the repositories page (e.g. https://findingaids.princeton.edu/repositories/univarchives)?

**Comment by ccleeton** [comment]
I think the access and use is more helpful since it includes potential restrictions or if parts are housed off site

**Comment by hackartisan** [comment]
Should we see if we can add the "visit us" link to the access and use tab, and then have the image link to that tab, and not add a caption at all?

for the additional breadcrumb in the search results -- should this also link to the "access and use" tab for the collection?

**Comment by ccleeton** [comment]
I'd like to see the visit us link added to the tab but I'd like to see the caption added so users don't have to click it if they don't need or want to.

For the breadcrumb i would say yes to link the access and use to be consistent

**Comment by hackartisan** [comment]
Okay and you definitely want the caption to link to the Visit Us page? Sorry for all the back and forth; I just want to make sure in that context you're not concerned about the potential restrictions or if parts are housed off site. Thank you!

**Comment by ccleeton** [comment]
Good point. I am seeing that the storage note is only on the collection overview page. - This is an example of where there are items at Mudd and Recap - https://findingaids.princeton.edu/catalog/AC154
@faithc what do you think?
@tpendragon is it possible to add the storage note to the access page? Then it would all make sense to me.

**Comment by hackartisan** [comment]
Another option instead of a caption by the collection title might be to repeat the breadcrumb somewhere on the page. Perhaps above the component title? See screenshot:

![Screen Shot 2022-09-13 at 11 51 42 AM](https://user-images.githubusercontent.com/845363/189948421-ef7facec-be76-46b6-baeb-044b19285cd1.png)

Then I guess it would also link to the "access and use" tab.

**Comment by ccleeton** [comment]
I love this breadcrumb idea, more than a caption by the photo. Would it all be clickable?

**Comment by hackartisan** [comment]
I think it would all be clickable the same way it is in a search result.

**Comment by hackartisan** [comment]
So this proposal is:

* Add the storage note to the "Access & Use" tab. Still keep it on the "Collection Overview" tab.
* Add the library to the front of the breadcrumb in the search results, if clicked it takes you to the "Access & Use" tab of the collection show page.
* Add breadcrumbs to the top each component content area, above the component title. functionality the same as the breadcrumb on the search results page.
* Make the library image next to the collection title a clickable link that goes to the repository page (e.g. https://findingaids.princeton.edu/repositories/univarchives).

I'm curious what @sdellis thinks of this proposal.

**Comment by hackartisan** [comment]
I've updated the description of this ticket to make it be just about the breadcrumbs. I created #1167 and #1168 for the additional info / linkable image.
