### ISSUE TITLE
Show Online content icons on search results page

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1053]
Display the online content icon on search results page if digital content is available. In both grouped and all results

This is both the placement and the fact that an icon only shows up in "All Search Results" and not in the grouped results.

We don't need a wireframe, use your best judgement. Provide a screenshot.

**Comment by hackartisan** [comment]
Per wireframe review meeting, this should be the full "[icon] has online content" tag as seen next to a collection title on a show page. The full tag should be used in all search results. It should be placed next to the container info. Both should be dropped down to a new line below the title.

**Comment by sdellis** [comment]
I will check in with the POs to ensure this is what they want. I will also provide hex values with the colors of the icons/badges.
