### ISSUE TITLE
Ensure that content negotiation exposes XML encoded finding aids

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#107]
This is currently implemented in PULFA 2.0 in order to support the harvesting of collections and components by external organizations (please see https://findingaids.princeton.edu/collections/MC019/c01194 and https://findingaids.princeton.edu/collections/MC019/c01194.xml). A pattern is already structured for this in Blacklight with https://github.com/projectblacklight/blacklight/blob/master/lib/blacklight/routes/searchable.rb#L17, so this may be a minor enhancement.

We'll have to figure out how to save and manage these in a way that allows access to the EADs from multiple webservers.

## Implementation Proposal

* Create an AR Object with a text field, the call number string field, and an ID
* After downloading the XML stash it in postgres.
* For the pages just pull it from postgres if the record exists in SOLR.
* For component pages don't cache them, just parse it with Nokogiri and grab that component out.

**Comment by sdellis** [comment]
Allow the end user to access the EAD data from the Collections page UI, so users don't have to guess how they might access the data. A Creative Commons Attribution license should be presented in the path to access EAD so users know that they may reuse/remix that data with attribution.

**Comment by tpendragon** [comment]
@faithc @ccleeton @regineheberlein There's a full-sized HTML view of the content and staff are using ASpace. Do we need to provide the EAD data? It's not nearly as readily available when we're indexing out of aspace. If we do, can it be post-MVP?

**Comment by regineheberlein** [comment]
I’ll let others chime in, but my feeling is that it’s a core functionality, especially because more and more researchers do data mining on our finding aids.

Regine Heberlein
Library IT Data Analyst
609-258-6156
heberlei@princeton.edu

**Comment by faithc** [comment]
+1

**Comment by ccleeton** [comment]
+1 For me having access to the xml is sometimes the quickest way to find a barcode related to a box.

**Comment by tpendragon** [comment]
We don't have to support `?scope=record`, but we do need component XML. For now just export directly what's coming out of ASpace.
