### ISSUE TITLE
Homepage hours not displaying for SCF correctly

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1073]
The hours for Firestone are showing as not available. 

## Sudden Priority Justification

(from @ccleeton)

Adding sudden since the campus will have alot of visitors in the next few weeks

**Comment by ccleeton** [comment]
Adding sudden since the campus will have alot of visitors in the next few weeks

**Comment by tpendragon** [comment]
Kevin says the libcal ID changed, he'll get the new one for us.
