### ISSUE TITLE
Your Account Link

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1076]
Change the link of "Your Account" to https://lib-aeon.princeton.edu/aeon/aeon.dll
This will allow all users to login regardless of affiliation

**Comment by sdellis** [comment]
@ccleeton I'm just confirming that you're talking about the "Your Account" login in the main navigation bar, correct? It appears to be linked to that address in all other instances I can see, but I agree that linking to the Aeon login makes much more sense.

**Comment by ccleeton** [comment]
Yes the one in the nav bar because MANY of our outside researchers go right to that and try to log in and the current link only works for U members.
It also is much more intuitive to have a login at the top of the page instead of having to scroll "below the fold" to find the access.

**Comment by eliotjordan** [comment]
What do we do about the Sidekiq dashboard? As far as I can tell, it's only Pulfalight-specific functionality that requires authentication using CAS. To be fair, it's not very secure as anyone with a NETID can view and interact with it.

**Comment by hackartisan** [comment]
Good point. I'd vote to keep all the cas functionality in place for that. We don't need the login link, though, right? We can navigate directly to `/sidekiq`.
