### ISSUE TITLE
Link to Special Collections website on Landing page

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1077]
request for a link to https://library.princeton.edu/special-collections/ be placed on the landing page

Right now there is no link to the SC site from the finding aids.

Suggestions:
Add a link of some kind in the black bar
Add a link within the footer

We often get calls and emails from people stating they are having difficulty getting back to our website from the finding aids.

**Comment by hackartisan** [comment]
This ticket needs design

**Comment by m-ichelleliu** [comment]
Another potential option would be to link it in the "Request Materials" blurb, a la something like this: ![image.png](https://images.zenhubusercontent.com/62e3ec553e723055ba58287d/1a00a6c0-ba2b-42b8-be1d-13e8d23e04a3)

**Comment by ccleeton** [comment]
I like this idea. @faithc What do you think?

**Comment by hackartisan** [comment]
💯 looks like we're good to go on adding the link to the content area under Request Materials
