### ISSUE TITLE
Change Library names on landing page

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1079]
In Location and Today's Hours

Change the text in the gray box to say the following

Special Collections at Firestone
Special Collections at Mudd Manuscript Library

 (Alternative, if too long remove the _manuscript_ work.)

**Comment by tpendragon** [comment]
We can fix it here: https://github.com/pulibrary/pulfalight/blob/main/app/views/catalog/_hours.html.erb
