### ISSUE TITLE
Ensure that content is indexed in Google (and other major search engines) for discovery

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#108]
Generating a sitemap for this is essential (perhaps using https://github.com/sul-dlss/blacklight_dynamic_sitemap?) Additional, some focus towards microdata and JSON-LD for schema.org might be considered (please see https://github.com/projectblacklight/blacklight/issues/1952).

- [x] Add blacklight_dynamic_sitemap gem
- [x] Add config to pul_solr and deploy
- [x] Reindex pulfalight records
- [x] Let google know about sitemap

**Comment by eliotjordan** [comment]
This is done.
