### ISSUE TITLE
Catalog/record_not_found partial not found

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1082]
## Error

[PULFALight/production] ActionView::MissingTemplate: Missing template catalog/record_not_found, application/record_not_found with {:locale=>[:en], :formats=>[:ttf], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:  * "/opt/pulfalight/releases/20220519181300/app/views"  * "/opt/pulfalight/shared/bundle/ruby/2.7.0/gems/devise-4.7.1/app/views"  * "/opt/pulfalight/shared/bundle/ruby/2.7.0/gems/blacklight_range_limit-7.9.1/app/views"  * "/opt/pulfalight/sha...

## Backtrace

    line 490 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: block in <class:CatalogController>

## Context

User came from https://findingaids.princeton.edu/catalog/MC068_c00104

Error came from these params:

```
{
  "controller" => "catalog",
  "action" => "show",
  "id" => "Roboto-Regular",
  "format" => "ttf"
}
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/85491351)

**Comment by hackartisan** [comment]
This error looks pretty different on honeybadger now, but also hasn't happened in several months. closing / resolving.
