### ISSUE TITLE
Check log rotation, disk alerts

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1084]
Disk filled up on prod1.

- [x] We didn't see any alerts. Check datadog to ensure these machines are configured for disk space alerts
- [ ] Check log rotation and consider doing file size based rotation rather than time-based rotation to ensure logs don't fill up disk space

**Comment by hackartisan** [comment]
The alerts happened in slack on #datadog-alerts on May 6th and 16th.

**Comment by acozine** [comment]
We want to change the `minsize` param to `maxsize` - see https://stackoverflow.com/questions/20162176/centos-linux-setting-logrotate-to-maximum-file-size-for-all-logs.

**Comment by tpendragon** [comment]
Closed by https://github.com/pulibrary/princeton_ansible/pull/3084
