### ISSUE TITLE
new plugin that exports URIs with the EAD displaying in Box field and on call slip

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1090]
It looks like the ASpace URI of the archival object/component associated with the container is being pulled in for some reason.
![Untitled](https://user-images.githubusercontent.com/9676616/176704542-b5175074-2cc1-4848-9145-fb802c1c2ef6.png)

**Comment by tpendragon** [comment]
Product owners would like to keep the ASpace URI on the component show page (at the bottom), but leave it off the call slips.
