### ISSUE TITLE
yellow log-in box should always appear for components with OARSC content

### ISSUE THREAD

**Issue by kellybolding** [pulibrary/pulfalight#1096]
This came up at the last Virtual Reading Room WG meeting. We would like for the yellow OARSC log-in box (ex. https://findingaids.princeton.edu/catalog/C1436_c547) to always appear for components with OARSC content. @tpendragon had mentioned that this log-in box currently only shows up when there are approved users on the list for a particular collection. However, this presents an issue for users and public services staff in these cases because they have no way of knowing that an item is available in OARSC if the button is not appearing. The initial functional requirement for this involved making sure OARSC items were discoverable, so we see this more as core functionality than a bug. Sara Logue was also at our last meeting and requested this on behalf of Public Services.

(I thought this would be a Pulfalight ticket, but feel free to move it to Figgy if that's more appropriate.)

Thanks!

**Comment by tpendragon** [comment]
There might be an intersection with CDL - make sure it still works after this ticket.
