### ISSUE TITLE
Updates to Report Harmful Language form: Title and Message

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#1103]
In an effort to allow users to submit notice of harmful content as well as harmful language via the form, the title and message should be updated as such: 

Title: Report Harmful Language or Content Form

Message: 

Princeton University Library aims to describe archival materials in a manner that is respectful to the individuals and communities who create, use, and are represented in the collections we manage. However, for a variety of reasons, users may encounter offensive or harmful language, for example, language that is racist, sexist, or homophobic, in our finding aids. You may also encounter [harmful content](https://library.princeton.edu/statement-harmful-content) in the paper and digital records within archival collections.

Staff are currently implementing practices to address offensive or harmful language and harmful content as part of routine description work. We recognize that terminology evolves over time and that efforts to create respectful and inclusive description must be ongoing. You can help us address this issue by reporting any [harmful or offensive language](https://findingaids.princeton.edu/archival_language) or harmful content you encounter on this site by using the form below. If you would prefer to report this anonymously, you may leave the name and email fields blank.

## Sudden Priority Justification

This website feature serves as a way in which we are trying to mitigate both harmful language and content in archival collections. We'd like to know as soon as possible if a user encounters harmful language or content of which we're not aware in order to address it in a timely manner, and we would like the language associated with this feedback mechanism to be as clear as possible. Currently, it does not address the issue of harmful content. Thanks.

**Comment by faithc** [comment]
I just remembered that the text in the Feedback Welcome section of the landing page will have to be revised to reflect these changes as well.

**Comment by sdellis** [comment]
@faithc can you add a "sudden priority" reasoning to this ticket that would justify it being done before the next work cycle? Thanks!

**Comment by faithc** [comment]
This website feature serves as a way in which we are trying to mitigate both harmful language and content in archival collections. We'd like to know as soon as possible if a user encounters harmful language or content of which we're not aware in order to address it in a timely manner, and we would like the language associated with this feedback mechanism to be as clear as possible. Currently, it does not address the issue of harmful content. Thanks.

**Comment by sdellis** [comment]
From @faithc via Slack:
This looks good. Would it be possible to update the text of the button/icon as well to include "and content"?

Also, the Suggest a Correction text now needs to be changed to remove "[harmful or offensive language](https://findingaids-staging.princeton.edu/archival_language)," from "Corrections may include [harmful or offensive language](https://findingaids-staging.princeton.edu/archival_language), misspellings, incorrect or missing dates, misidentified individuals, places, or events, mislabeled folders, misfiled papers, etc." Might you be able to make this change as well?
