### ISSUE TITLE
Ensure that mobile devices (smartphones and tablets) are able to view and interact with PULFALight

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#111]
This support is limited at best for smartphones:

![image](https://user-images.githubusercontent.com/1443986/73426785-387e8500-4303-11ea-8050-d9b71257c009.png)

![image](https://user-images.githubusercontent.com/1443986/73426803-446a4700-4303-11ea-96c6-677385a4a494.png)

**Comment by jrgriffiniii** [comment]
Might we have any metrics on the current PULFA 2.0 site with mobile and tablet devices? Whether or not thorough testing for the user interfaces using smartphones and tablets should remain an MVP task has been raised as a discussion point when discussing project prioritization. @sdellis

**Comment by sdellis** [comment]
@jrgriffiniii yes, it looks like roughly half of 2.0 site users are on mobile devices (see screenshot below). This would likely be higher if it were not such a poor experience on mobile. I think it needs to remain a priority. 

<img width="624" alt="Screen Shot 2020-09-01 at 3 26 09 PM" src="https://user-images.githubusercontent.com/609368/91897157-dfdfe380-ec67-11ea-8fdb-4ed11d2bab6b.png">

**Comment by tpendragon** [comment]
User input:

In mobile, on the record screen, the table of contents is above the metadata. This means to get to the metadata, you have to scrollllll all the way to the bottom, which takes a long time, and it's not clear that's what you want.
