### ISSUE TITLE
Ongoing issues with Sidekiq/Redis

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#1117]
[PULFALight/production] Redis::CommandError: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/84752535)

**Comment by tpendragon** [comment]
We noticed this is always at 5 AM and 5 PM. @acozine going to see if there's anything running on those pulfalight boxes at that time.

**Comment by acozine** [comment]
Notes from some digging today:
This error message seems to indicate that a long-running Lua script is still in progress on the Redis server. We have two projects that use Lua (that I can find): special_collections and pul_library_drupal. 
This [SO post](https://serverfault.com/questions/999431/how-to-fix-the-redis-is-busy-running-a-script-error) suggests we could modify the global `lua-time-limit` for the Redis server (by default 5,000 ms). This [GitHub issue](https://github.com/nyagato-00/predictor/issues/41) suggests we could increase the Redis client timeout.

**Comment by acozine** [comment]
Discussed today, we will try the `Redis.new timeout` option, though we're not convinced this will work. If that does not fix this problem, we can look again.

**Comment by eliotjordan** [comment]
DLS will try the timeout option.

**Comment by hackartisan** [comment]
To set timeout via sidekiq, see https://github.com/sidekiq/sidekiq/wiki/Using-Redis#life-in-the-cloud

We'll likely need to do the setting this way since Redis.current is deprecated. For an example see figgy https://github.com/pulibrary/figgy/blob/65869b68b2c9a174d8ef4c03646858f03f85c683/config/initializers/sidekiq.rb#L2
