### ISSUE TITLE
add new physloc codes

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#1136]
We're adding 9 new location codes to finding aids; could you add them to pulfalight please? 

Background: the reason we're doing this is so we can tell apart material that's requestable from the catalog vs. material that is in the catalog but should be requested from the finding aids; we'll use the physloc codes to suppress the "request in reading room" button in orangelight. 

The display values for the new locations should be the same as their equivalents as follows:

```
 scarcpxm (same as rcpxm)
 scactsn (same as ctsn)
 scagax (same as gax)
 scamss (same as mss)
 scawa (same as wa)
 scaex (same as ex)
 scahsvm (same as hsvm)
 scamudd (same as mudd)
 scathx (same as thx)
```

See related https://github.com/pulibrary/orangelight/issues/2910

**Comment by faithc** [comment]
Added this to a work-cycle ticket for the current sprint @tpendragon @ccleeton as I believe these data changes will be implemented in the near future.
