### ISSUE TITLE
Display breadcrumbs in "Search Within Collection" result sets

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1153]
## Summary
All Search results that represent series and component records should display breadcrumbs that display the hierarchical context of the records. This currently works for global search results, but not for search within a collection which only diplay the repository (Public Policy Papers, University Records, Manuscripts, etc.). Breadcrumbs should display for the search within results the same way they display for global search results. 

See the screenshots for details:

### Global Search Results 
<img width="1038" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzV6QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6720725f7cd6cb791e3d0bae7701ff914cebbb36/Screenshot%202024-06-18%20at%204.42.40%E2%80%AFPM.png" alt="Screenshot 2024-06-18 at 4.42.40 PM.png" />

### Search Within a Collection Results (missing breadcrumbs)
<img width="711" alt="Screen Shot 2022-09-22 at 11 12 11 AM" src="https://user-images.githubusercontent.com/609368/191785234-1cf063bf-472e-4494-9e3f-35993066b791.png">

## Acceptance Criteria 
Breadcrumbs should display and be clickable for search within results.

## First Step

- [ ] Write a feature test.

**Comment by faithc** [comment]
@sdellis are you referring to the fact that pulfalight doesn't include contextual breadcrumbs like pulfa used to, i.e., the information that displays as part of "Contained in": https://pulfa.princeton.edu/?v1=Abraham+Lincoln&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0?

**Comment by faithc** [comment]
Hey @sdellis - just wanted to check in about my question above. Of course it seems like pulfa was finally taken down re: the example I provided. Haha But basically wondering if this ticket is meant to address the fact that contextual breadcrumbs/the hierarchy doesn't display in search results, like so: https://archives.lib.duke.edu/catalog?q=Fitzgerald&search_field=all_fields&view=list. We want to add these back!

**Comment by ccleeton** [comment]
The hierarchy is currently working in a full finding aid search but not when searching within a collection

**Comment by ccleeton** [comment]
the hierarchy might not make sense to many researchers. Would a hover explanation help? This might be a separate ticket if needed.
