### ISSUE TITLE
Add location information to each item in the Request Cart

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1154]
This image should provide the guidance necessary to work this ticket:

<img width="506" alt="Screen Shot 2022-09-22 at 1 35 31 PM" src="https://user-images.githubusercontent.com/609368/191814493-48dd385b-54ef-4a6f-af90-accf004a09d0.png">

**Comment by ccleeton** [comment]
Can we change it to say "up to 3 business days" please? 
Giving hours can be misleading. We also note it can take 2-3 business days not just 48 hours.

**Comment by ccleeton** [comment]
I also think that ADAPT wants to see the text in the finding aids as noted in the original ticket.

**Comment by sdellis** [comment]
FYI, I released LUX version 4.5.0, which has the truck delivery icon that we can use to implement this ticket. 
https://pulibrary.github.io/lux/docs/#/Icons/LuxIconDelivery

**Comment by hackartisan** [comment]
There's already a spot for this functionality in the request cart code

https://github.com/pulibrary/pulfalight/blob/1a931fdc91178b21e4d5b1a36227d61c42077843/app/javascript/components/RequestCart.vue#L82-L94

**Comment by hackartisan** [comment]
@ccleeton the delivery time portion of this issue has been implemented and deployed.

**Comment by tpendragon** [comment]
I just about have the location part of this done, but I need URLs for the locations.

Also I think the valid locaitons are "Firestone Library", "Mudd Manuscript Library", "ReCAP", "Engineering Library", "Annex B", and "Plasma Physics Library" - want to confirm I have the right ones.

**Comment by tpendragon** [comment]
Ping @faithc and @ccleeton for above when y'all got time.

**Comment by ccleeton** [comment]
For Firestone and Mudd let's link to this - https://library.princeton.edu/special-collections/visit-us
Engineering - https://library.princeton.edu/engineering
PPL - honestly I am feeling a bit dumb because I can't figure out where we should be directing people.
RECAP And Annex B - @faithc do you have a suggestion for this? Both are physical locations that cannot be accessed. Maybe those just don't have a link?

**Comment by faithc** [comment]
I don't think Plasma Physics is a repo/location. It seems that collections related to plasma physics are part of UA or Engineering. 

Another repo/location is the East Asian Library. It looks like the lone collection associated with that location is at ReCAP. 

Are there collections at Annex B? 

It also makes sense to me for ReCAP and Annex B to not have a link. Can the location name for both be something like "Offsite storage facility"?

Do we think links in general are necessary here?

**Comment by ccleeton** [comment]
I think links for Firestone and Mudd are useful. I also think keeping the names of Annex and Recap are helpful for staff but just not a link.
Are EA items circulated at firestone then keeping that not a link makes sence to me.

**Comment by faithc** [comment]
I'm not sure if EA01 would be viewed at Firestone, but I think associating it with that location for now should be sufficient. Should this also then get the https://library.princeton.edu/special-collections/visit-us link?

**Comment by ccleeton** [comment]
I think that is the safest option. I have also just added a link on that page to the ask us form so people can get to us if needed

**Comment by tpendragon** [comment]
I'm hearing:

Firestone Library -  https://library.princeton.edu/special-collections/visit-us
Mudd Manuscript Library - https://library.princeton.edu/special-collections/visit-us
ReCAP - No Link
Annex B - No Link
Engineering Library - https://library.princeton.edu/special-collections/visit-us
PPPL - No link, and probably won't show up anywhere.

RIght?

So it's either visit special collections or nothing.

**Comment by faithc** [comment]
Engineering should be https://library.princeton.edu/engineering.
EA should be https://library.princeton.edu/special-collections/visit-us (for now).

**Comment by ccleeton** [comment]
Just looking at this example - https://findingaids.princeton.edu/catalog/MC016_c7860
and the text says view at the Recap which is going to be confusing for researchers since they literally can't. The truck underneath is good but I am concerned about the text

**Comment by tpendragon** [comment]
So based on repository instead of container location?

**Comment by ccleeton** [comment]
Yes that seems as though it would work
