### ISSUE TITLE
Update physloc codes

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#1158]
Code values added in https://github.com/pulibrary/pulfalight/issues/1136 are incorrect. They should be updated to:

```
scarcpxm: 'Manuscripts Remote Storage (ReCAP)'
scactsn: 'Cotsen Children’s Library Archival'
scagax: 'Graphic Arts Archival'
scamss: 'Manuscripts Archival'
scawa: 'Western Americana Archival'
scaex: 'Rare Books Archival'
scahsvm: 'Manuscripts High Security Archival'
scamudd: 'Mudd Archival'
scathx: 'Theater Archival'
```

**Comment by eliotjordan** [comment]
@tpendragon No I'm not sure.
@regineheberlein Your Slack message from this morning seems to imply something different.

>  We want to make sure pulfalight passes the codes, e.g.
scamudd
to Aeon for requesting.

Please advise.

**Comment by eliotjordan** [comment]
I see now that the UI text for the locations goes here:
https://github.com/pulibrary/pulfalight/blob/main/config/location_codes.yml

Not sure about the physloc codes. Maybe something like:

```
scamudd: 'scamudd'
```

if those codes are what Aeon is expecting.

**Comment by regineheberlein** [comment]
So does pulfalight map the Aeon "sites", i.e. pickup locations? If so, they are:
| site | physloc | Alma label
| --- | --- | ---
RBSC | scarcpxm | 'Manuscripts Remote Storage (ReCAP). Special Collections Use Only'
RBSC | scactsn | 'Cotsen Children’s Library Archival. Special Collections Use Only'
RBSC | scagax | 'Graphic Arts Archival. Special Collections Use Only'
RBSC | scamss | 'Manuscripts Archival. Special Collections Use Only'
RBSC | scawa | 'Western Americana Archival. Special Collections Use Only'
RBSC | scaex | 'Rare Books Archival. Special Collections Use Only'
RBSC | scahsvm | 'Manuscripts High Security Archival. Special Collections Use Only'
MUDD | scamudd | 'Mudd Archival. Special Collections Use Only'
RBSC | scathx | 'Theater Archival. Special Collections Use Only'

**Comment by tpendragon** [comment]
Ah, okay. Pulfalight does two things:

Map `physloc` to SITE:

https://github.com/pulibrary/pulfalight/blob/2d88ebe0e49d76515a0910d4db79c265de18b06e/app/values/aeon_request.rb#L85-L87

and

https://github.com/pulibrary/pulfalight/blob/2d88ebe0e49d76515a0910d4db79c265de18b06e/lib/pulfalight/traject/ead2_config.rb#L99-L106

and also map container locations to Location

https://github.com/pulibrary/pulfalight/blob/2d88ebe0e49d76515a0910d4db79c265de18b06e/app/values/aeon_request.rb#L98-L100

and 

https://github.com/pulibrary/pulfalight/blob/2d88ebe0e49d76515a0910d4db79c265de18b06e/app/values/aeon_request.rb#L109-L112

I think you need some tests in https://github.com/pulibrary/pulfalight/blob/main/spec/values/aeon_request_spec.rb to

A) Make sure Site gets populated for those physloc codes
B) Make sure Location replaces those sca codes with the other codes.

The goal is, in Aeon, for `scahsvm` to have a `Location` of `hsvm` and a `Site` of `RBSC`, for instance, yeah?

**Comment by tpendragon** [comment]
Alternatively, if we want the UI and Aeon to always act as if "sca" isn't in a location code, we could just index without those - if it finds "scaxxx" it indexes "xxx"

**Comment by regineheberlein** [comment]
Oh, that is so much better! Yes, that would be ideal. The raison d'etre of the new codes is purely to allow us to have things in the catalog BUT not have them requestable from there; they are "twins" to existing location codes in each case. So indexing with out the `sca`- prefix sounds like an elegant solution.
