### ISSUE TITLE
Ability to search by box number and/or box and folder number

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#116]
Staff often know the collection code and box and/or folder numbers, so being able to search by them saves time compared to finding a collection and then navigating to the box/folder. Indexing some combined format "C1234_box12" or "C1234_box12_folder2" so staff can accurately search by these numbers would help make that work smoothly.

**Comment by regineheberlein** [comment]
For dsc[2] containers, this should be fairly straightforward. All retrieval containers are described in the dsc[2], e.g. MC016 Box 26:
```
<c level="otherlevel" otherlevel="physicalitem" id="MC016_i2">
				<did>
					<container type="box">26</container>
					<unitid type="barcode">32101106254731</unitid>
					<physloc type="code">rcpph</physloc>
				</did>
</c>
```
Items or subcontainers contained in the retrieval container are referenced in the dsc[1] through the container/@parent, e.g. MC016 Box 26 Reel 6:
```
<container type="reel" parent="MC016_i2">6</container>
```

The situation is a little murkier for "classic" containers. Other than box/folder pairs and multiple single-type containers, we currently have the following scenarios represented in our EAD files (though the Mudd dsc[2] Retro Project currently underway will significantly cut down on the variety and in particular on the various cabinet/drawer scenarios):

```<did count="1249">
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
</did>
<did count="734">
   <type>folder</type>
   <type>page</type>
</did>
<did count="660">
   <type>item</type>
   <type>page</type>
</did>
<did count="650">
   <type>box</type>
   <type>reel</type>
</did>
<did count="605">
   <type>volume</type>
   <type>folio</type>
</did>
<did count="470">
   <type>box</type>
   <type>volume</type>
</did>
<did count="412">
   <type>case</type>
   <type>box</type>
</did>
<did count="368">
   <type>box</type>
   <type>case</type>
</did>
<did count="346">
   <type>scrapbook</type>
   <type>page</type>
</did>
<did count="259">
   <type>box</type>
   <type>item</type>
</did>
<did count="183">
   <type>reel</type>
   <type>box</type>
   <type>folder</type>
</did>
<did count="167">
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
</did>
<did count="150">
   <type>portfolio</type>
   <type>packet</type>
</did>
<did count="148">
   <type>box</type>
   <type>cassette</type>
</did>
<did count="100">
   <type>volume</type>
   <type>page</type>
</did>
<did count="94">
   <type>reel</type>
   <type>item</type>
</did>
<did count="63">
   <type>box</type>
   <type>file</type>
</did>
<did count="46">
   <type>case</type>
   <type>drawer</type>
</did>
<did count="31">
   <type>folder</type>
   <type>reel</type>
</did>
<did count="22">
   <type>file</type>
   <type>folder</type>
</did>
<did count="22">
   <type>box</type>
   <type>tape</type>
</did>
<did count="15">
   <type>folder</type>
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
</did>
<did count="13">
   <type>cabinet</type>
   <type>drawer</type>
</did>
<did count="8">
   <type>scrapbook</type>
   <type>page</type>
   <type>page</type>
</did>
<did count="6">
   <type>box</type>
   <type>folders</type>
</did>
<did count="5">
   <type>folder</type>
   <type>folder</type>
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
</did>
<did count="2">
   <type>box</type>
   <type>box</type>
   <type>folder</type>
</did>
<did count="2">
   <type>drawer</type>
   <type>folder</type>
</did>
<did count="2">
   <type>box</type>
   <type>folder</type>
   <type>folder</type>
</did>
<did count="2">
   <type>box</type>
   <type>binder</type>
</did>
<did count="2">
   <type>folder</type>
   <type>folder</type>
   <type>folder</type>
   <type>folder</type>
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
</did>
<did count="2">
   <type>folder</type>
   <type>folder</type>
   <type>folder</type>
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
</did>
<did count="2">
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
   <type>box</type>
</did>
<did count="1">
   <type>folder</type>
   <type>reel</type>
   <type>reel</type>
</did>
<did count="1">
   <type>scrapbook</type>
   <type>page</type>
   <type>page</type>
   <type>page</type>
</did>
<did count="1">
   <type>bin</type>
   <type>folder</type>
</did>
<did count="1">
   <type>folder</type>
   <type>cabinet</type>
   <type>folder</type>
</did>
<did count="1">
   <type>drawer</type>
   <type>folder</type>
   <type>folder</type>
</did>
<did count="1">
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
</did>
<did count="1">
   <type>cabinet</type>
   <type>drawer</type>
   <type>box</type>
</did>
<did count="1">
   <type>folder</type>
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
</did>
<did count="1">
   <type>box</type>
   <type>box</type>
   <type>box</type>
   <type>cabinet</type>
   <type>drawer</type>
   <type>folder</type>
</did>
<did count="1">
   <type>box</type>
   <type>folder</type>
   <type>box</type>
</did>
<did count="1">
   <type>cabinet</type>
   <type>folder</type>
   <type>drawer</type>
</did>```

**Comment by sdellis** [comment]
To follow up on Regine's description of "classic" containers being "murkier" we keep a list of what is considered a ["container"](https://github.com/PrincetonUniversityLibrary/pulfa/blob/production/webapp/xsl/component2html.xsl#L617-L646) and ["subcontainer"](https://github.com/PrincetonUniversityLibrary/pulfa/blob/production/webapp/xsl/component2html.xsl#L813-L831) in the XSL. This helps us figure out what to send to Aeon when users request a component. 

The introduction of several new container types from Mudd has perhaps made this a bit more confusing, but I'm not sure we need them anymore, given the desire to implement the DSC2 approach. (It would be helpful to remove them in the current system if they are no longer needed.)

**Comment by regineheberlein** [comment]
@sdellis Indeed, except the container/subcontainer divide is not always consistent. Things like box + item or box + reel etc. are sometimes a container AND an item and sometimes an item IN a box. The barcoding project has actually helped a lot in flushing those out.

**Comment by jrgriffiniii** [comment]
Following some discussion on 02/28/20, the next step for supporting this feature will be to require mockups for possible solutions.

**Comment by khanhvu98kk** [comment]
This work was started in this branch: https://github.com/pulibrary/pul_solr/compare/pulfalight-116-containernumber?expand=1. Once this ticket has further specified, we can pick it up again later.

**Comment by sdellis** [comment]
It's unclear to me why this has the "wireframe" and "visual design" labels. This is a fairly straightforward request to allow for searching for containers within a collection. 

However, rather than using underscores as suggested above (C1234_Box12_Folder2), I would use more common search syntax of quoting strings with spaces". 

So, if one searches for `C1234 "Box 12" "Folder 2"` the only search result would be the component in C1234 that has that container.
