### ISSUE TITLE
Change TOC icon for branch-level (series) nodes that may have some online components

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1160]
These icons would be the same as the green ones, but instead they would have the following HEX color: #636363

Example that should have this hex: https://findingaids.princeton.edu/catalog/C0022_c0089

**Comment by sdellis** [comment]
See this screenshot (the "General, 1918 - 1995" node):
<img width="379" alt="Screen Shot 2022-09-26 at 2 39 43 PM" src="https://user-images.githubusercontent.com/609368/192354887-9db6af39-eb33-44ee-82dc-4cf5bdca5817.png">

**Comment by tpendragon** [comment]
When implementing this, also try a lighter green and we'll decide what to do. Ping @eliotjordan when you try.
