### ISSUE TITLE
Update the icon tooltip in the TOC to have clearer info

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1163]
The tooltip should say "has online content" or "some online content" instead of simply "online"
![Screen Shot 2023-06-29 at 11.55.29 AM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/a08d5eef-705e-4949-8174-28ba229fbd8a)

**Comment by tpendragon** [comment]
Grayed out ones should say "some online content", the green ones should say "has online content"
