### ISSUE TITLE
Component pages should display badges with their online content status

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1164]
If it has online content, it should look like the screenshot, green badge, green icon and "HAS ONLINE CONTENT" text. 

HAS ONLINE CONTENT:
color: #1D8235
background-color: #F4FEF5
border-color: #1D8235

If it has children with online content, it should be a gray badge, with a grey icon and it should say "SOME ONLINE CONTENT". Here are the hex codes:

SOME ONLINE CONTENT
color: #636363
background-color: #E3E0E0
border-color: #C7C4C4

![HAS-ONLINE-CONTENT](https://user-images.githubusercontent.com/609368/192357918-9dea2c26-680c-4c12-825c-95f6e95a3c2d.JPG)

**Comment by tpendragon** [comment]
If we pick a not-gray color for #1160, match the color here.
