### ISSUE TITLE
Move "box number" and "extent" badges below the header in line with the online content

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1172]
All should be below the title as they currently are.

See wireframes produced for https://github.com/pulibrary/pulfalight/issues/1099

Adjust styling to make badges consistent.

**Comment by tpendragon** [comment]
Existing state:
![Screen Shot 2023-06-29 at 11.58.13 AM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/632c07d7-0674-4026-bb9b-86004a463c2f)

**Comment by tpendragon** [comment]
Put all the tags below the header in the search results on the same line.
