### ISSUE TITLE
Repurpose bookmarks into cart/request functionality

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#118]

**Comment by apferrar** [comment]
![Screen Shot 2020-03-24 at 10 16 06 AM](https://user-images.githubusercontent.com/32106332/77435878-342d9000-6db9-11ea-9be2-3db443ced2c7.png)
![Screen Shot 2020-03-24 at 10 15 44 AM](https://user-images.githubusercontent.com/32106332/77435885-368fea00-6db9-11ea-9f4c-12a774904ca2.png)
![Screen Shot 2020-03-24 at 10 15 27 AM](https://user-images.githubusercontent.com/32106332/77435888-37288080-6db9-11ea-8f95-99d05ad2df25.png)
![Screen Shot 2020-03-24 at 10 15 13 AM](https://user-images.githubusercontent.com/32106332/77435892-37288080-6db9-11ea-855b-ae3f02ca5abb.png)

**Comment by jrgriffiniii** [comment]
Given that a LUX component is being actively developed to produce a preferred solution for request management at the collection level (or for multiple components across collections), this has been deprecated in favor of just disabling the bookmark feature outright.
