### ISSUE TITLE
Build a list of IPs that need access to aspace

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1183]
A couple times a year there is a change to the IPs for one or more of our VPN machines and we have to email lyrasis and ask them to update our allowed IPs list. The process has gotten a lot easier, but it would be even easier if every time we have to write them we could say "here's the entire list" instead of "here are the VPNs and please don't erase those other non-VPN ones when you make this change". So I'd like to build a list of all the IPs that need access to aspace, I'm thinking in a shared lastpass note. I have all the IPs on their list from about 6 months ago, but I don't know what all of them are for.

Who would need to be consulted in order to build such a list? Maybe @regineheberlein and someone in ops (@acozine)?

**Comment by regineheberlein** [comment]
Happy to help. This might also be a good one to crowdsource--I myself don't have an overview of the machines that need to be on that list.

**Comment by regineheberlein** [comment]
I was thinking of broadcasting this ticket to all of IT (on `#it-general` perhaps?), plus Will C. in SC?

**Comment by acozine** [comment]
This sounds like a great idea. I'm happy to participate too. 

Do you know why the IPs change? I don't think I've experienced this yet.

**Comment by hackartisan** [comment]
@acozine Our VPN provider just doesn't guarantee IP persistence, and they change occasionally. The aspace configuration doesn't accept domain-based auth.
