### ISSUE TITLE
Use actual component ids (with dots) in urls

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1185]
Figgy stores the id with the dots and links to the finding aid. Everything is easier if the findingaid url just uses the actual component id.

Here are some example items:

- https://findingaids.princeton.edu/catalog/C1491_c87307-37697
- https://findingaids.princeton.edu/catalog/C1491_c99167-65619
- https://findingaids.princeton.edu/catalog/C1491_c10986-49249

## To Fix:

Update routes.rb similar to https://github.com/pulibrary/figgy/blob/792ac531a5c59187578073a6d6c37af6e60d458d/config/routes.rb#L295

**Comment by sdellis** [comment]
There are two different syntaxes being used in PulfaLight that could complicate the regular expressions needed to fix:
1. https://findingaids.princeton.edu/catalog/AC198-05_c1791
2. https://findingaids.princeton.edu/catalog/C1491_c87307-37697

We will want to write tests to ensure both of these syntaxes resolve.

**Comment by hackartisan** [comment]
I think that in both cases the dash is replacing a dot, and the underscore is part of the component id. Here's the figgy record for the first example in the previous comment https://figgy.princeton.edu/catalog/994e4d15-d6e9-49bd-b483-6cd8fd63a810/

**Comment by hackartisan** [comment]
I'm not really sure anymore that we should do this. There are several, integration points around this id, and messing with the url this far into the life of the application would be a pain. We've fixed several integration points and I think we're likely close to whacking the final mole. I'm gonna put this back in the inbox so we can re-assess. I think https://github.com/pulibrary/figgy/issues/5459 may be the last issue otherwise; I'm reopening that.
