### ISSUE TITLE
Online Content icons not appearing for some components

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#1221]
For reference, this component should have an online content icon:

https://findingaids.princeton.edu/catalog/MC104-13_c0034
https://findingaids.princeton.edu/catalog/MC104-13_c0034.xml

Also, may be related to the broken XML for components.
See: https://github.com/pulibrary/pulfalight/issues/799

**Comment by tpendragon** [comment]
This is probably a missing DAO. If edit the record in Figgy and save it again it'll probably fix it?

**Comment by faithc** [comment]
This seems to be ok now?
