### ISSUE TITLE
Implement new access note data model

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#1225]
See the following document for information about this change/request: https://docs.google.com/document/d/1_Qtpn7GP52w9f6FOQpiwvw-lP8ogbwYXF9feryxHmDM/edit.

See related issues #1093 and #497 

It would be ideal if we had a pulfalight staging site to test this out before adding it to prod -- qa infrastructure is ticketed in #1252

I think the field referenced here is `access_ssi`

**Comment by phoebeno** [comment]
1) OPEN. Collection-level, series-level or component-level access type is blank: this is considered equal to "open" and no badge should display. 
2) REVIEW. Collection-level, or series-level access type is "review": display badge "Restrictions may apply. See Access note." (yellow) (not used at component level)
3) RESTRICTED. Collection-level, series-level, or component-level access type is "restricted": display badge "Restricted content." (red)

Restriction types filter DOWN from collection level and file group level. No need for restriction types to filter up from components any longer.

**Comment by tpendragon** [comment]
We're looking for examples for all the scenarios in https://docs.google.com/document/d/1xdP80sQ2Z_Smul0EPlkYcbT7rXXnAkrOsOhtldubvM4/edit so we can develop test fixtures and local development.

**Comment by tpendragon** [comment]
Something that would make this easier is a QA infrastructure that's pointed at production aspace.

**Comment by faithc** [comment]
> We're looking for examples for all the scenarios in https://docs.google.com/document/d/1xdP80sQ2Z_Smul0EPlkYcbT7rXXnAkrOsOhtldubvM4/edit so we can develop test fixtures and local development.

This scenarios doc is now outdated. Will send examples of how the new data model is being implemented.

**Comment by faithc** [comment]
@tpendragon Are these the types of examples you're looking for?

1. Toni Morrison (C1491)- some scenarios include the following: 
- Collection-level access note type is set to "review." 
- This series is also set to “review”: [https://findingaids.princeton.edu/catalog/](https://findingaids.princeton.edu/catalog/C1491_c1622)C1491_c1. 
- This is one of many components that are marked with type "restricted": https://findingaids.princeton.edu/catalog/C1491_c1622.

**Comment by tpendragon** [comment]
@faithc Yup, do you have one where there's no top-level note and one below is marked something?

**Comment by faithc** [comment]
I don't think that use case should exist anymore. Any collection that includes a restriction or materials that need review should now have the "review" value at the collection level. Collections with no value type at the collection level should all be totally open. Does that make sense?

**Comment by tpendragon** [comment]
This is live on QA, folks are testing it now.
