### ISSUE TITLE
[PULFALight/production] MultiXml::ParseError: 55:811: FATAL: Opening and ending tag mismatch: extref line 55 and phystech

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1238]
[PULFALight/production] MultiXml::ParseError: 55:811: FATAL: Opening and ending tag mismatch: extref line 55 and phystech

repositories/5/resource_descriptions/4274

You can get the resource from the cache on the production rails console with `x = XmlCache.find_by(resource_descriptions_uri: "repositories/5/resource_descriptions/4274")`. Then you can look at `x.content` to see the xml.

## Backtrace

    line 58 of [PROJECT_ROOT]/app/services/aspace/client.rb: get_resource_description_xml
    line 46 of [PROJECT_ROOT]/app/jobs/aspace_index_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/82623269)

**Comment by tpendragon** [comment]
This is a missing phystech note, we've notified #pulfalight. Resolved.
