### ISSUE TITLE
Search tips

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#124]
Include search tips like in the current pulfa site that are more visible than how they currently are (i.e right now there is a link under the main search bar in the current site that opens a pop up window). They'd need to be reviewed for current language. It should also contain a "How to Browse this collection" section rather than being separate (ex: https://findingaids.princeton.edu/collections/AC234 ; top of the page under the collection title)

**Comment by hackartisan** [comment]
Added as part of https://github.com/pulibrary/pulfalight/pull/475
