### ISSUE TITLE
Review the prepopulated search results (default search results)

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#125]
They're helpful and we like that they exist in the current iteration of the staging site.

**Comment by tpendragon** [comment]
@jrgriffiniii What are the "prepopulated search results"?

**Comment by tpendragon** [comment]
@faithc @ccleeton Do either of you know what this is in reference to? If not, maybe close this?

**Comment by ccleeton** [comment]
I am not sure, @faithc do you remember what Mandy meant?

**Comment by faithc** [comment]
I think this was just us noting that we liked this feature, so I think it can be closed. :)
