### ISSUE TITLE
Cover images and "Aviso de contenido" label

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#1259]
As our Spanish-language finding aids are now bilingual, we are wondering if "Aviso de contenido," which is being used as a label in addition to "Content Warning," could also be applied to the current functionality in Figgy in which cover images are automatically applied when this note/label exists. Thanks.

Not sure whether this ticket should be added to the Figgy repo? (@tpendragon )

**Comment by tpendragon** [comment]
I think we can keep it in Pulfalight. We'll need an example.

**Comment by faithc** [comment]
Great. And yes, sorry about that: https://findingaids.princeton.edu/catalog/C1603_c75148-21421.

**Comment by faithc** [comment]
Oh, right. That's a good question. Let me check on that.

**Comment by faithc** [comment]
Ok, never mind. Both labels/notes will always be present, so never mind! Sorry about that!
