### ISSUE TITLE
Collection level extents not displaying consistently. 

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#127]
Here's an example: https://pulfalight-staging.princeton.edu/?group=true&q=american+civil+liberties+union&search_field=all_fields&view=compact  group by collection, you can see that ACLU 2, Lillenthal, and Doar are all different. Faith checked the data and it seemed to be consistent so she thinks it has to do with the site.

**Comment by jrgriffiniii** [comment]
There are differences in units and the information which is encoded at the collection-level EAD  - there should be two extent tags: one for linear footage, and another for number of containers. Both of these should be indexed in Solr and rendered in search results.

**Comment by jrgriffiniii** [comment]
I'm currently finding that, within the EADs for two of the example collections, the `<extent>` content is being indexed directory from the EAD file:

mudd/publicpolicy/MC001.02.EAD.xml:
```xml
<physdesc>
  <extent unit="footage">1917-1946 ACLU Records, 1886 bound volumes and 12 archival boxes (on 288 reels of microfilm) 1947-1995 ACLU Records, 899.37 linear feet</extent>
  <extent>2004 archival boxes, 20 half-size archival boxes, 21 archival shoeboxes, 20 16x20 photo boxes, 11 8x10 photo boxes, 9 film canisters, and 1 24x36 photo box</extent>
</physdesc>
```

mudd/publicpolicy/MC148.EAD.xml:
```xml
<physdesc>
  <extent unit="footage">278.9 linear feet</extent>
  <extent>632 boxes and 2 oversize folders</extent>
</physdesc>
```

I am not certain how to reconcile this - I can approach this by setting extents at the repository level, but that would then be applied for all `publicpolicy` collections in this case. Is there a way for me to identify from a collection like MC148 that the extent from MC001.02 should be used?

**Comment by jrgriffiniii** [comment]
On the PULFA 2.0, I am currently finding that the `extent` values (mapped to `size` on the pages) do vary on the collection pages, so I can look to adjust this just in the search results:

![image](https://user-images.githubusercontent.com/1443986/80504406-0fd94c00-8941-11ea-8e2f-60e902416acf.png)


![image](https://user-images.githubusercontent.com/1443986/80504329-f932f500-8940-11ea-92eb-54dc7a35a84c.png)

**Comment by jrgriffiniii** [comment]
I apologize, but just to be thorough, I also wish to note that these are different on the search results interface for PULFA 2.0:

![image](https://user-images.githubusercontent.com/1443986/80504943-b1f93400-8941-11ea-8864-e05161d24b6f.png)

![image](https://user-images.githubusercontent.com/1443986/80504881-9b52dd00-8941-11ea-9d2a-3e6f9266493e.png)

**Comment by faithc** [comment]
I'm a bit unclear about some of the comments above, so apologies if my response doesn't totally address issues that you've articulated, @jrgriffiniii. I think what we wanted to point out is that extent data that displays on pulfa 2.0 does not always display in pulfalight. For instance, the Extent info in the example you provide above for the David Lilienthal Papers on pulfa 2.0 displays the data located in both extent tags within the physdesc element at the collection level (linear footage and containers), whereas only the data related to linear footage displays on pulfalight; the data included in the second extent tag doesn't display. 

And yes, extent info should be coming directly from the ead files.

**Comment by tpendragon** [comment]
@faithc Thanks for that! That clears things up considerably for me.

**Comment by jrgriffiniii** [comment]
For the file `mudd/publicpolicy/MC148.EAD.xml`:

```xml
<archdesc type="findingaid" level="collection" relatedencoding="marc21">
    <did>
        <physdesc>
            <extent unit="footage">278.9 linear feet</extent>
            <extent>632 boxes and 2 oversize folders</extent>
        </physdesc>
    </did>
</archdesc>
```

On the search results page, the `632 boxes and 2 oversize folders` field is not rendered:
![image](https://user-images.githubusercontent.com/1443986/87076351-a18df100-c1ef-11ea-8b1a-5642c46d3502.png)

...where this has the following on the show page:
![image](https://user-images.githubusercontent.com/1443986/87076413-b79bb180-c1ef-11ea-8ca8-840f3df45b2f.png)
