### ISSUE TITLE
Fix style of Online Banner when there's an access badge

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1281]
![Screen Shot 2023-07-12 at 2 32 55 PM](https://github.com/pulibrary/pulfalight/assets/2806645/4aaa5fa3-b591-47e0-bd17-3efee52b0d2e)

Taken at https://findingaids-qa.princeton.edu/catalog/AC118_c00216

**Comment by eliotjordan** [comment]
I'm seeing the same effect, but it looks slightly different. 
![Screenshot 2023-07-12 at 4 44 19 PM](https://github.com/pulibrary/pulfalight/assets/784196/6e205667-fd65-4b2c-b31b-f168c91a1f37)
