### ISSUE TITLE
Page should error with 404 not 500 when xml requested for non-existent record

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1292]
[PULFALight/production] ActionView::MissingTemplate: Missing template catalog/record_not_found, application/record_not_found with {:locale=>[:en], :formats=>[:xml], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :coffee, :jbuilder]}. Searched in:  * "/opt/pulfalight/releases/20230717150309/app/views"  * "/opt/pulfalight/shared/bundle/ruby/3.1.0/gems/devise-4.8.1/app/views"  * "/opt/pulfalight/shared/bundle/ruby/3.1.0/gems/blacklight_range_limit-7.9.1/app/views"  * "/opt/pulfalight/sha...

## Backtrace

    line 495 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: block in <class:CatalogController>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/94082878)

## Note

This is returning a 500 for non-existent records period, not just for XML.

## To work on it

Write a failing test
Make it pass

## Sudden Priority Justification

Staff need to know if a record is missing rather than "broken" so they can diagnose what's going on and how to report it.

**Comment by tpendragon** [comment]
This is sending a 500 even for HTML pages.

**Comment by hackartisan** [comment]
The html page actually is returning a 404, I think the error page is maybe getting overwritten at the load balancer so I will look into that.
