### ISSUE TITLE
Staging shouldn't sync to figgy and doesn't need to error

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1299]
[PULFALight/staging] SyncToFiggyJob::FiggyError: SyncToFiggyJob::FiggyError

## Backtrace

    line 18 of [PROJECT_ROOT]/app/jobs/sync_to_figgy_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/97961870)

**Comment by tpendragon** [comment]
Not happening we think we fixed it.

**Comment by hackartisan** [comment]
I thought maybe it was because of this but it doesn't seem like it; there's still an auth token defined in https://github.com/pulibrary/princeton_ansible/blob/0fb24c2d1e86deef06c52477e21d6f85a74a6994/group_vars/pulfalight/staging.yml#L80C33-L81 so not sure why it stopped happening.
