### ISSUE TITLE
Locations note in top container record should be in the call slip when requesting

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1317]
Requesting https://findingaids.princeton.edu/catalog/SL001_c1?onlineToggle=false should have "Scheide 68.7" in the ItemInfo4 when requesting it.

## Sudden Priority Justification

Staff have a very difficult time locating the box without the information on the call slip.

**Comment by tpendragon** [comment]
Oh, this is already happening. Maybe it's call slip configuration? @kevinreiss can you take a look and make sure ItemInfo4 is rendering on call slips?

**Comment by kevinreiss** [comment]
Can you see the value in the ItemInfo4 field in the request Aeon recorded? If you can and it's not printing out than it's an issue with the print template itself. If it's not there and Aeon isn't accepting the value pulfalight is passing that's weirder and needs to be a support ticket to atlas. If you need help with the print templates also please put in a support ticket with Atlas.

**Comment by tpendragon** [comment]
I don't know how to see the ItemInfo4 field in Aeon. As a user I don't see it anywhere in the request, but it does get forwarded by Pulfalight.

**Comment by kevinreiss** [comment]
This something any staff user of Aeon can check in the client.
