### ISSUE TITLE
Upgrade to Postgres 15

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1319]
Update CI to use postgres 15

Staging:

1. Turn off Pulfalight: `ansible pulfalight_staging -a "sudo service nginx stop && sudo service pulfalight-workers stop" -u pulsys`
2. Dump Database from old server to new server: `ansible lib-postgres-staging1.princeton.edu -e @group_vars/all/vault.yml -e @group_vars/pulfalight/staging.yml -m shell -a "export PGPASSWORD=\"{{vault_postgres_staging_admin_password}}\"; pg_dump -h lib-postgres-staging3 --format custom --clean {{application_db_name}} -U postgres  > /tmp/pulfalight_staging.dump" -u pulsys`
3. Provision database (on pulfalight_postgres_15 ansible branch): `ansible-playbook playbooks/pulfalight.yml --tags postgresql`
4. Restore database: `ansible lib-postgres-staging1.princeton.edu -e @group_vars/all/vault.yml -e @group_vars/pulfalight/staging.yml -m shell -a "export PGPASSWORD=\"{{vault_postgres_staging_admin_password}}\"; pg_restore -h 127.0.0.1 -U postgres --dbname {{ application_db_name }} /tmp/pulfalight_staging.dump" -u pulsys`
5. Run this branch: https://github.com/pulibrary/princeton_ansible/pull/4274 (`ansible-playbook playbooks/pulfalight.yml --tags site_config`)

QA:

1. Turn off Pulfalight: `ansible pulfalight_qa,pulfalight_qa_workers -a "sudo service nginx stop && sudo service pulfalight-workers stop" -u pulsys`
2. Dump Database from old server to new server: `ansible lib-postgres-staging1.princeton.edu -e @group_vars/all/vault.yml -e @group_vars/pulfalight/qa.yml -m shell -a "export PGPASSWORD=\"{{vault_postgres_staging_admin_password}}\"; pg_dump -h lib-postgres-staging3 --format custom --clean {{application_db_name}} -U postgres  > /tmp/pulfalight_qa.dump" -u pulsys`
3. Provision database (on pulfalight_postgres_15 ansible branch): `ansible-playbook playbooks/pulfalight.yml --tags postgresql -e runtime_env=qa`
4. Restore database: `ansible lib-postgres-staging1.princeton.edu -e @group_vars/all/vault.yml -e @group_vars/pulfalight/qa.yml -m shell -a "export PGPASSWORD=\"{{vault_postgres_staging_admin_password}}\"; pg_restore -h 127.0.0.1 -U postgres --dbname {{ application_db_name }} /tmp/pulfalight_qa.dump" -u pulsys`
5. Run this branch: https://github.com/pulibrary/princeton_ansible/pull/4274 (`ansible-playbook playbooks/pulfalight.yml --tags site_config -e runtime_env=qa`)

Production:

1. Turn off Pulfalight: `ansible pulfalight_production,pulfalight_production_workers -a "sudo service nginx stop && sudo service pulfalight-workers stop" -u pulsys`
2. Dump Database from old server to new server: `ansible lib-postgres-prod1.princeton.edu -e @group_vars/all/vault.yml -e @group_vars/pulfalight/production.yml -m shell -a "export PGPASSWORD=\"{{vault_postgres_admin_password}}\"; pg_dump -h lib-postgres-prod3 --format custom --clean {{application_db_name}} -U postgres  > /tmp/pulfalight_prod.dump" -u pulsys`
3. Provision database (on pulfalight_postgres_15 ansible branch): `ansible-playbook playbooks/pulfalight.yml --tags postgresql -e runtime_env=production`
4. Restore database: `ansible lib-postgres-prod1.princeton.edu -e @group_vars/all/vault.yml -e @group_vars/pulfalight/production.yml -m shell -a "export PGPASSWORD=\"{{vault_postgres_admin_password}}\"; pg_restore -h 127.0.0.1 -U postgres --dbname {{ application_db_name }} /tmp/pulfalight_prod.dump" -u pulsys`
5. Run this branch: https://github.com/pulibrary/princeton_ansible/pull/4274 (`ansible-playbook playbooks/pulfalight.yml --tags site_config -e runtime_env=production`)

**Comment by eliotjordan** [comment]
Done.
