### ISSUE TITLE
Cover warning should not display for components with inherited content note

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1321]
From Faith:

We recently noticed an issue with the behavior of content warnings/cover images. i don't think this was happening previously, so i'm wondering if it's perhaps a result of the recent functionality that was implemented so that content warnings inherit down. currently, it seems that cover images are being applied to all digital content for collections with a collection-level content warning. for example, this is happening with TC040; a specific example within that collection is https://findingaids.princeton.edu/catalog/TC040_c00034?onlineToggle=false. cover images should only be applied to components with content warnings that have been applied at that level and that have a dao. the inheriting functionality we requested was only meant to display the note. thanks for looking into this!

## Sudden Priority Justification

The current state will cause confusion and serve as an unnecessary impediment to accessing content. we don't want to be needlessly heavy-handed in applying cover images; we want to apply them thoughtfully. for example, having a cover image for this content doesn't make sense: https://findingaids.princeton.edu/catalog/TC040_c00034?onlineToggle=false.

## DLS Lead Note

We'll mark this as a sudden priority for a maintenance week because we don't have a Pulfalight cycle scheduled, this was a bug from our previous cycle, and it will affect our users negatively. It's prioritized below security upgrades and other sudden priorities that prevent folks from getting work done.

**Comment by tpendragon** [comment]
Inherited content warnings should render on the page, but not in the JSON. This probably means we need to index a new `direct_content_warning` field or something similar and render that in the JSON.

**Comment by sdellis** [comment]
Content Warning notes inherit down, except when they are overridden for individual components. When they are overridden for targeted description, the component viewer should get a Cover Warning and the Content Warning note should use the overridden value.

**Comment by faithc** [comment]
Just wanted to see whether y'all might be able to get to this ticket soon? Thanks.

**Comment by hackartisan** [comment]
It's in our ready column for maintenance. We're just starting a maintenance week now so hopefully!

**Comment by faithc** [comment]
Ok, thanks!

**Comment by tpendragon** [comment]
I tried to generate a new fixture for this, but the IPs for our aspace IP are out of date. :( I might look for a workaround later, since I think it just needs to re-process TC040, not redownload it.

**Comment by hackartisan** [comment]
Reopening; this isn't resolved until a reindex

**Comment by tpendragon** [comment]
I just realized we'll have to reindex all the pulfa item metadata to do this.

**Comment by tpendragon** [comment]
I ran `rake figgy:pulfalight:sync_resources`

**Comment by tpendragon** [comment]
Done!
