### ISSUE TITLE
Use new central redis

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1323]
This will allow us to merge https://github.com/pulibrary/pulfalight/pull/1322.

We'll need to update https://github.com/pulibrary/pulfalight/blob/32efaf1575e5d4235a95a84f66531ce6080b015d/config/initializers/sidekiq.rb; pulmap has a nice way of doing it https://github.com/pulibrary/pulmap/blob/09086a08f01b99257bf480c5eeb0dffbe38c9f43/config/initializers/sidekiq.rb

**Comment by tpendragon** [comment]
We need to update sidekiq configuration, then turn off workers, update sidekiq and point to the new server, and deploy.

**Comment by hackartisan** [comment]
this issue also depends on https://github.com/pulibrary/princeton_ansible/issues/4046 and https://github.com/pulibrary/princeton_ansible/issues/4294

**Comment by hackartisan** [comment]
Staging is done; reindex queued fine
