### ISSUE TITLE
Change "Collection context" heading

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#134]
i.e. https://pulfalight-staging.princeton.edu/catalog/MC231MC231_c0384 

Change, perhaps, to "Collection Overview" or "explore the rest of this collection"? or something of the like?

FC/AF will reach out to James re: the entire issue of browsing the Arclight's design

**Comment by jrgriffiniii** [comment]
Wireframes for this should be provided in order to capture feedback on earlier design ideas.

**Comment by sdellis** [comment]
We actually have [the original wireframes for the Collection Context](https://stacks.stanford.edu/file/druid:hd302yz0755/Arclight-Mockups-MVP.pdf). See page 10, Component Details. For some reason, Stanford did not design this in accordance with the recommendations of their own UX team. The original wireframe is closer to where we want to be.

**Comment by jrgriffiniii** [comment]
Closed in favor of #206
