### ISSUE TITLE
Does the name change for the Engineering Library break the collections indexing on the repo page?

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#1352]
### The Problem

When you go to the [Engineering Library's repo page ](https://findingaids.princeton.edu/repositories/eng), no collections associated with that repository are displayed.

I'm observing that the url of [a search grouped by collection](https://findingaids.princeton.edu/catalog?f%5Blevel_sim%5D%5B%5D=Collection&f%5Brepository_sim%5D%5B%5D=Lewis+Science+and+Engineering+Library) ends in  `Lewis+Science+and+Engineering+Library`. It gives no results.

If I change the search to end in `Engineering+Library` it succeeds, returning 4,247 results.

### Possible Cause

I recently [updated the Engineering Library's name and address](https://github.com/pulibrary/pulfalight/pull/1346) following the move of the collections to Fine Hall. That changed the name of the Library from "Engineering Library" to "Lewis Science and Engineering Library" in `config/repositories.yml`.

I suspect that the search grouped by repository is looking for "Engineering Library" and not finding it, getting "Lewis Science and Engineering Library" instead. I haven't figured out yet where in the code that happens.

**Comment by regineheberlein** [comment]
This is fixed after [reverting the slug in ASpace](https://github.com/pulibrary/aspace_helpers/issues/477) + reindex

**Comment by hackartisan** [comment]
related to https://github.com/pulibrary/pulfalight/issues/1350
