### ISSUE TITLE
Provision Jammy VMs

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#1355]
# Reasoning

We need to upgrade all our boxes to Jammy; we're starting to be unable to get apt packages, etc.

# Boxes to Migrate

These are the names of the existing boxes. We can change the names to use current conventions, suggestions inline.

## Staging
`pulfa3-staging1` => name the new box `pulfalight-staging1`

## QA
`pulfalight-qa-web-1` => name the new box `pulfalight-qa-web1`
`pulfalight-qa-worker-1` => name the new box `pulfalight-qa-worker1`

## Production
`pulfalight-prod1` => name the new box `pulfalight-prod3` I guess?
`pulfalight-prod2` => name the new box `pulfalight-prod4`?
`pulfalight-worker1` => name the new box `pulfalight-worker2`?

**Comment by acozine** [comment]
Leave existing boxes in place, add new boxes.

**Comment by acozine** [comment]
I've finished the first two of these boxes: pulfalight-qa-web1 and pulfalight-qa-worker1.

**Comment by hackartisan** [comment]
The QA boxes are all set. The old QA boxes can be deleted and production boxes can be created.

**Comment by acozine** [comment]
I've created the three new production boxes. I lost my head a little and put `jammy` in the names, so they are:

- pulfalight-jammy-prod1
- pulfalight-jammy-prod2
- pulfalight-jammy-prod-worker1

All three boxes have IPs and rules allowing SSH and HTTP/HTTPS per our usual approach. Do we need any other network rules?

**Comment by hackartisan** [comment]
I don't think we need any other rules. Pulfalight uses the central redis service.

**Comment by acozine** [comment]
Okay, the last box is up: `pulfalight-staging1` in the dev environment. Note that this box is re-using an IP address that previously belonged to one of the decommissioned bionic pulfalight QA boxes.

**Comment by hackartisan** [comment]
Done.
