### ISSUE TITLE
Add Topic Facet

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#136]
This will relate to the "browse topics" data referenced in https://github.com/pulibrary/pulfalight/issues/120 (I believe that these are EAC-CPF resources), but will also require that the user experience for faceting using subject headings is satisfactory.

**Comment by faithc** [comment]
Hi @jrgriffiniii - 

Just to clarify, the topic headings and subject headings are not EAC-CPF records; they are part of the controlaccess element in EADs.

**Comment by tpendragon** [comment]
Renaming this "Add Topic Facet", since we already have subjects as a facet.

**Comment by faithc** [comment]
Not sure we want display the local topics as a facet (yet) as staff need to review these. The idea was to maintain them as a separate, browsable page for now, mimicking the current site. https://findingaids.princeton.edu/topics

**Comment by tpendragon** [comment]
@faithc I think that's https://github.com/pulibrary/pulfalight/issues/120. Should the "Topics" part in "find related materials" (https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c5078) still link to other items that have that local topic?

**Comment by faithc** [comment]
Oh yes, sorry, you're right. And yes, please!

**Comment by tpendragon** [comment]
We've determined this is just making the "Find related materials" Topics link work, rather than having a facet for topic. Thus, closing this as a duplicate of #509
