### ISSUE TITLE
[PULFALight/production] Errno::EHOSTUNREACH: No route to host - connect(2) for 128.112.200.68:25

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#1361]
## Backtrace

    line 29 of [PROJECT_ROOT]/app/forms/ask_a_question_form.rb: submit
    line 23 of [PROJECT_ROOT]/app/controllers/contact_controller.rb: question

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/71321332)

## Sudden Priority Justification

These questions are the primary form of feedback from users to staff, and it will increase staff triage time if they start going through lsupport more regularly.

**Comment by eliotjordan** [comment]
See: https://github.com/pulibrary/pulfalight/issues/566

**Comment by eliotjordan** [comment]
Email sent to lsupport to add new VMs to Pony Express allow list.

**Comment by hackartisan** [comment]
Reopening to do data recovery. Christa said we can send the data to her and she'll enter it in libanswers.

**Comment by hackartisan** [comment]
I just emailed the data to Christa.
