### ISSUE TITLE
Update Aspace IPs for Jammy VMs

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#1362]
[PULFALight/production] ArchivesSpace::ConnectionError: API client login failed as user [aspace_pulfalight_prod], check username and password are correct

## Backtrace

    line 18 of [PROJECT_ROOT]/app/services/aspace/client.rb: initialize
    line 38 of [PROJECT_ROOT]/app/models/pulfalight/document/xml_export.rb: new
    line 38 of [PROJECT_ROOT]/app/models/pulfalight/document/xml_export.rb: client

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/90706913)

**Comment by hackartisan** [comment]
Blake confirmed these were done 1/9.
