### ISSUE TITLE
Provide access to institutional Princeton users (NetID-based authentication) to restricted digitized content

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#137]
Single sign-on (CAS) should provide users with the ability to access and view restricted digitized content in Figgy. As captured in the comment found on the Google Sheet (https://docs.google.com/spreadsheets/d/11fvifxmA9ZXJZsNycuIXEIkg43M6tlOaPyyGn6G89S8/edit?disco=AAAAEH48rds), this requested feature is for *remotely* accessing restricted content (the on-campus cases seem to already have another solution in place).

**Comment by jrgriffiniii** [comment]
Certain groups have certain rights to material, this would be:

* Certain departments
* Certain classes

SecureSend, which is currently in place for material which is not digitized, would not address cases where classes need to access online material. The Toni Morrison collection may not be completely open, but must still remain available. These cases might be broken into separate issues, as these classroom cases are not high priorities.

**Comment by jrgriffiniii** [comment]
Authorization here should, in part, be provided by Figgy.

**Comment by tpendragon** [comment]
Closed as duplicate (or rather going to be handled by) #389
