### ISSUE TITLE
Support single sign-on authentication (SSO) using the CAS for institutional Princeton users (those with NetIDs)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#138]
This is scoped just to support authentication, and blocks #137

**Comment by hackmastera** [comment]
Both figgy and DPUL have needed to be changed later to accommodate people with guest accounts on CAS (i.e. non-princeton email addresses). It would probably be a good idea to ensure that's not an issue from the outset, here.

**Comment by hackmastera** [comment]
This was done in #83; is something more needed here?

**Comment by jrgriffiniii** [comment]
I've just tested this in staging, it is indeed resolved.
