### ISSUE TITLE
Margaret K. McElderry Papers (COTSEN4) is not rendering properly in PULFALight

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#1380]
https://findingaids.princeton.edu/catalog/COTSEN4 

Only part of the resource record is rendering in pulfalight. 

Resource record: https://aspace.princeton.edu/staff/resources/4231#tree::resource_4231 (cotsen repo)

## Sudden Priority Justification

Without rendering in the display our colleagues can't know if their work is done, and researchers won't be able to access the objects.

**Comment by tpendragon** [comment]
One thing we noticed is that the component IDs don't include the EADID, maybe that's related?

**Comment by faithc** [comment]
I was wondering if part of the issue was data-related. I'm not sure why the ref IDs (component IDs) for this collection don't align with our convention for how these are typically applied/assigned.
