### ISSUE TITLE
changes in aspace getting stuck

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#1383]
The Aspace Operations group have noticed that there have a been a few instances where a change was made to a finding aid and it is saved and the changes do not appear. It seems to get "stuck" requiring staff to resave.
Is there a way to run a report or investigate this in an other way.

Example: [https://findingaids.princeton.edu/catalog/MC247_c2144?onlineToggle=false](url)
this note - Conditions Governing Access
Materials in this series will open for research in December, 2024. 
This was changed to add the month, previously it only had the year.  When it was not displaying in the finding aid we went back to Aspace and found it was indeed there and saved but we had to save it again for it to appear.

## Sudden Priority Justification

With inconsistent indexing,  folks are unable to be sure their work is getting in, and so they're repeatedly having to go back to check and it's creating some concern that some of their work is missing.

## Success Criteria

Schedule a full hard reindex every night. We'll probably have to install "Whenever", Figgy has examples on what that looks like.

**Comment by ccleeton** [comment]
@tpendragon Wondering if you might know if this is something that could be looked at as maintenance since it is impeding work. There is no way to know what is publishing correctly and what is not.

**Comment by tpendragon** [comment]
> @tpendragon Wondering if you might know if this is something that could be looked at as maintenance since it is impeding work. There is no way to know what is publishing correctly and what is not.

Seems reasonable. Can you give it a sudden priority justification in the issue description that roughly says that? Presumably this can wait a few weeks for us to spec out? If so we'll take a look at it then. Thanks for the ping!

**Comment by ccleeton** [comment]
This impedes our work because random notes or other changes fail to publish, but we would have to check every single one to know that it failed or was successful.

**Comment by tpendragon** [comment]
@ccleeton @faithc I'm guessing we're going to have a hard time figuring this out. Worst case scenario, how do you feel about just reindexing everything on some regular basis as a fix to this?

**Comment by faithc** [comment]
I think this is a question for Will Clements/ the ASpace Operations Group. Can you check in with him, @ccleeton ?

**Comment by ccleeton** [comment]
@tpendragon What would a reindex mean. It happens hourly right now correct? But if things aren't getting fixed by that how would a reindex help?

**Comment by tpendragon** [comment]
@ccleeton Every hour we reindex things that ArchivesSpace tells us has "changed" - if it's missing some, as it seems it is, then a full reindex would catch everything whether or not ASpace told us it changed.

**Comment by ccleeton** [comment]
Thank you for the clarification. How often would you possibly do a full one? Are they scheduled now for any sort of regularity?

**Comment by tpendragon** [comment]
We only do them right now when something's very broken. We could do it regularly, and whatever interval "regularly" is would mean these things that slip through the cracks are fixed then. Like - if you had to wait a week, is that too long? Three days? A day? (Daily full reindexing is probably too much)

**Comment by hackartisan** [comment]
I just did some messing around running some bits of the code in my terminal and didn't find anything amiss with the way the api request is written. the only thing I noticed that is weird is that this line never seems to actually show up in the logs, although the indexjob is definitely getting enqueued and run, and the Event is getting updated. https://github.com/pulibrary/pulfalight/blob/6b5341d3aa82a4cb0d2379f0582e747bf69995b0/app/services/aspace/indexer.rb#L41 

My one thought is that it might be worth trying an event per repository, rather than just one for all indexing. then we could update the appropriate event at the end of the job instead of after enqueuing.

**Comment by faithc** [comment]
I don't think we ever requested that this note display on the site so I'm not sure this is solely an indexing issue? The issue Charles noted does seem to be primarily related to indexing.

**Comment by ccleeton** [comment]
Thanks @faithc but it does appear here - https://findingaids.princeton.edu/catalog/MC001#find-more

**Comment by ccleeton** [comment]
Charles also added this in pulfalight channel which  might be related - Hi all, The boxes for the Dance Subject Files (TC107) are not able to be requested. This is in rare books repository. The location data was updated on Friday.

**Comment by faithc** [comment]
> Thanks @faithc but it does appear here - https://findingaids.princeton.edu/catalog/MC001#find-more

Ah, never mind then. Ignore my comment about that! Ha

**Comment by tpendragon** [comment]
@ccleeton Can you make sure these problems are fixed tomorrow and if so close this ticket again? Thank you!
