### ISSUE TITLE
Migrate Solr QA from lib-solr8-staging to lib-solr8-d-staging

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1384]
Sub-ticket of https://github.com/pulibrary/princeton_ansible/issues/4666

**Comment by hackartisan** [comment]
I'm going to try restoring a copy of the production solr backup instead of just indexing everything.

**Comment by hackartisan** [comment]
Okay that curl command didn't work; it errored with "

**Comment by hackartisan** [comment]
Okay that curl command didn't work; it errored with "Could not restore core" so I tried it again async and that worked. Here's how I did that:

```
curl "localhost:8983/solr/admin/collections?action=DELETE&name=pulfalight-qa" 
curl "localhost:8983/solr/admin/collections?action=RESTORE&name=pulfalight-production-20240321.bk&collection=pulfal
ight-qa&location=/mnt/solr_backup/solr8/production/20240321&async=1000"
```

Then you can run this to see how the restore is going: `curl "localhost:8983/solr/admin/collections?action=REQUESTSTATUS&requestid=1000"`

I walked away for a little bit but it really didn't take too long; much quicker than running the whole index would have been.
