### ISSUE TITLE
Spike on Upgrading to Vue 3

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#1396]
https://github.com/pulibrary/lux-styleguidist

## Instructions

https://github.com/pulibrary/lux-styleguidist/blob/main/UpgradeInstructions.md

Approvals change for reference: https://github.com/pulibrary/approvals/pull/984

Component migration instructions: https://github.com/pulibrary/lux-styleguidist?tab=readme-ov-file#copying-vue-2-components-from-lux

## Spike Instructions

Try spending up to a day to do this and see where blockers appear and find what we don't know and if we can reasonably continue it right now. Document blockers that appear in this ticket so we can discuss them. Expect code generated from this to be disposable.

## Step One

Read the upgrade instructions and follow them.

## Parts

- [ ] Upgrade lux to https://github.com/pulibrary/lux-styleguidist
- [ ] Upgrade local vue code (Shopping Cart)

**Comment by eliotjordan** [comment]
Upgrade Issues:

- [ ] There is no longer a "special-collections-footer"
- [ ] Pulfalight uses exported scss files that are not available in this version of lux. They [had to be copied over ](https://github.com/pulibrary/pulfalight/pull/1408/files#diff-6af4653619c0c29c6ec8c1e49c4073a33982d46600116dc64bfa36f58a0c4c98)to get Vite to compile.
- [ ] Some of the[ old scss variable names](https://github.com/pulibrary/pulfalight/pull/1408/files#diff-74a4e065a54f88567dc34f12d8949742eb9abecb47a63de16095de98dbc1a926L335) are no longer in lux. 
- [ ] There are some styling issues with alignment, icons, etc...
- [ ] Needs thorough testing on staging.
