### ISSUE TITLE
Determine whether or not ReCAP items can be requested using Aeon

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#140]
It would be ideal if users could select the logical unit (corresponding to the `<container>`) in order to request SCSB items using the information in the EAD. However, this might be blocked given what is needed from within Voyager in order to support requests for these items.

**Comment by jrgriffiniii** [comment]
This shouldn't be any different from items outside of ReCAP, as these items are definitely going to have a barcode. They can only currently be requested through Voyager *if* they don't have a barcode in the `<dsc2>`.

**Comment by tpendragon** [comment]
@jrgriffiniii Is this actionable? I'm very confused.

**Comment by jrgriffiniii** [comment]
I am sorry for the confusion with this @tpendragon - this has become deprecated given the abandonment of the legacy EAD structure (before the direct integration with ArchivesSpace).
