### ISSUE TITLE
Review the PULFALight Solr configuration for relevancy rankings

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#146]
Similar to pulibrary/pulfalight#145, but scoped to address the `conf/solrconfig.xml` file.

**Comment by jrgriffiniii** [comment]
We need to ensure that the Solr relevancy weights the components differently from the collections within search results.

**Comment by tpendragon** [comment]
@faithc @ccleeton @jrgriffiniii I'm reading this ticket as "Collections should show up before components in a search across all items." Is that true, even though collection-grouped search is the first result now? If not, can we close this? Blocking this pending feedback.

**Comment by sdellis** [comment]
@tpendragon Any collection title that contains the search terms should have prioritized ranking. Furthermore, components higher in the hierarchy should be considered more relevant than components lower in the hierarchy. 

For example, a search for "John Foster Dulles" (with or without quotes) should put the "John Foster Dulles Collection" and "John Foster Dulles Papers" at the top, but that's not currently the case:    

<img width="1444" alt="Screen Shot 2020-12-03 at 4 08 02 PM" src="https://user-images.githubusercontent.com/609368/101088853-48e63880-3582-11eb-9ac0-18c7bb182596.png">
