### ISSUE TITLE
Preferred citation 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#150]
This is currently autogenerated for the current site. We'd like to maintain this functionality.

**Comment by jrgriffiniii** [comment]
This should be rendered on each component within a collection.

**Comment by jrgriffiniii** [comment]
One must ensure that this is being indexed by Solr at the outset.

**Comment by jrgriffiniii** [comment]
If we know that a document belongs to a certain given collection, this can be provided in a given citation template (e. g. Public Policy)

**Comment by jrgriffiniii** [comment]
https://github.com/PrincetonUniversityLibrary/pulfa/blob/99405c337902cfed24737fd6fa83f7fd995b2a73/webapp/xsl/component2html.xsl#L2685 provides the functionality for building and displaying this citation.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pulfalight/compare/issues-19-jrgriffiniii-repos-config...issues-150-jrgriffiniii-pref-cite?expand=1 gets the citations generated in the Solr Document.
