### ISSUE TITLE
For search results, include scope content note (or abstract for collection-level results) along with breadcrumbs

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#158]
To provide sufficient context for users.

**Comment by tpendragon** [comment]
@faithc Do you mean in the "Grouped by Collection" search results? I think this is displaying in the results.

Grouped: https://findingaids-beta.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=evelyn+schuyler+schaeffer+family+papers%2C+1835-1969

Ungrouped: https://findingaids-beta.princeton.edu/catalog?q=evelyn+schuyler&search_field=all_fields

**Comment by faithc** [comment]
I think we were wondering if description (scopecontent) notes could display for components as well.
