### ISSUE TITLE
A show page should only have one viewer location

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pulfalight#161]
Currently it shows up below the main description and also in an "online content" tab. Where should it belong?

**Comment by jrgriffiniii** [comment]
I'm generally not in favor of tabbed interfaces, but I am not a designer. @sdellis is the better party to provide guidance from that standpoint.

**Comment by sdellis** [comment]
Digitized content should be front and center, and should not be hidden behind a tab. It's hard to comment without seeing this in action though. Can you share a screenshot or a link @hackmastera ?

**Comment by hackmastera** [comment]
@sdellis Once the functionality is in, here are some screenshots of the default appearance.

I assume we want to remove the "digital content" tab and increase the size of the remaining viewer. Likely also remove the "online content" heading.

Once the work for for #35 is merged I can post a link.

![Screen Shot 2020-03-18 at 10 03 37 AM](https://user-images.githubusercontent.com/845363/76969035-39de2e00-6900-11ea-9f1b-df300fb8ec14.png)
![Screen Shot 2020-03-18 at 10 03 47 AM](https://user-images.githubusercontent.com/845363/76969037-3a76c480-6900-11ea-8edc-adedf044d00c.png)

**Comment by hackmastera** [comment]
I've noticed that when you're viewing a container object, the "online content" tab is populated with child objects which provide online access. Something to be mindful of here.

**Comment by sdellis** [comment]
@hackmastera I'm not seeing child objects in your screenshots, but rather a redundancy with the current object's digitized content. Do you have examples of the digitized content for the child objects? (By `objects`, are we talking about components? Or are these objects with parent-child relationships in Figgy?)

A slightly related note: I also noticed essentially a "table of contents" that should probably be in the viewer for better UX/Usability, but is instead described in the EAD. Notice that his has children components here in PULFA:

https://findingaids.princeton.edu/collections/C0744.03/c0002

But not here in pulfalight:
https://pulfalight-staging.princeton.edu/catalog/C0744-03C0744-03_c0002

**Comment by hackmastera** [comment]
@sdellis The table of contents bug has been ticketed as #163 

The child object scenario happens when you look at the "online content" tab for a collection. Here's a screenshot:

![Screen Shot 2020-03-30 at 4 09 46 PM](https://user-images.githubusercontent.com/845363/77957112-fb9e2280-72a0-11ea-9b1d-bb479ad39022.png)

**Comment by jrgriffiniii** [comment]
Please see the proposed design in https://xd.adobe.com/view/b8b645f7-4321-42d0-50a7-bcfbe9fdcb1d-ce87/
