### ISSUE TITLE
Non-manifest digital object locations need to be indexed to a different field

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pulfalight#162]
Figgy manifests and arks for objects in pudl are getting indexed to the same place. The result is that the viewer code tries to load arks into figgy viewers, resulting in a blank viewer and no link to the pudl object. We'll need to index them into different fields and display them differently. Perhaps until we get the design sorted out the viewer could be on the page and the link could go in the digital objects tab.

example title with a pudl ark: "1000 mile tree in the narrows"

**Comment by hackmastera** [comment]
Alternately, should we index the "role" of the digital object location and check whether it is "https://iiif.io/api/presentation/2.1/" in the viewer / renderer logic?

**Comment by sdellis** [comment]
This issue breaks any JavaScript on the page because it's trying to load insecure content via a secure page.

**Comment by jrgriffiniii** [comment]
After discussing this on 03/23, we might need to confirm that the `@role` attribute of the `dao` element is acceptable in the EAD-parsing functionality for this work. We are looking to use `https://iiif.io/api/presentation/2.1/` as the value @regineheberlein

**Comment by regineheberlein** [comment]
EAD2002, which is what we are currently using, uses xlink:role. The value is not controlled.

(EAD3 breaks the role attribute out into arcrole and linkrole, FWIW, though my understanding is that that is under review. https://www.loc.gov/ead/EAD3taglib/EAD3.html)
