### ISSUE TITLE
How will we keep solr configs in sync with the ones in production on pul_solr?

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pulfalight#167]
Assuming we will need current solr configs to effectively do development work. Does orangelight deal with this?

**Comment by tpendragon** [comment]
Orangelight deals with it by downloading them from Github: https://github.com/pulibrary/orangelight/blob/14ec45d4c47a2bc5b88e60257effc157dd6dc820/lib/tasks/pulsearch.rake#L10
