### ISSUE TITLE
Remove number of components that display in grey box next to titles when browsing individual finding aid

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#175]
No one needs to know this. haha

**Comment by hackmastera** [comment]
A screenshot would help here.

**Comment by apferrar** [comment]
![Screen Shot 2020-03-24 at 10 46 45 AM](https://user-images.githubusercontent.com/32106332/77439059-f7639800-6dbc-11ea-8fe3-18213f0116b3.png)
@hackmastera

**Comment by jrgriffiniii** [comment]
This might be deprecated by #240

**Comment by jrgriffiniii** [comment]
This is currently in alignment with the [wireframes](https://xd.adobe.com/view/c3b49814-866d-449f-44e7-2479ff0cbb30-b585/screen/17ab6c92-2aa9-4457-8bc2-30f4562829a2), but is, at this point, a requirement for #240

**Comment by tpendragon** [comment]
New table of contents got rid of this.
