### ISSUE TITLE
Improve the visibility of notes

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#177]
Is there something that can be done on the design side that could make them more visible? While we're assigning this to MVP, Devteam may want to put this into the 1.x series to check in about later.

**Comment by hackmastera** [comment]
A screenshot would be helpful -- in particular, which notes are we talking about?

**Comment by apferrar** [comment]
@hackmastera 
![Screen Shot 2020-03-24 at 10 49 15 AM](https://user-images.githubusercontent.com/32106332/77439395-5d501f80-6dbd-11ea-9401-13c61c7ee1ee.png)
This goes back to the difficulty in navigating the side due to the design. It's odd to use the tabs but if we have to, then perhaps making the notes "pop" more would be good. Bolder? Darker text? Something we aren't thinking of? Of course, this may be solved after our conversations about overall design later on.

**Comment by faithc** [comment]
Just to add to what @apferrar contributed, we're referring to all notes associated with a component. We’re wondering if there’s a way to make them pop generally rather than having a bunch of plain text on the screen. Users don’t often read finding aid notes, so we’re thinking playing around with the design might be a way to encourage them to do so.

**Comment by faithc** [comment]
Aside from indexed terms, yes, that's primarily what we're referring to.

**Comment by tpendragon** [comment]
@faithc @ccleeton See https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c4623, is this still a concern?

**Comment by ccleeton** [comment]
The bold titles seem to help. @faithc is there more you were looking for?

**Comment by faithc** [comment]
Agreed, this is helpful. I think the addition of icons for digital content and access restrictions as noted in the wireframes will also serve as an improvement.

**Comment by tpendragon** [comment]
Thanks! We have separate tickets for those, so I'm going to close this.
