### ISSUE TITLE
Overarching design of the site structure

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#178]
The entire design of the site when in a collection is difficult to navigate. Is this something to do with the overall design? Is this something different? Can AF/FC/JG chat about this?

**Comment by jrgriffiniii** [comment]
Might it be possible to more closely follow the design for the collapsible finding aid view for PULFA 2.0?

Perhaps in the center of the page, there can be an expand/collapse interface component for viewing collection and component descriptions.

**Comment by jrgriffiniii** [comment]
Given the ongoing discussions for #173 , is this a duplicate?

**Comment by jrgriffiniii** [comment]
This has been deprecated by #238
