### ISSUE TITLE
Search History via your account

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#181]
What happens to your search results information in your account? How long is someones history saved? Can we control how long and in what manner this is maintained at Princeton? How responsibly is this information being managed? No matter the answer, we need a note on this page to let users know ALL of this information

**Comment by tpendragon** [comment]
It's kept forever (or until the user manually clears it). We can control anything. Is there an actionable thing we can do here to close this ticket?

@ccleeton @faithc Pinging you for feedback. Do we just remove the search history feature? Do we auto-clear it? Do we just need a note on the home page somewhere, if so where?

**Comment by ccleeton** [comment]
I feel like this is something to ask our users, can we have it keep forever for now and then make sure this is addressed in user testing?

**Comment by faithc** [comment]
+1. I like the idea of including an explanation so that users know they have control over how long their searches are saved. Perhaps we can add a note on the search history page.

**Comment by tpendragon** [comment]
There's a big "Clear" button on the search history page. Can we close this, and user test whether that's sufficient?

**Comment by ccleeton** [comment]
Works for me.
