### ISSUE TITLE
Solr may not really be working in ci

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pulfalight#183]
When I add logic to clean solr before each test all tests fail with a 404 from solr. I think this indicates that our ci setup is not complete.

**Comment by jrgriffiniii** [comment]
I can confirm that this was the case for me at some point, I will try to reproduce this.

**Comment by jrgriffiniii** [comment]
This does seem to still be a problem, as https://github.com/pulibrary/pulfalight/blob/master/.circleci/config.yml#L104 uses Solr for the CircleCI configuration, but does not seem to create a configset or core during test builds.

**Comment by jrgriffiniii** [comment]
This was resolved with https://github.com/pulibrary/pulfalight/commit/49676f679202f315a5ad63a815f7bd3fbb57aa4d
