### ISSUE TITLE
Review ARKs for PUDL content and ensure that these items are not already in Figgy

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#189]
If these items have already been migrated into Figgy, then perhaps the ARKs should be updated. In either event, the <dao> must be indexed with the Figgy Manifest URL.

**Comment by jrgriffiniii** [comment]
@regineheberlein shall attempt to produce a Google Sheet assessing the current values stored in the `<dao>` element. 6,300 elements is the approximate count.

**Comment by regineheberlein** [comment]
A Google sheet with current values, cid's, and collection id's can be found in the Pulfa 3.0/PULFAlight Google drive: [](https://drive.google.com/drive/u/1/folders/1HyJGlT1YBinFpKOdW7jw1po-HB66IQ6o)

**Comment by jrgriffiniii** [comment]
@jrgriffiniii needs to check on the status of ingesting Western Americana collection into Figgy.

**Comment by jrgriffiniii** [comment]
This serves as a good list on what should be prioritized for needs to be migrated into Figgy from the Finding Aids. Figgy does provide some reporting functionality, and @jrgriffiniii needs to check on how this might be consumed.

**Comment by jrgriffiniii** [comment]
Thank you very much for generating this @regineheberlein !
