### ISSUE TITLE
Clicking an "Online Content" button triggers an error

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#200]
This is currently afflicting the staging environment

**Comment by jrgriffiniii** [comment]
The following item should have the Universal Viewer embedded:

![image](https://user-images.githubusercontent.com/1443986/77951621-58490f80-7298-11ea-903b-306b89f32727.png)

**Comment by tpendragon** [comment]
Seems to have been resolved by the reindex.
