### ISSUE TITLE
Allow import of EAD hierarchy into structmap for components described at the item level

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#211]
This is an example where table of contents information is described in the EAD. A better user experience would be to allow the user to navigate around the object in the UV by generating a structmap with the hierarchy:

https://findingaids.princeton.edu/collections/C0776/c00491

**Comment by tpendragon** [comment]
I don't think those hand-edited comments about folios are reliable enough to associate with Figgy's labels, which are generated via the order manager. It'd be good for someone to go in Figgy and create that struct-map, but having the system do it automatically seems unlikely right? Unless I'm misunderstanding?

**Comment by sdellis** [comment]
You're correct that the unstructured, hand-edited comments won't be useful for any automatic generation of struct-maps. The best we could get would be a hierarchy that would need to be manually associated with page labels. 

I will close this as I agree that we won't be able to get a better experience without some manual effort.
