### ISSUE TITLE
Online content should only display in record of component with which that content is associated (components with daos)

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#223]
Online content currently displays alongside parent-level component records when that content is actually associated with child components. For instance, if you navigate to Series 1: Writings (https://pulfalight-staging.princeton.edu/catalog/C0187_c00001) in the F. Scott Fitzgerald Papers, there is online content that appears along with the series-level component record (not sure whether it's everything associated with that series? difficult to tell) as well as at the components with which the content is actually associated, such as https://pulfalight-staging.princeton.edu/catalog/C0187_c00019. This is unnecessary and confusing. Having an icon or some note indicating that a series or file group or parent component has online content is helpful; however, the content itself should not display at that level if the content is only associated with child components.

**Comment by faithc** [comment]
Also, I believe this was documented elsewhere, though I'm having trouble locating it; but the filenames for digital content are still visible.

**Comment by tpendragon** [comment]
@faithc Can you post a link to a record where that's happening?

**Comment by apferrar** [comment]
@tpendragon https://pulfalight-staging.princeton.edu/catalog/AC122_c1081

**Comment by tpendragon** [comment]
Not fixed. Example: https://pulfalight-staging.princeton.edu/catalog/MC221_c0094 should be the only record that renders the viewer. Instead all its parents render the viewer, for example https://pulfalight-staging.princeton.edu/catalog/MC221_c0092
