### ISSUE TITLE
Collection-level notes

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#224]
Collection-level notes (notes currently included in the Overview and Access tabs on pulfalight) should include all elements/notes that appear in archdesc from the opening did element to the first dsc combined tag. (See all tabs associated with finding aids on the current site: Summary, Description, Collection History, etc.) 

The "Rules or Conventions" note should not appear.

As indicated in #119, most of these notes should filter down to child component records unless those notes are supplanted at lower levels.

**Comment by faithc** [comment]
One collection-level note that shouldn't filter down to components within dsc[1] is acquisition information. See for example https://pulfalight-staging.princeton.edu/catalog/C0187_c00001.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pulfalight/tree/issues-224-jrgriffiniii-coll-notes ensures that the relevant EAD2 elements are indexed into Solr. I will proceed next by ensuring that these are rendered for collections and components on the appropriate pages.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pulfalight/commit/afeb56bda62eece1e47ce6536b50943277c2ece2 introduces a Presenter-based pattern for rendering the markup for the collection-level notes.

**Comment by jrgriffiniii** [comment]
There are forthcoming wireframes for the collection notes which should be used to implement the redesign. This should be reimplemented to render the notes with parity to the navigation interface for https://findingaids.princeton.edu/collections/MC221

**Comment by jrgriffiniii** [comment]
The criteria for which fields should be rendered needs to be determined with discussions held with @regineheberlein and @sdellis. Further, there should be codes which are resolved using the XML functions.

**Comment by jrgriffiniii** [comment]
Some of the DACS notes should *not* be propagated down to child/ancestor components.

**Comment by jrgriffiniii** [comment]
PULFA 2.0 should be referenced for this, particularly the XSL stylesheets.
