### ISSUE TITLE
Implement collection-level "Storage Note"

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#225]
There are several notes whose labels and text strings are currently auto-generated via the production stylesheet for the current site (which @sdellis and @regineheberlein know about), including physloc type="code," which displays as the Storage note on the current site (https://findingaids.princeton.edu/collections/C0187/#summary), and prefercite, which displays as Credit this material on pulfa 2.0: https://findingaids.princeton.edu/collections/C0187/#accessuse. 

The Physical Location note on pulfalight is currently displaying the attribute value: https://pulfalight-staging.princeton.edu/catalog/C0187, which in this case is hsvm.

**Comment by jrgriffiniii** [comment]
Display logic for this should be ported from the production XSL Stylesheet - this is something which is going to be ported into the Solr indexing.

**Comment by jrgriffiniii** [comment]
Please see about porting constants and functions from the XSL at https://github.com/PrincetonUniversityLibrary/pulfa/blob/a82c039a25d99b4f7d3d97e41545f70e1b723231/webapp/xsl/lib.xsl

**Comment by tpendragon** [comment]
We have credit this material done. We'd need to do the "Storage Note." Changing title of this issue.
