### ISSUE TITLE
Introduce a scrollspy for the Table of Contents interface within collections

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#226]
This should follow the design of https://www.cssscript.com/demo/animated-side-toc-nav-long-web-content

**Comment by jrgriffiniii** [comment]
There have been more recent conversations regarding the design of the ToC interface, and alternatives proposed for the scrollspy were referenced. @sdellis should we still consider this to be a feature request?

**Comment by jrgriffiniii** [comment]
This navigation feature is going to be removed entirely, as on the current site, there is a single-level depth hierarchy, and introducing a second hierarchical navigation interface would become confusing to users.

**Comment by jrgriffiniii** [comment]
This may still be implemented (or reconsidered), hence it should not be closed yet.

**Comment by tpendragon** [comment]
@eliotjordan and I recommend we close this, as it seems difficult and unnecessary for the MVP. Cool, @jrgriffiniii ?
