### ISSUE TITLE
The name of the repository doesn't show in the collection context at the top of the screen

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#230]
The hierarchy should state the specific repository name that the material is from, however it just states "Repository" and then the title of the collection (see below screenshot).

Related to [115](https://github.com/pulibrary/pulfalight/issues/115)

![Screen Shot 2020-04-06 at 11 50 09 AM](https://user-images.githubusercontent.com/32106332/78679292-087dd000-78b8-11ea-8e0e-1a393db1db4d.png)

**Comment by jrgriffiniii** [comment]
This is related there not being any repositories configured for PULFALight currently.

**Comment by jrgriffiniii** [comment]
This is advanced by #259, but currently only the title of the repository is rendered. When testing a single EAD from `selectors`:

![image](https://user-images.githubusercontent.com/1443986/80500048-aefb4500-893b-11ea-90c0-67e938d4317b.png)

![image](https://user-images.githubusercontent.com/1443986/80500310-0bf6fb00-893c-11ea-86fe-bb308fca64de.png)

Should more information be rendered than jus the repository title for this?

**Comment by tpendragon** [comment]
We are now matching the wireframes, which doesn't have a link to the repository. We can open another issue if we find we need it somewhere.
