### ISSUE TITLE
Rename "Online Access" Facet to "Access", put it at the top, and make it always open.

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#232]
Technically, there is only one other way to access the materials and that's in person, which there is no toggle option for. It seems unnecessary for researchers to have to click the menu to click the option to see the refreshed results. If the drop down menu needs to be there, then should the rest of the materials be labeled with "In the Library" access like in the Catalog? (see screenshots of staging, current, and catalog examples).
staging site: ![Screen Shot 2020-04-07 at 10 47 42 AM](https://user-images.githubusercontent.com/32106332/78684225-39f99a00-78be-11ea-89b9-6b0219c4e2df.png)
current site: ![Screen Shot 2020-04-07 at 10 52 38 AM](https://user-images.githubusercontent.com/32106332/78684230-3bc35d80-78be-11ea-94d4-e15e18769d1b.png)
catalog example: ![Screen Shot 2020-04-07 at 10 54 32 AM](https://user-images.githubusercontent.com/32106332/78684234-3cf48a80-78be-11ea-8361-0fed1e6d1517.png)

**Comment by ccleeton** [comment]
Asking to have the "In the Library" results not appear in the facet.
