### ISSUE TITLE
Can the search facets have an "i" icon next to them so people can hover over the "i" and see what the filters actually mean?

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#234]
Example of text: "Names are pulled from the subject headings applied to the collection during processing." "Places are pulled from the location subject headings applied to the collection during processing."

**Comment by faithc** [comment]
This is being discussed/has been articulated re: the site's redesign. Please associate this with the appropriate issue #.

**Comment by apferrar** [comment]
This should not be a ticket, but rather addressed in the "Help" section of the website. I've added this to the [PULFAlight Content Management spreadsheet ](https://docs.google.com/spreadsheets/d/1fz-iRuryipCwfWFRcJ_mHWMp10PDSlB1lKbYz4FPjhs/edit#gid=0)for future review.
