### ISSUE TITLE
Implement a Table of Contents interface for navigating collections and components

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#240]
The design from this is derived from https://github.com/pulibrary/pulfalight/issues/206. Please see the wireframes at https://xd.adobe.com/view/b8b645f7-4321-42d0-50a7-bcfbe9fdcb1d-ce87/grid

**Comment by jrgriffiniii** [comment]
The Vue components used to implement this should take JSON blobs for props. @sdellis successfully experimented with this on https://codepen.io/sdellis/pen/VwvvZPV

**Comment by tpendragon** [comment]
Er, wait, I meant JSON blobs for the table of contents. You want JSON for the content too?

**Comment by jrgriffiniii** [comment]
There is an almost-finished table of contents component in LUX: https://github.com/pulibrary/lux.

@tpendragon did raise some concerns regarding the performance of using this when compared with jQuery.

**Comment by jrgriffiniii** [comment]
We can create an artificial hierarchy for testing against sample data for larger EAD Collections. @regineheberlein was having difficulty with the extremely large collections with regards to exporting this from ArchivesSpace.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/lux/pull/321 tracks the Table of Contents Component used to navigate Collections and Components.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/lux/pull/321/files#diff-3c7984c3230a5a4748d626485c019dddR28 is where one provides a JSON tree-structure of the data as a property for the component.

**Comment by tpendragon** [comment]
Closed by #347
