### ISSUE TITLE
Identify and include a sample of EAD files which are representative of variation in finding aid XML structure

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#265]
Please see the EADs identified in https://docs.google.com/document/d/12e5AdrkabpZZeXoYfbkLCYlcM0eELyL-fevtgldoYwk/edit. This should be refined into a separate list in the form of documentation before the EADs are added as fixtures.

**Comment by regineheberlein** [comment]
We probably need to revisit this list? Some of these results are superseded by the recent dsc2 project.

**Comment by jrgriffiniii** [comment]
This relates to implementation, but perhaps also the EADs need not be tracked as fixtures in the repository, but a list of the files instead be used in combination with the Rake task `rake pulfa:checkout`. Maybe `pulfa:checkout:sample` or something similar.

**Comment by sdellis** [comment]
1. Flat collection (no hierarchy): WC064
2. Deep collection (extreme hierarchy): C0614
3. Both DSC2 and Traditional EAD with component containing multiple containers (please specify componentID): ?
4. Both DSC2 and Traditional EAD with components that share a container (please specify componentID): ?
5. Collection with mixed Access Restrict policies: ?
6. Largest Collection (in MB): ?
7. Collection with lots of Item-Level Description/Text: C0776/c00076
8. Small Collection that is Requestable at the collection level:  
9. ...

**Comment by regineheberlein** [comment]
I suggest that we work on completing the list of parameters in @sdellis 's list above; I can then pull fresh examples based on those.

**Comment by jrgriffiniii** [comment]
Given that this Google Document is a bit dated, there may need to be a separate discussion in which a new set of sample EADs are identified which fulfill the criteria identified previously by @sdellis in this thread.

**Comment by regineheberlein** [comment]
Starting a new list in light of ASpace development, which makes the dsc2 moot:

Flat collection (no hierarchy): WC064
Deep collection (extreme hierarchy): C0614
Lots of containers in one component: MC152
Collection with mixed Access Restrict policies: C0807
Largest Collection (in MB): MC001.04
Collection with lots of Item-Level Description/Text: C0776/c00076
Small Collection that is Requestable at the collection level: C0879
...

**Comment by regineheberlein** [comment]
Putting files here: svn://lib-svn.princeton.edu/libsvn/trunk/rbscXSL/pulfalight/eads4aspace

**Comment by regineheberlein** [comment]
successfully imported into ASpace:
- [ ] WC064
- [ ] C0614
- [ ] MC152
- [ ] C0807
- [ ] MC001.04
- [ ] C0776
- [ ] C0879

**Comment by tpendragon** [comment]
@regineheberlein Are you uploading these through a UI? I wonder if the 413 is an nginx error we can fix.

**Comment by regineheberlein** [comment]
Yes, I'm still working on my access to the backend, so the UI is the stopgap for now.

**Comment by regineheberlein** [comment]
@tpendragon @sdellis @escowles @kelynch @jrgriffiniii @kevinreiss 

I've started populating this directory with EADs roundtripped through ASpace dev; they should be fairly representative of the data we can expect to be working with. (Will keep adding to the directory as we resolve ASpace import issues)

svn://lib-svn.princeton.edu/libsvn/trunk/rbscXSL/pulfalight/aspace2pulfalight

**Comment by tpendragon** [comment]
@regineheberlein Great! I pinged @kayiwa and he's working on a setting that should fix the 413 errors.

**Comment by tpendragon** [comment]
@regineheberlein These EADs don't have any components. I assume that's not right?

**Comment by tpendragon** [comment]
Oh, it does, but it's not indexing into pulfalight. Sorry, my problem.

**Comment by regineheberlein** [comment]
@tpendragon C0879 is an example of a collection that's requestable at the collection level and has no dsc, so that one doesn't have components. The others should.

**Comment by tpendragon** [comment]
We have a bunch of these in `rake pulfalight:aspace:index_test_eads` now. Closing.
