### ISSUE TITLE
Evaluate and identify a cached, HTML-rendered approach to the rendering the "Table of Contents" interface for collections and components

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#276]
In previous discussions, it was proposed that this interface component should be implemented using Vue. After a discussion held on 06/26/20, it was determined that it would be much more performant to render the HTML and cache the tree structure, with default CSS classes being used to collapse each branch in the tree.  There would then be JavaScript used to select the branch and node which is the current focus, and expand this.

**Comment by jrgriffiniii** [comment]
The performance concerns affecting this need to be clarified.

**Comment by tpendragon** [comment]
Closed.
