### ISSUE TITLE
In-progress finding aids in ASpace should not be exported to PULFALight 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#281]
Not entirely sure yet what staff will need to do to indicate whether a finding aid is ready for export, but thinking it will likely involve the "publish" feature in ASpace.

**Comment by jrgriffiniii** [comment]
It will need to be determined how this can be implemented.

**Comment by regineheberlein** [comment]
When the "publish" checkbox on the collection level remains unchecked, the EAD exports with `<ead audience="internal">`. (The @audience is not present on exports where the "publish" box was checked.)

**Comment by tpendragon** [comment]
Leaving this open because I'm not convinced we're avoiding this right now.
