### ISSUE TITLE
Woodrow Wilson School is being rename to Princeton School of Public and International Affairs (SPIA)

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/pulfalight#283]
@faithc Should the content and collection name be changed now that the name of the School has changed?

![Screen Shot 2020-07-06 at 11 32 58 AM](https://user-images.githubusercontent.com/1599081/86611344-8c5d5c00-bf7c-11ea-9531-2b8b8a428a84.png)

**Comment by apferrar** [comment]
Hi there @carolyncole, good catch! Dan Linke and Sara Logue have some guidance on this so I encourage you to reach out to them about it, particularly Sara (slogue@princeton.edu). They're working on some larger changes.

**Comment by tpendragon** [comment]
This will be reflected in the EAD. Don't need a pulfalight ticket I don't think. I'm closing this, @apferrar can you reopen if I'm wrong?
