### ISSUE TITLE
Provide an option to print/download the finding aid in its entirety

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#289]
This is to replace the FOP-based generation of finding aid PDFs. This should be created as a print stylesheet that excludes any elements that are not directly part of the finding aid. 

We may want to add a button to allow this on the Collection Summary page or Collection header.

**Comment by sdellis** [comment]
Update: ArchivesSpace can generate PDFs out-of-the box. However, we need to evaluate how accessible they are. The best practice for "printing" use cases is to use a Print Stylesheet.

We also decided to have a "Print this Finding Aid" button on every page of the collection.

**Comment by tpendragon** [comment]
See https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/screen/17ab6c92-2aa9-4457-8bc2-30f4562829a2 for the button.
