### ISSUE TITLE
Document the exporting of EADs from an ArchivesSpace installation

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#290]
As ArchivesSpace is to be a part of the supported finding aid publishing workflow, then I would please contend that there be documentation outlining how one exports EAD XML from an ArchivesSpace resource.

**Comment by hackmastera** [comment]
And how to index them in a development environment. Replace instructions about svn: https://github.com/pulibrary/pulfalight#indexing-documents-into-pulfalight
