### ISSUE TITLE
Observe and document the user behavior for Aeon requests

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#303]
We should prioritize observing the user interaction with the Aeon request workflow.

**Comment by jrgriffiniii** [comment]
I can advance this by scheduling a meeting with the product owners.

**Comment by tpendragon** [comment]
Met with product owners. Once a request goes into Aeon, fulfillment staff never leave Aeon. They print a call slip which is used from that point forward to find the material. We think we've got this nailed down, just have to have the appropriate departments test the features when we have more data in.
