### ISSUE TITLE
Spin-out indexing into a separate application?

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#307]
This is a proposal is to spin-out indexing/document transformation into a separate application, like we do for Orangelight (marc_liberation) and GeoBlacklight (Figgy). 

- Using Solr JSON documents as fixtures instead of transforming (and generating!) XML EAD document fixtures on the fly would greatly improve developer ergonomics.
- Separating concerns will help us if we want to switch from using Traject.

Alternatively, we could keep the indexing functionality where it is, but use Solr JSON documents as fixtures for the non-indexing tests.

What are cons of this approach?

**Comment by tpendragon** [comment]
Do you have any concerns with there being a disconnect between how a document is converted and how the frontend responds to a certain Solr document? I feel like I've had that happen in some of our other apps before. The only other thing which might be an issue is we wouldn't be able to copy over any specs from Arclight master anymore. Maybe that's okay?

**Comment by eliotjordan** [comment]
@tpendragon To me, the disconnect between the converted document and frontend behavior with a solr document is the primary argument against doing this. I'm not as concerned about being able to copy/paste specs from Arclight. We don't typically do that in our other blacklight applications.

**Comment by tpendragon** [comment]
I don't think we need this anymore, or another application to support.
