### ISSUE TITLE
Ensure that year-titled <c level="file"> elements under a component are rendered as individual records

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#308]
These `file` components should be rendered as nodes under parent components within the Table of Contents interface, as one can observe on https://xd.adobe.com/view/c3b49814-866d-449f-44e7-2479ff0cbb30-b585/screen/8511ff6c-e5b8-4a41-9926-9c90325d315a

![image](https://user-images.githubusercontent.com/1443986/87704431-626d1c00-c76a-11ea-8b0f-f54b96adbbcb.png)

**Comment by tpendragon** [comment]
We're going to ingest MC016 so we can look at this. The real request seems to be that you can request child components from the parent component, but we may not need to do this with the request cart.
