### ISSUE TITLE
ASpace only exports invalid CPF records with minimal fields

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#309]
Included in the export are the display name and bioghist notes. Not included are ark / recordId, exist dates, use dates, authority file, sources, maintenance history. 

This has implications for our discovery services on pulfalight, since we've used the Names part of the website as an access point to our resources.

If we want to keep that service, we may want to create CPF records the way we have been (from the EADs) rather than export them from ASpace, at least for the time being.

From Brian Harrington:
```
Until the agent record improvements in ANW-429 are merged in, the necessary database fields to hold all of the information in your CPF records don't exist in ASpace
```

Earlier from Brian:
```
The EAC-CPF functionality is currently a bit of a mess.  Work is underway on getting it fixed, but unfortunately didn't make it into the upcoming 2.8 release.  There's a test server with the work in progress that you can try things on at http://aspace-anw-429.lyrtech.org/staff/ (username: admin, pass: admin).  You can also follow the ticket at: https://archivesspace.atlassian.net/browse/ANW-429
```
NB we're on 2.7; 2.8 is the upcoming release.

**Comment by tpendragon** [comment]
@regineheberlein @faithc @ccleeton We're confused about next steps here. Can we wait to implement the name search feature until we can get the EAC-CPF data into ArchivesSpace? If not, we need to figure out a strategy together to make this work that hopefully doesn't include simultaneously maintaining the SVN EADs.

**Comment by regineheberlein** [comment]
@Trey Yes! We found a workaround to the import barrier and are getting the names (and properties!) in with the next iteration. Hopefully then we can get them out via the API. Lyrasis is promising to fix the CPF export in an upcoming release.
