### ISSUE TITLE
Generate AbIDs

### ISSUE THREAD

**Issue by escowles** [pulibrary/pulfalight#311]
When we have migrated to ASpace, we will need a new tool for generating AbIDs (numerically-sequential storage locations based on the size of the containers being shelved). We currently have an Access DB that does this, which keeps track of the number of containers shelved internally, and updates the container inventory in the EADs. PDF labels are also generated for boxes and folders by this process.

This is probably not going to be implemented in Pulfalight, but I'm creating a ticket for it here to keep track of this requirement. The new AbID generator may be able to use the ASpace API to keep track of how many containers of various types have been shelved, or may need to track that internally like the current app.

Here's a wireframe of the functionality: https://docs.google.com/drawings/d/1xCF03sneYEAl5HskbyBKy29_qNYqaoWXv5vXy1uZzL4/edit

## Technical Implementation

This is a piece of bulk edit software for ASpace's top containers. The software can live anywhere - probably in Pulfalight is most maintainable, but it means we need to have a concept of "staff" in Pulfalight.

The goal for the software is to: Find a particular subset of containers in a given collection, give them a location code, give them a container profile, override their identifier, and give them a barcode generated by sequentially adding to a "start" barcode.

#### Data we use to find the resources to modify.
* Repository
* Resource ID
* Existing Top Container Type (Pull these from ASpace, will be things like Box, Volume, etc)
* Starting Top Container Identifier
* Ending Top Container Identifier

#### Data we modify.

* Starting barcode (User scans this from a roll of barcodes, so prevent enter from submitting the form.)
* Location Code to assign
* Container Profile to assign

### After Form Submission

What we do:

* Find the top containers which match the query parameters. (You can get all top containers for a collection via `/repositories/:repoid/resources/:resourceid/top_containers`)
* Validate there are no duplicates (e.g, there aren't two "box 6")
* Sort by indicator ASC
* For each top container, add the next barcode. (NOT %9 but Luhn algorithm: https://honeywellsps.my.salesforce.com/sfc/p/#00000000SK3U/a/A00000000GgQ/5jrhUOO.jAi2F8erRZ9wr3yvjnLIR5dGAv5J0E0.mxE
Rough implementation in this gist: https://gist.github.com/jrgriffiniii/39559ae65f80d37759c2e335fcc22564)
  * https://www.rubydoc.info/gems/barcode1dtools/1.0.2.0/Barcode1DTools/Codabar
  * https://www.rubydoc.org/github/toretore/barby/Barby/Codabar
  * https://github.com/mdchaney/Barcode1DTools
* Give each top container the given container profile.
* Give each top container the given location code.

## Open Questions

1. Do we need some sort of validation display, to say "You're about to override X containers with this data"?
2. Should we be validating that there are the expected number of boxes in ASpace for the given range? E.g. if I say override boxes 4-8, and there's no Box 7, should it fail (or give some sort of warning)?
3. What happens if they mess up? The form will no longer work, as the indicators will be overridden.
    * Per @regineheberlein, maybe we should save the old identifier as an unpublished note on the top container?

**Comment by Will-Clements** [comment]
Hi there, I wanted to add some info to the description above and request some additional features. In addition to generating the AbID and barcodes, we would need the tool to go into ASpace and plug them in to the Top Container records: replacing traditional box numbers that were entered during processing and adding the barcodes.

Additionally I have been struggling with the fact that you can't add container profiles or locations to Top Containers created in ASpace using Rapid Data Entry or the spreadsheet importer. We would likely need to add both of these to every Top Container record, and so I'm wondering if this is something we could add to the tool, since the data is going to the same place in ASpace (Top Container records). 

I could see this working in the tool because a user would be selecting a box size (which is what AbIDs are based on), and additionally they could add the location as well. there could potentially be more than one location added per collection. I'm attaching a spreadsheet of container profiles and locations if that helps to think this through. 
[profiles-locations-repos.xlsx](https://github.com/pulibrary/pulfalight/files/5318259/profiles-locations-repos.xlsx)

**Comment by regineheberlein** [comment]
+1 on questions 1, 2, imo.

Re: question #3: 
The container indicator gets overwritten, so that seems pretty final unless we store the old indicator in a note field. The only place I can see atm is in container_locations[note]. It would be a bit of a hack, but it would give us a bit of a failsafe.

The indicator aside, the workflow for re-doing a container would be something like "starting at the first barcode I had scanned, going for n sequential barcodes, do something." The 'something' can be change the location or the profile, or even the barcode I guess.

**Comment by regineheberlein** [comment]
One note about how ASpace validates barcodes--it mostly doesn't (any characters, any length are allowed), with one exception: it doesn't allow duplicate barcodes (they will return an http "bad request").

**Comment by tpendragon** [comment]
Ah, I didn't think about ASpace errors. If ASpace errors in the middle, should I be able to hit the button again?

**Comment by regineheberlein** [comment]
@faithc provided me with the current AbID documentation for processors (https://docs.google.com/document/d/17nML-1ZRG_Kd-rKi6F2OXpIWEYem5sedXI9okPfe3Ao/edit), which has the following note about undoing errors. That workflow works because the Access DB stores all records it created.

```HOW TO DELETE RECORDS:
*If you realize belatedly that you made a mistake after you’ve clicked “Output All” but before you’ve closed the UserAll 
form, you can return to the UserAll form and click “Undo today’s output” at the top of the form. The original box numbers, 
which display in italics following export, will become un-italicized after you’ve undone the output. In order to actually delete 
any items, you still need to click “Delete” next to individual rows to delete single items. When you have corrected your 
mistakes, you can output again by clicking “Output All.”
*If you realize belatedly that you made a mistake after you’ve closed out of the database entirely, go to the Start form and 
click “Recent Activity.” When prompted to “Enter the number of days to review,” enter a number below 1000 depending on 
how long ago you created the records you want to delete. Once the UserAllRecentActivity form opens, click “Undo output.” 
You should see a list of all items you have created within that time period. Then click the “Delete” button next to each 
individual record you want to delete. When you are finished, click “Output All” to re-do the output of any records in the list 
you do want to keep.
NOTE ABOUT ERRORS: Minor errors in records, i.e. those not relating to barcodes or their associated AbIDs, such as wrong 
collection codes or traditional box numbers, can be corrected in the XML export file rather than deleting and recreating 
records in the database as the database is not meant to serve as the master record for the data it creates.
```

**Comment by regineheberlein** [comment]
> Ah, I didn't think about ASpace errors. If ASpace errors in the middle, should I be able to hit the button again?

Yes, I would think so

**Comment by regineheberlein** [comment]
PROBLEM: Don Thornbury just alerted me to the fact that the AbID db is also used by catalogers / non-archivists, for data that does not live in ASpace. (They use MacroExpress to add it to Voyager). That means the current implementation plan doesn't work, since it relies on ASpace to know what the next available number in the sequence is. I'm adding a note to the ticket and I hope Don can chime in to fill in the blanks.

**Comment by regineheberlein** [comment]
From Kevin on Slack:
`I think we could support it in the context of the libjobs if we agree to take on the responsibility of persisting the IDs.`

**Comment by regineheberlein** [comment]
We probably wouldn't have to persist all AbID's--just the last one for each super-location (Firestone, Mudd) + profile. And at the end of each bulk update operation, we'd have to overwrite that value for next time.

**Comment by doncat** [comment]
I'm available to discuss details of the current AbID database and the functions it supports for MARC records.  Also, there's a little more to it than simply generating new AbIDs.

**Comment by regineheberlein** [comment]
@doncat If the "more" is not reflected in the above, could you elaborate?

**Comment by doncat** [comment]
Barcodes generated without AbID, for ReCAP "EAD" type.  AbID replacement is only for onsite storage.
Also, those search options on the Start form were created per user request.  It has been useful (on rare occasions, I think) to see what was assigned to an item in case of mistaken changes in EAD or MARC.
Also note the "None" metadata option for odd cases, mostly Cotsen boxes.

**Comment by regineheberlein** [comment]
Thanks @doncat! So if I understand correctly, the "metadata: none" option just means the container information will not be merged into a Voyager or ASpace record, right? So it's a "labels only" workflow?

If so, in addition to the above, we need to allow for the following:

* allow barcode to be blank
* persist ALL AbID's for future reference

**Comment by regineheberlein** [comment]
workflows to accommodate: 
*ASpace, as above
*Voyager: output XML file to be picked up by DT's macro for further processing
*none:  output XML file to be picked up by DT's macro for further processing

NB: Tentatively, we think the ASpace workflow doesn't need to output labels (ASpace includes a labels functionality--it's currently returning a 404, but we're following up with Lyrasis). The Voyager / no metadata workflows do, but that can hopefully be picked up by the existing tool for now (until we change over to Alma).

**Comment by regineheberlein** [comment]
This is a basic implementation of the Luhn algorithm for computing the checksum (14th digit):
def compute_barcode_checksum(barcode_without_checksum)
  is_odd = true
  sum_total = 0
  while barcode_without_checksum > 0 do
    last_digit = barcode_without_checksum % 10
    #odd digits get multiplied by 2 and summed
    #if product is => 10, subtract 9
    if is_odd
    then
      do_odd = last_digit * 2
      sum_total =
        if do_odd < 10
        then sum_total + do_odd
        else sum_total + (do_odd - 9)
        end
    # if even, add to sum
    else sum_total = sum_total + last_digit
    end
    is_odd = not(is_odd)
    # integer divide over 10 to move on to the next digit
    barcode_without_checksum = barcode_without_checksum / 10
  end
  remainder = sum_total % 10
  if remainder == 0
  then return remainder
  else return 10 - remainder
  end
end

**Comment by escowles** [comment]
@regineheberlein Is this the same algorithm as https://github.com/pulibrary/figgy/blob/main/app/values/barcode.rb ?

**Comment by regineheberlein** [comment]
@escowles That looks very much like it's the same checksum algorithm! (https://honeywellsps.my.salesforce.com/sfc/p/#00000000SK3U/a/A00000000GgQ/5jrhUOO.jAi2F8erRZ9wr3yvjnLIR5dGAv5J0E0.mxE)

**Comment by jrgriffiniii** [comment]
This has been deprecated in favor of https://github.com/pulibrary/abid
