### ISSUE TITLE
Redirect old component ID URLs ASpace component ID URLs

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pulfalight#317]
Using data loaded from PULFA EAD into ASpace, redirect URLs from legacy PULFA component IDs to new ASpace ones.

E.g. `https://pulfalight-staging.princeton.edu/catalog/MC085_c01078` should redirect to `https://pulfalight-staging.princeton.edu/catalog/aspace_MC085_c01078`

See [this thread on Basecamp](https://3.basecamp.com/3410311/buckets/17339997/messages/2859895617) for how legacy component IDs will be available in the ASpace EAD.

**Comment by hackartisan** [comment]
duplicate of #526

**Comment by tpendragon** [comment]
We're stripping `aspace_` now, so this is closed.
