### ISSUE TITLE
Implement the design for the Homepage View defined by the Summer 2020 wireframes

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#329]
This should follow the design proposed for the homepage with https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/

**Comment by jrgriffiniii** [comment]
"Browse All Online" content link in the design is *required* to be implemented for the MVP, however any dynamically-updated content in the "Featured Online Content" and "Blog" sections can be deprioritized for the MVP.

**Comment by tpendragon** [comment]
Where are we pulling hours data from? I think I'm gonna break that ticket out and just frame it out to close this ticket, but it'd be good to know.
