### ISSUE TITLE
Ensuring that the ArchivesSpace location entries are inserted into the EAD from location records

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#332]
As discussed on 08/11/20, @regineheberlein clarified that there is a need to ensure that the location records are inserted into the EAD finding aids exported from the system.

**Comment by regineheberlein** [comment]
...or at least merging them back into the EADs post-export is one way to go about it?

**Comment by tpendragon** [comment]
Might be done, it'll come out during our implementation of the requesting. Closing this. See https://github.com/pulibrary/princeton_ead_exporter
