### ISSUE TITLE
Item breadcrumbs not displaying correctly

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#345]
Breadcrumbs for EADS imported from Archive Space are not displaying correctly.

<img width="683" alt="Screen Shot 2020-08-26 at 11 58 49 AM" src="https://user-images.githubusercontent.com/784196/91334068-0eefe400-e794-11ea-86db-e42395e9b809.png">

**Comment by eliotjordan** [comment]
This is an indexing issue

The `parent_unittitles_ssm` method only appends the top-level (collection) title. `parents` in this method never have components:
https://github.com/pulibrary/pulfalight/blob/bc2427cdfb8b2da77561e3a4eeec77ea5509b395/lib/pulfalight/traject/ead2_component_config.rb#L109

The logic in this method and `parent_levels_ssm` does not work.

**Comment by tpendragon** [comment]
When I was digging into this I wasn't sure how to fix it with the new nested children logic. Might have to adjust how the breadcrumbs are generated?
