### ISSUE TITLE
Integrate the Universal Viewer

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#35]
We will also need to be able to link to the manifests generated from Figgy. This is likely going to consist of just porting the existing viewer integration directly from Figgy itself.

**Comment by hackmastera** [comment]
Here is the dpul commit that integrated the figgy viewer: https://github.com/pulibrary/pomegranate/commit/b085769089d8eef3032f1e0af0f382641cf40041

**Comment by hackmastera** [comment]
Here is the arclight custom viewer documentation
