### ISSUE TITLE
Update the <unittitle> derived for the header titles and subtitles for Collection and Component show views

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#352]
This requires that additional fields be added into the Traject configuration (at least until presentation functionality is shifted elsewhere in the application).

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/pulfalight/pull/348 advanced this with the removal of the date subtitle.

**Comment by jrgriffiniii** [comment]
This should be deprioritized until we can work with the final ASpace EADs.

**Comment by tpendragon** [comment]
We need examples to make this ticket actionable.

**Comment by tpendragon** [comment]
We're assuming we're doing the right thing now. We'll open a new ticket if an issue is reported.
