### ISSUE TITLE
Add component-level access icons.

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#366]
See wireframe: https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/screen/8511ff6c-e5b8-4a41-9926-9c90325d315a

Access values should be indexed already, but some mapping may have to be done. Research will have to happen as part of this ticket.

**Comment by tpendragon** [comment]
Blocked similar to #285
