### ISSUE TITLE
Collection-level access privileges can be misleading (these lie within the EADs)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#367]
There are cases where the access privileges in the collection-level notes which are, at times, misleading when it comes to providing or denying access to entire collection. There are cases where only some components within a collection are restricted, and this may need to be adjusted in the EAD itself.

**Comment by faithc** [comment]
@regineheberlein is working to try to correct this issue on the data side so that additional pulfalight functionality isn't needed. Will create a new issue is this approach isn't successful.

**Comment by regineheberlein** [comment]
@faith this requires input from you on https://github.com/PrincetonUniversityLibrary/pulfa/issues/1231

**Comment by faith** [comment]
> @faith this requires input from you on https://github.com/PrincetonUniversityLibrary/pulfa/issues/1231

Wrong person fam 😂, it wasn't me, it was @faithc

**Comment by regineheberlein** [comment]
So sorry @faithc
