### ISSUE TITLE
Integrate a static "Help" section into the site

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#368]
There should be created a static Help page which users should be able to readily access, and this content should be maintained within the PULFALight application itself. Please note that the users should be able to regularly update the content.

**Comment by jrgriffiniii** [comment]
Should this feature embedded content (e. g. video) such as one finds on a Wordpress, Drupal, or other CMS platform? Will this be required?

**Comment by jrgriffiniii** [comment]
For the MVP, this should be only a static page, but perhaps this could also be synchronized from a CMS once https://github.com/pulibrary/pulfalight/issues/253 is completed?

**Comment by apferrar** [comment]
Also consider the content on the [Pulfalight Content Management (by Feature) spreadsheet](https://docs.google.com/spreadsheets/d/1fz-iRuryipCwfWFRcJ_mHWMp10PDSlB1lKbYz4FPjhs/edit#gid=0)

**Comment by hackmastera** [comment]
For the initial static page, we will need the content. Where can we get this?

**Comment by faithc** [comment]
@apferrar can speak more to this in terms of instructions for users; however, one piece of content that's ready to go is this statement: https://library.princeton.edu/special-collections/statement-language-archival-description.

**Comment by apferrar** [comment]
@hackmastera I've drafted some text for each section and [it's in the drive](https://docs.google.com/document/d/13i_44Py4LESJyKrcwA9YvjSSeIIE3K9LykD-BTJ0sRw/edit). I'm not sure how much we'll actually need, but I was basing it off of what existed on the old [Special Collections Research Account blog](https://blogs.princeton.edu/research-account/).
