### ISSUE TITLE
Design and implement the Request Cart feature set for supporting the selection of multiple containers for Aeon requests

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#37]
Current Implementation WIP: https://github.com/pulibrary/pulfalight/compare/jrgriffiniii-request-cart-spike-rebase2

Please see the following screenshots captured for the current behavior of [PULFA 2.0](https://findingaids.princeton.edu):

![image](https://user-images.githubusercontent.com/1443986/67708069-f0616680-f991-11e9-83ae-5b8e42681094.png)

![image](https://user-images.githubusercontent.com/1443986/67708120-02dba000-f992-11e9-87e3-bbf1477ec979.png)

**Comment by jrgriffiniii** [comment]
There may be a Vue component which could be integrated in order to facilitate with the implementation of this feature.

**Comment by jrgriffiniii** [comment]
Currently, there are duplicate requests created for Aeon when users submit request multiple items linked to the same user account. As a consequence, staff are required to manually delete these duplicated requests.

**Comment by jrgriffiniii** [comment]
It is desired, however, to track which boxes and folders are requested in order to identify precisely what is being most frequently requested by users.

**Comment by jrgriffiniii** [comment]
Also, please note that individual requests for related boxes or folders are *not* linked within the Aeon request system.

**Comment by jrgriffiniii** [comment]
Please also see #118

**Comment by jrgriffiniii** [comment]
Vue integration had no objections, but this feature set could be significantly large.

Perhaps linked to this might be a separate issue for exploring the Aeon API? Ideally, in the future, users should be able to submit requests with cookies would permit users to submit requests to Aeon between collections (without forcing reauthentication).

**Comment by jrgriffiniii** [comment]
The best approach to this would be to create wireframes and mockups in order to initiate this process.

**Comment by jrgriffiniii** [comment]
We also want to ensure that this is tracked closely to the MVP release, as we want integration to be addressed before the MVP is deployed.

**Comment by sdellis** [comment]
Jotting down a few thoughts here... 

According to [the Vue.JS cookbook](https://vuejs.org/v2/cookbook/client-side-storage.html), it seems like using client-side storage (specifically, LocalStorage) will be the best way to track requested items over the course of a session.

**Comment by jrgriffiniii** [comment]
Should users leave items in their request cart, without having been submitted for an Aeon request, these can and should persist within the local storage for the browser.

Users would need to use the same browser for this set of requests, and we can set a time-to-live.

**Comment by sdellis** [comment]
We also would like to prevent people from requesting multiple folders from the same box separately. Currently if people request folders piecemeal, they do not get collapsed into a single request and inundate public services with unnecessary requests.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/lux/compare/request-cart tracks prototyping for a Vue Component developed in LUX.

**Comment by jrgriffiniii** [comment]
I need to rebase the work on https://github.com/pulibrary/pulfalight/tree/jrgriffiniii-request-cart-spike-rebase, however, this is completed:

![image](https://user-images.githubusercontent.com/1443986/91492065-f7dbef80-e882-11ea-951c-9cab11a98eed.png)
