### ISSUE TITLE
Make Homepage Hours pull from libcal

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#378]

**Comment by kevinreiss** [comment]
JSON for Today's hours for each location:

For Special Collections: https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=14275&format=json&systemTime=1
For Mudd: https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=12315&format=json&systemTime=1
All locations: https://libcal.princeton.edu/api_hours_today.php?iid=771&lid=0&format=json&systemTime=1

There is also a more fully featured REST-style API that requires the passing of an access token. Let me know if that route seems preferable over. 

https://ask.springshare.com/libcal/faq/1407

**Comment by tpendragon** [comment]
"More Hours" should go to https://libcal.princeton.edu/hours

**Comment by ccleeton** [comment]
The Firestone RR hours are not displaying correctly right now. Can this be fixed? It seems to have been like this for a few weeks or more.

**Comment by ccleeton** [comment]
New ticket for new issue - https://github.com/pulibrary/pulfalight/issues/1073
