### ISSUE TITLE
Add a beta banner

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#386]
We'll be running both systems alongside one another potentially.

**Comment by sdellis** [comment]
@tpendragon We will need to periodically put banners with announcements on the site. Can this "beta banner" be generalized into an "announcement banner"? 

Is the idea that the content markup be done manually and display will be handled via css?

**Comment by tpendragon** [comment]
I'm open to ideas on implementation. Generalizing is fine. For now the use case is just when we first open up prod (which is soon) there's a banner at the top saying it's beta software.

**Comment by eliotjordan** [comment]
Closed by #430
