### ISSUE TITLE
Apply the PUL branding

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#4]
This involves applying the PUL branding using a combination of SCSS and JavaScript from other existing applications.  https://github.com/pulibrary/DSS/pull/90 was given as an example to follow (and introduces the possibility of including LUX in this process).

Some progress has been made on the branches https://github.com/pulibrary/pulfa3-light/tree/pul-branding-lux and https://github.com/pulibrary/pulfa3-light/tree/pul-branding.  `pul-branding` may no longer be needed given the advantages introduced by using Webpack to handle JavaScript assets.

**Comment by jrgriffiniii** [comment]
Should this be closed before we request a review from Enterprise and User Services?

**Comment by sdellis** [comment]
Blocked by #186
