### ISSUE TITLE
Searching will not work for some collection codes

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#421]
The regex we use won't match collection codes with decimal values.
https://github.com/pulibrary/pulfalight/blob/master/app/controllers/catalog_controller.rb#L46

Example:
https://findingaids.princeton.edu/collections/AC105.01

Will probably need to wait until we have fixtures with ids in this format.

**Comment by tpendragon** [comment]
@regineheberlein Is there a small decimal point EAD?

**Comment by regineheberlein** [comment]
Sorry @tpendragon, I'm not understanding your question. We have a few dozen EAD files with decimal points in the collection code / file name, including those with two decimal points (e.g. MC001.02.01 etc.)

**Comment by tpendragon** [comment]
@regineheberlein We need to index one, but all the ones I saw are too big and ASpace's QA is crashing when I grab them. Is there one that isn't very big but has a decimal?

**Comment by regineheberlein** [comment]
Ah, got it. Try MC001.02.06 or MC001.02.06--both around 500MB, and they have an inventory (i.e. not collection-level only).
