### ISSUE TITLE
we need a way to get structured access restrictions out of ASpace 

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#429]
From archivesspace-development created by [regineheberlein](https://github.com/regineheberlein): pulibrary/archivesspace-development#44  

From pulfalight created by [regineheberlein](https://github.com/regineheberlein): pulibrary/pulfalight#370  

Summarizing a conversation with @Will-Clements:

ASpace has structured and actionable fields for access restrictions that archivists want to make use of going forward. These don't export as part of the EAD export functionality. Only notes (=strings) do.

ASpace treats the structured access restrictions as properties of the top container. We need a way to get those out so they can be used to automate aspects of the requesting process.

**Comment by tpendragon** [comment]
@regineheberlein If we're going to move this forward I think we need some more info. What's the feature here? Can you provide some screenshots of the data in ASpace and where it should appear in Pulfalight?
