### ISSUE TITLE
Request Cart should scale for Mobile

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#440]
Right now it's too small to use, and the button doesn't appear.

**Comment by jrgriffiniii** [comment]
While working to improve the display of the request cart for mobile devices, I've discovered a bug in which the sliding pane will not reopen once triggered at a smaller screen resolution.

**Comment by jrgriffiniii** [comment]
I have introduced the following on https://github.com/pulibrary/pulfalight/tree/issues-440-jrgriffiniii-req-cart-mobile:

![image](https://user-images.githubusercontent.com/1443986/99122335-22a92a80-25cc-11eb-957c-c19aa7499d64.png)
![image](https://user-images.githubusercontent.com/1443986/99122377-36ed2780-25cc-11eb-8c71-9f0b5ef615da.png)
![image](https://user-images.githubusercontent.com/1443986/99122438-54ba8c80-25cc-11eb-9bc8-99b79dfe1cb7.png)
![image](https://user-images.githubusercontent.com/1443986/99122502-6e5bd400-25cc-11eb-8b33-3b343a565d61.png)
![image](https://user-images.githubusercontent.com/1443986/99122548-86cbee80-25cc-11eb-8353-62533455a468.png)
![image](https://user-images.githubusercontent.com/1443986/99122580-9b0feb80-25cc-11eb-9ed4-14a89b828dac.png)
![image](https://user-images.githubusercontent.com/1443986/99122665-c4307c00-25cc-11eb-8590-173224b59419.png)
![image](https://user-images.githubusercontent.com/1443986/99122722-df9b8700-25cc-11eb-91b5-65a9cb9cd8bb.png)
