### ISSUE TITLE
Add directions to Request Cart to inform folks they don't have to request immediately and can group up items.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#445]
![Screen Shot 2020-11-02 at 10 02 20 AM](https://user-images.githubusercontent.com/2806645/97902506-93aa3180-1cf2-11eb-8989-02d1329a1c5a.png)

Recommendation was to put a note below the Request Cart header with a tip or something.

**Comment by hackmastera** [comment]
Language needed; maybe @faithc or @apferrar can help?

**Comment by hackmastera** [comment]
It might be nice to wait on this and see whether we observe user behavior that indicates help text is needed.

**Comment by tpendragon** [comment]
@hackmastera We already did, this ticket got made because during the test of the request cart Faith made multiple requests across pages. 😂
