### ISSUE TITLE
Requests: Location should be ReCAP if site code is rcppa, rcpph, rcpxc, rcpxg, rcpxm, or rcpxr

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#447]
See https://github.com/PrincetonUniversityLibrary/pulfa/blob/e8f383c4135948412fd0f0f88bfd73201f05e6a1/webapp/xsl/ead-classic-view.xsl#L241

Implement here: https://github.com/pulibrary/pulfalight/blob/0d3b5ac5287a465fdbf0569c637c603023b249cc/app/values/aeon_request.rb#L21

**Comment by hackmastera** [comment]
possible this was done in https://github.com/pulibrary/pulfalight/commit/1fd709b6f75385282beeceb28528a805be8aa779? Needs a test.

**Comment by hackmastera** [comment]
LAE086 can be used for testing; it has `<physloc type="code">rcppf</physloc>`

But this seems blocked by #288 for now
