### ISSUE TITLE
Do not include physloc notes in "located in" field

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#451]
From @faithc: The physloc text notes associated with container records, which note where in the stacks an item is located, should not display on the site. This is for staff use only. For example, see: https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c5621. "D-zone" should not display on the site.
![Screen Shot 2020-11-04 at 8 36 42 AM](https://user-images.githubusercontent.com/845363/98118366-207ef780-1e79-11eb-8ebb-dfa5d374f6bf.png)

**Comment by tpendragon** [comment]
It looks like D-Zone is a physloc code without any sort of identifier to say it's private. @regineheberlein should these be identified in the EAD somehow?

**Comment by tpendragon** [comment]
See https://github.com/pulibrary/pulfalight/compare/physloc_staff_notes for the WIP. Can't move forward until we know how to hide these notes.
