### ISSUE TITLE
Value of "level" should only come from DSC

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pulfalight#453]
Split out from the original description in #172

The values included are from the DSC and DSC2, the DSC2 is what we would want to ignore.

**Comment by faithc** [comment]
Sorry if I'm misunderstanding this ticket, but we don't want Level as a facet on the search results page at all.

**Comment by hackmastera** [comment]
I thought this was configured to show up in other places. We'll close it for now and if we see anything wrong we'll open a new ticket with an example.
