### ISSUE TITLE
Replace all instances of email address in access tab with link to the Ask Us! form

### ISSUE THREAD

**Issue by apferrar** [pulibrary/pulfalight#466]
Removing the email address of the library location in the access tab of the collection. Instead direct people to the [Ask Us form](https://library.princeton.edu/special-collections/ask-us) since we now have a central SC email ticketing system.

This requires getting the SC email address specialcollections@princeton.libanswers.com working.

**Comment by tpendragon** [comment]
I think this might have happened as part of the data migration? I'm looking at https://findingaids-beta.princeton.edu/catalog/aspace_C0564_c001 and I don't think we did that. @regineheberlein did you transform this as part of the migration?

**Comment by tpendragon** [comment]
@ccleeton Confirmed we can close this.
