### ISSUE TITLE
Components without requestable material display empty footer bar

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#477]
Not sure if this is new, but I just noticed it. Very distracting as the empty "footer" bar is sticky.

<img width="1411" alt="Screen Shot 2020-11-11 at 10 24 07 AM" src="https://user-images.githubusercontent.com/784196/98837645-cf3aaf00-2408-11eb-84b7-925a26bf3cb6.png">

**Comment by christinach** [comment]
@eliotjordan I've seen this since last week when I started on the project. I assumed it is a known issue.

**Comment by tpendragon** [comment]
It'll have suggest a correction in it soon.

**Comment by eliotjordan** [comment]
I just saw that in https://github.com/pulibrary/pulfalight/pull/476. This is no longer an issue.
