### ISSUE TITLE
Dates should not display as a range starting from 0

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#486]
How should they display?

example: https://findingaids.princeton.edu/collections/C0776/c00071

![image](https://user-images.githubusercontent.com/845363/99097248-5c1a6f80-25a5-11eb-9be3-0374b562bc40.png)

**Comment by tpendragon** [comment]
@ccleeton @faithc Can you comment on what these should look like? Just `...), 1945`?

**Comment by ccleeton** [comment]
@faithc should this be undated to 1945?

**Comment by faithc** [comment]
I'm confused. The date range for this component record is circa 1870-1945. Not sure where the zero is coming from?

**Comment by hackartisan** [comment]
In pulfa the date does not display in the title heading. But in the wireframes it looks like the date is included. So @faithc this should display as `...), circa 1870-1945`, can you confirm?

**Comment by faithc** [comment]
Gotcha. And yes, thanks.
