### ISSUE TITLE
Header should match newer PUL branding from Library homepage

### ISSUE THREAD

**Issue by kelynch** [pulibrary/pulfalight#488]
The banner color and logo size should match the style elements of PUL branding on the Library main website homepage.

Style elements from Drupal site - https://github.com/pulibrary/pul_library_drupal/blob/46f94c8f1201a25657da8b95b47a660910e9a130/sites/all/themes/pul_base/assets/source/styles/components/_branding.scss

Blocked by LUX Update.

**Comment by tpendragon** [comment]
I think to do this we'd have to update Lux, and I have some fuzzy memory of it being different in Lux on purpose. Maybe @axamei or @sdellis can comment with their expertise?

**Comment by sdellis** [comment]
@kelynch and @tpendragon I would be happy to update LUX, and I'll make a ticket there unless @axamei has objections.

**Comment by hackartisan** [comment]
fwiw the header color is also an open ticket for dpul https://github.com/pulibrary/pomegranate/issues/827

**Comment by sdellis** [comment]
Merging [this PR](https://github.com/pulibrary/lux/pull/350) and cutting a new LUX release should unblock this. Bumping the LUX version in package.json will fix it.

**Comment by kelynch** [comment]
Upgrading to the latest version of LUX should address this in PULFAlight.
