### ISSUE TITLE
"View Content" should be renamed to "Download Content"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#489]
See https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c363

@faithc @ccleeton we feel like it's unclear what these buttons do, especially if a viewer may appear for restricted content. Do you agree with this?

**Comment by ccleeton** [comment]
What if the item is restricted from download and the user is only able to view? Are you suggesting this as a site wide change?

**Comment by faithc** [comment]
Not sure what you mean by buttons plural? I think it makes sense to leave the wording as is, or perhaps it could be changed to "access content"? I think the phrase needs to be both broad as well as instructional as there will be a few scenarios for how users will actually be able to access digital content based on restrictions, as Christa mentioned. "Download" seems to specific and potentially misleading. This may be something we want to check in with our colleagues about, including @sdellis and the Virtual RR group. Though, as far as I'm aware, no one has mentioned that the current wording is problematic or confusing. This scenario is similar to the Request button as several scenarios may apply in terms of whether something is restricted or needs review.

**Comment by hackartisan** [comment]
@ccleeton @faithc the time we think it's confusing is when there's a viewer right above it. What do you think about this scenario? Please see screenshots in the pull request for adding the viewer based on a query to figgy: https://github.com/pulibrary/pulfalight/pull/479

**Comment by faithc** [comment]
Ah, well to me then it makes sense to not even have a button in those cases. Is that possible--to know when content will be accessible via the viewer based on the link? I'm thinking no since restrictions are managed in Figgy?

**Comment by tpendragon** [comment]
We think we won't have these anymore, given the removal of links to relative PDFs. Closing this until we find some examples.
