### ISSUE TITLE
Relative PDF links in DAOs should not show a "View Content" button

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#490]
See https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c363

These DAOs are only in there to generate offline finding aids for the reading room via an external script. We don't need to use or display them.

**Comment by sdellis** [comment]
@tpendragon Are they in Figgy? If so, can you use the current method for logging in ("reading room functionality") to Figgy to display them to users? The general public can request to view these, so we would not be able to rely on PUID or CAS to authenticate users.

This is a policy question I think, so it might be a better question for Public Services.

**Comment by sdellis** [comment]
I have not been part of any "virtual reading room" talks so I don't know what y'all have in mind for that, but @kelynch might have some insight on this too.

**Comment by faithc** [comment]
Assuming we want to mimic how this works on the current site? https://findingaids.princeton.edu/collections/C1491/c363. But agree this is a question for the virtual RR WG and Public Svs.

**Comment by sdellis** [comment]
@faithc the current site limits viewership to people with Princeton IDs. My understanding is that the general public should be able to request to view. Do we have an option/path for this?

**Comment by faithc** [comment]
Think this is something @kelynch and the VRRWG have been reviewing.

**Comment by kelynch** [comment]
Yes, we've started talking about implementing a request feature at some point, where the requests would go to a queue for Special Collections staff to review and potentially add for access.  I'll make sure this is on the agenda for the next VRR meeting.

**Comment by kelynch** [comment]
To clarify, for MVP it is my understanding that we need to preserve the current OARSC functionality that is available for some materials based on the list of "restricted viewers" in Figgy for that collection, which is what this item has in the current Finding Aids application.  Details for a request feature are in discussion, but have not been finalized yet and should not block this issue for launch.

**Comment by tpendragon** [comment]
@faithc @sdellis @kelynch I think there's been some confusion here. In the EAD is a DAO for `pdf/c363.pdf`. I'm -assuming- that's powering some sort of functionality, and asking if we need to duplicate whatever that functionality is.

If there's no confusion, then what I'm hearing is "make the JS viewer work, and make sure nothing shows up in the UI for the PDF `pdf/c363.pdf`. Can someone confirm? If so I'll update the issue.

**Comment by sdellis** [comment]
@tpendragon Yes, the relative DAO path IS powering the off-line, reading room access to content for Toni Morrison. 

As long as we don't need to update the finding aid in the reading room, it will continue to work. However, as soon as we need to update the finding aid with the latest EAD, those links will be important to have. 

@kelynch Are there any plans to update the Reading Room Toni Morrison content before we implement the "request feature" you are talking about? If there are, we should definitely keep the relative paths and do nothing with them (i.e., "nothing shows up in UI") in PULFALIGHT.

**Comment by tpendragon** [comment]
@sdellis And it's not `findingaids.princeton.edu` that's generating that off-line reading room access? If that's the case, I'll adjust the ticket.

**Comment by sdellis** [comment]
@tpendragon Correct, the current site does not generate the off-line site. That is a separate process/script.
