### ISSUE TITLE
Export component-level access note as part of requesting functionality

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#497]
Looking at the access restrictions, we want to see how it would work if lower-level (component) notes exported instead of collection-level note as these will have more specificity and are associated with specific containers 
@tpendragon #

Call slips in Aeon Requests should have the access restriction note for the components.

**Comment by ccleeton** [comment]
Not sure why I was not able to add a milestone to this. but it should be a MVP

**Comment by tpendragon** [comment]
@ccleeton Is there any way this could be not MVP (as in, we could release to users without it)? We have a lot of tickets, I'm concerned changing functionality from what exists will result in follow-up tickets that will further distract from getting this to users.

**Comment by ccleeton** [comment]
@faithc Do we need this to be MVP? Is it blocking?

**Comment by faithc** [comment]
I would argue that it's not blocking; however, I defer to you as to whether or not it's MVP. Would be nice to utilize the data staff are including in finding aids, which provide information about access restrictions that are specific to materials as opposed to only relying on the collection-level access note; though I can't recall whether this is happening in pulfa2 or now, i.e. whether component/lower-level access notes appear on call slips when those notes supersede the collection-level note.

**Comment by ccleeton** [comment]
As long as the collection level restriction is coming into the call slips its fine to not be MVP. We in PS basically just need to see that something is restricted in the collection and then we can look at the component to see more. But this would be helpful in a next sprint.

**Comment by tpendragon** [comment]
@faithc Can you provide an example component that's restricted but its collection level isn't, so we can make sure the call slip has it?

**Comment by faithc** [comment]
In Toni Morrison, C1491, the collection-level access note type is set to "review." This is one of many components that are marked with type "restricted": https://findingaids.princeton.edu/catalog/C1491_c1622. 

Is that helpful?

**Comment by tpendragon** [comment]
I'm looking at the code and I think this is already happening? Can @faithc or @ccleeton find an example where it's not? For example, C1491_c1622 is sending "This material is closed until 2037."

**Comment by ccleeton** [comment]
Based on what I saw with some items in ACLU today in Aeon I would say yes it is working.
