### ISSUE TITLE
Make "action link" appearance consistent

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#503]
<img width="507" alt="Screen Shot 2020-11-19 at 10 13 29 AM" src="https://user-images.githubusercontent.com/609368/99685313-74303a00-2a50-11eb-82ed-9d6db3796fa8.png">

These appear at the bottom of the component description. See: https://pulfalight-staging.princeton.edu/catalog/aspace_C1491_c1262

**Comment by tpendragon** [comment]
This got done.

![Screen Shot 2021-03-11 at 10 23 34 AM](https://user-images.githubusercontent.com/2806645/110835597-db6a3800-8253-11eb-9cfb-72c16c354d90.png)
