### ISSUE TITLE
"Search within collection" results need a H1-level page title/header

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#506]
When searching within a collection, the results screen loses the context of the collection. Even though the facets provide an indication that the results are limited to the collection, this is not enough distinction among other facets and creates a jarring experience. This is both an accessibility and a UX issue.

The solution is to place "Search Results within [Collection Name]" (or equivalent) as a `<h1>` level header. See screenshots:

<img width="1307" alt="Screen Shot 2020-11-19 at 1 22 42 PM" src="https://user-images.githubusercontent.com/609368/99709012-9df75a00-2a6c-11eb-8aa8-e4b26bc3629b.png">
<img width="1241" alt="Screen Shot 2020-11-19 at 1 23 23 PM" src="https://user-images.githubusercontent.com/609368/99709024-a2237780-2a6c-11eb-9267-4a795d34555b.png">

Severity: Major

WCAG Guidelines:
2.4.6 AA | Headings and labels clearly and accurately describe their topic or purpose.
https://www.w3.org/WAI/WCAG21/quickref/#headings-and-labels

**Comment by hackartisan** [comment]
@sdellis I thought we were supposed to only use h1 for the header. Is that still a current best practice?

**Comment by sdellis** [comment]
@hackartisan I don't think there is an agreed-upon best practice on this. I'm open to different opinions, but I would argue that the app title/logo is not part of the document structure (that should generate a table of contents) and therefore should NOT be wrapped in a heading. 

@axamei any thoughts on this?

In fact, thanks for bringing this up, as it made me realize that I need to update the LUX announcements banner to remove the heading and add an aria `role=alert` as well.

**Comment by axamei** [comment]
h1 should describe the page. "Search Results within [Collection Name]" would be a helpful h1 in this particular context. 

i'm having a hard time seeing it in the screenshots. if the design doesn't include this text, then you can visually hide this text but still expose it to screen readers.

**Comment by sdellis** [comment]
Thanks, @axamei. The screenshots are meant to illustrate that the current finding aids site provides a heading describing the collection context for the search results, as opposed to the PULFALight site in which collection context is just one of many facets. 

So yeah, let's add "Search Results within [Collection Name]" as an h1. 👍

**Comment by hackartisan** [comment]
Makes good sense to me. Thanks!
