### ISSUE TITLE
Request to create and provision a PULFALight Beta Server (to be accessible as the production environment)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#518]
This is to please request a server environment for the production environment of PULFALight, serving as a publicly accessible beta server (until this is prepared to be resolved from findingaids.princeton.edu).

From the basic specifications on the staging environment, I would like to please request the following from @kayiwa in the Operations Team:

- Two CPU AMD64 cores (~2200 MHz, Intel(R) Xeon(R) CPU)
- ~16GB RAM
- ~40GB of Disk Storage, with the other logical volumes configured in a manner similar to the following please:
```
Filesystem                Size  Mounted on
udev                      7.9G     /dev
tmpfs                     1.6G  /run
/dev/mapper/lib--vg-root   /
tmpfs                     7.9G  /dev/shm
tmpfs                     5.0M     /run/lock
tmpfs                     7.9G     /sys/fs/cgroup
tmpfs                     1.6G     /run/user/1001
tmpfs                     1.6G     /run/user/1000
```

I apologize in advance if any of this is unnecessary or not possible, or should another recommendation be followed (e. g. a recommendation for more CPU core processing power). Thank you very much!

Update: This request should also please include that this include a `findingaids-prod.princeton.edu` DNS record and accompanying SAN entry in the X.509 certificate.

**Comment by jrgriffiniii** [comment]
@carolyncole referenced a practice in which EUS uses `servicename-prod.princeton.edu`, with the hope of shifting this to `servicename.princeton.edu`. @kayiwa confirmed that this could be supported using X.509 SAN entries.

**Comment by eliotjordan** [comment]
Done.
