### ISSUE TITLE
Year-titled <c level="file"> elements under a component aren't showing up as individual records.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#52]
See ![Screen Shot 2019-10-30 at 1.28.51 PM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/3de6ed39-d9f9-4883-9481-c477f58d5cf2)

vs

![Screen Shot 2019-10-30 at 1.29.12 PM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/3deb37e5-c7cd-4016-8128-cb4b79a36a7b)

**Comment by jrgriffiniii** [comment]
An example of a component which was indexed at the file level is:

```xml
<c level="file" id="MC016_c11033">
  <did>
    <container>
      <ptr target="MC016_i605" />
    </container>
    <unittitle> "Department of State, Miss Snell's Record of People Sent Articles and Speeches" </unittitle>
    <unitdate>undated</unitdate>
    <physdesc>
      <extent type="computed">1 box</extent>
    </physdesc>
  </did>
</c>
```
(https://pulfalight-staging.princeton.edu/catalog/MC016_c11033)

which, should be available as a child component on https://pulfalight-staging.princeton.edu/catalog/MC016_c11029

**Comment by eliotjordan** [comment]
I'm having difficulty translating what we see on the finding aids site and how records should be displayed in pulfalight. **It would be a helpful to have a sketch of where these component should appear.**


 Is this the issue that there should be a contents tab on the "Series 1: Selected Correspondence" and the "Acheson, Dean, 1944-1958" pages with links to their children. That isn't the case right now. Only the parent "John Foster Dulles Papers" page has the "components" tab where you can navigate all the way down.

<img width="951" alt="Screenshot 2020-07-15 17 17 50" src="https://user-images.githubusercontent.com/784196/87605881-495b6100-c6bf-11ea-9aed-160363270b9d.png">

Although when you click "1921/1921" (the normalized title), the parent-child tree is rendered strangely:

<img width="566" alt="Screenshot 2020-07-15 17 20 33" src="https://user-images.githubusercontent.com/784196/87606005-90e1ed00-c6bf-11ea-805f-e62f8b0ee9e3.png">

Overall, the default display here is quite confusing.

**Comment by jrgriffiniii** [comment]
I apologize for the lack of details in this issue. My sense is, at this point, that restructuring the component show view page should follow the design found with: https://xd.adobe.com/view/c3b49814-866d-449f-44e7-2479ff0cbb30-b585/screen/8511ff6c-e5b8-4a41-9926-9c90325d315a

**Comment by jrgriffiniii** [comment]
The design for this is going to follow this pattern:

![image](https://user-images.githubusercontent.com/1443986/87704431-626d1c00-c76a-11ea-8b0f-f54b96adbbcb.png)

Perhaps closing this issue in favor of advancing a child issue for https://github.com/pulibrary/pulfalight/issues/240 would be more helpful at this point?

**Comment by jrgriffiniii** [comment]
I have created https://github.com/pulibrary/pulfalight/issues/308 in order to close this. Please let me know if that seems actionable, and I can close this issue.
