### ISSUE TITLE
Link is dead on ask a question form

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#527]
https://github.com/pulibrary/pulfalight/blob/main/app/views/catalog/_question_modal.html.erb#L25

**Comment by tpendragon** [comment]
@ccleeton @faithc Is there an alternative FAQ for "How can I purchase copies from rare books and special collections?"?

**Comment by ccleeton** [comment]
I don't see the dead link? Both redirect to our newer combined Digitization guidelines. I have also asked that this FAQ be editied to be more uniform.

**Comment by tpendragon** [comment]
@ccleeton https://faq.library.princeton.edu/rbsc/faq/64876 works for you?

**Comment by ccleeton** [comment]
Oh interesting, i searched it on the SC site and found this which is linked to libanswers https://library.princeton.edu/special-collections/faqs/how-can-i-purchase-copies-rare-books-special-collections
