### ISSUE TITLE
Creator facet is sometimes missing

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#546]
The collection facet does not show when known creators are entered. A search for "Derrida" should work. A search for "John Foster Dulles" lists some creators, but not John Foster Dulles himself. Perhaps the Creators are not being indexed properly?

**Comment by tpendragon** [comment]
Creators aren't published in ASpace yet.

**Comment by tpendragon** [comment]
![Screen Shot 2021-01-27 at 11 56 42 AM](https://user-images.githubusercontent.com/2806645/106046352-00855b80-6097-11eb-8f73-2e4d6faaf2de.png)
