### ISSUE TITLE
make sure ark-based legacy urls still work

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#548]
This is to ensure continuity for researchers' bookmarks and citations used in published research. 

Regine:house_with_garden:  12:16 PM
Question regarding arks, with apologies if I'm just not seeing the corresponding issue. Did we discuss whether bookmarked legacy links (constructed from arks) still redirect to the corresponding ASpace record after the cutover? (The old urls will migrate to the EAD Location field.)
New

Esmé:taco:  12:32 PM
@Regine that seems like a good issue to create — we should either make sure the URLs are the same, or redirected at some level, or we'll need to update a lot of ARKs
:+1:
1

**Comment by tpendragon** [comment]
There's no global change to happen here, there's just some ARKs that staff are going to fix.
