### ISSUE TITLE
Submission of "Ask A Question" results in error

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#551]
<img width="815" alt="Screen Shot 2020-12-04 at 4 31 05 PM" src="https://user-images.githubusercontent.com/609368/101216877-49e49c00-364e-11eb-9d77-29ee6be696f4.png">

**Comment by tpendragon** [comment]
We need to get pony express set up. @kayiwa do I talk to you to do this?

**Comment by tpendragon** [comment]
Honeybadger error: https://app.honeybadger.io/projects/65922/faults/71321332
