### ISSUE TITLE
Keyword search for name in direct order yields too many results

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#557]
Attempting to do a keyword search for a name by entering first and then last name yields too many results, including results in which only the first name or only the last name appears. When searching for a name by entering last, first name, autocomplete options only show name when it its present in unittitles. As an example, I tried doing a keyword search for Frederick Vinton using direct and indirect order. 

This behavior is unlike the current site where regardless of how one enters a name in a keyword search, targeted results are generated. When I do the same keyword search for Frederick Vinton in pulfa 2.0, I can 4 results regardless of which way I enter the name.

**Comment by tpendragon** [comment]
I think this happens because we had to set the MM parameter to be really low (minimum must match) to make box/folder queries return. We'll have to do some fiddling to see if we can improve things.

**Comment by tpendragon** [comment]
I set minimum must match to 75%, which means 75% of the query has to appear for an item to show up in results. I can make that number higher for more restricted results (100% means every field needs to show up), but I think we should fiddle with that later.

**Comment by tpendragon** [comment]
@faithc Is this still the case? I can set the required matches to be higher, but I'm concerned it'll filter out matches (in this case, for instance, data's in there as both Vinton, Frederick and Vinton, Frederic, with various dates depending on when the correspondence was.)

**Comment by faithc** [comment]
I think there are still too many results, and that it should mimic the behavior of pulfa 2 where one gets only 4 results regardless of how one enters the name. The other results that are displaying in pulfalight have nothing to do with Frederick Vinton. https://findingaids.princeton.edu/?v1=Vinton%2C+Frederick++&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0 vs. https://findingaids-beta.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=Vinton%2C+Frederick.

**Comment by tpendragon** [comment]
@faithc Even https://findingaids-beta.princeton.edu/catalog/C0344 ? (Fourth result down on Pulfalight)

**Comment by tpendragon** [comment]
There's a good chance https://findingaids-beta.princeton.edu/catalog/TC011_c194 is a match too, which wouldn't match if Frederick had to be included. How about I set the minimum must match on staging after it indexes everything and we can see how it looks?

**Comment by faithc** [comment]
That's "Rand, Vinton" and "Rand, Wakefield" though. 

Guess we could try that, but I still think whatever method is being used on the current site seems appropriate.

**Comment by tpendragon** [comment]
The indexing backends are different, so I'm not sure we'll hit precisely the same results coming back, but I can definitely make it stricter so we can see how it goes.

**Comment by tpendragon** [comment]
(Sorry for the back and forth, by the way, I've personally always preferred too-many-results with the relevant ones popping up at the top, rather than fewer results where I worry I miss things - too much google I guess. 😅 )

**Comment by faithc** [comment]
Ha, that's ok. It's good to think through, but I definitely think stricter matching is the way to go for this site. Just wanna loop @ccleeton in too.

**Comment by ccleeton** [comment]
This seems good to me. I think we will know if its more of an issue when the staff starts to use it.

**Comment by tpendragon** [comment]
@faithc @ccleeton I pushed up a test to https://pulfalight-staging.princeton.edu. Could you take a look when you get a chance and see if that's working more the way you expect?

**Comment by faithc** [comment]
Hmm now the results for Frederick Vinton are slightly different. There are now 4 results on each site; however [these are results on pulfalight](https://pulfalight-staging.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=Frederick+Vinton), and the resulting list on the current site includes [these collections](https://findingaids.princeton.edu/?v1=Frederick+Vinton&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0). Aside from the 3 that overlap, pulfalight includes MC248- I'm not sure where his name shows up-and pulfa 2 includes AC123, which seems more relevant.

**Comment by tpendragon** [comment]
AC123 matches in PULFA2 because of a bioghist note which doesn't seem to be in aspace. See https://findingaids.princeton.edu/collections/AC123#description.

MC248 I think is matching because there are authors in there with both Frederick and Vinton in their names, they're just not super close. I'm not sure why it's ranked higher than TC011.

**Comment by faithc** [comment]
Ah, right. The bioghist notes are now associated with agent records; however we want those notes to be displayed and searchable in finding aids too. Is that doable?

**Comment by ccleeton** [comment]
@tpendragon I agree with @faithc that it should be stricter and to what she also said. We would like to see the login for the test that you did in staging be applied to beta soon.

**Comment by tpendragon** [comment]
@faithc @ccleeton This has been deployed to beta. Can you check it out and close this if it's good?

**Comment by faithc** [comment]
From a quick search, this looks better to me; though I'm a bit nervous about the fact that the number of results for some searches differ drastically between pulfalight and pulfa2, for example, doing a keyword search for Toni Morrison. But maybe that's because the indexing functionality for the former is better? I wonder if we should keep this open while colleagues continue to test it out; in case they discover issues we may be missing.

**Comment by tpendragon** [comment]
@faithc Can we just open a new issue if someone finds more relevancy problems? Keeping an issue open with no clear way to close it makes it hard to track when the blocking issues are done.

**Comment by faithc** [comment]
Sure, that makes sense. We can close it then if @ccleeton is cool with that.
