### ISSUE TITLE
Using quotes in keyword search yields no results

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#558]
Doing a keyword search for "Frederick Vinton" yields no results even though there are multiple results that appear if one doesn't use quotes. This behavior was noticed by a staff person when testing the site. Users often apply quotes when doing a keyword search with multiple terms, for example, when searching for names. A search yielding no results erroneously is problematic as a user would likely assume that Princeton doesn't have collections related to their search.

This behavior is different than the current site where the use of quotes doesn't affect the search results.

**Comment by tpendragon** [comment]
This is interesting. It's because the records are mostly in the form of "Frederic Vinton" and Solr considers the quotes to be an exact match phrase query. Should we strip the quotes and remove that functionality?

**Comment by faithc** [comment]
Ah. And yes, I think so since that's how the current site functions. @ccleeton?

**Comment by ccleeton** [comment]
Agreed!
