### ISSUE TITLE
Search results are not being listed by relevancy 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#560]
This is particularly the case if one doesn't include "papers" or "records" etc. in the search field. Example:  when you search "Board of Trustees" you get these results on the beta site https://findingaids-beta.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=board+of+trustees. When you search this phrase in pulfa 2.0, the most relevant collection is listed first, regardless of whether you add "records" to the keyword search. https://findingaids.princeton.edu/?v1=board+of+trustees&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0

**Comment by tpendragon** [comment]
I think we're better than we were. Maybe if I boost matches where the item's in a collection with that title?

**Comment by tpendragon** [comment]
@faithc Can you look at https://findingaids-beta.princeton.edu/catalog?group=true&q=board+of+trustees&search_field=all_fields actually and confirm those results aren't acceptable? We did some boosting before which I think has helped a lot.

**Comment by faithc** [comment]
Perhaps it's better? But the Board of Trustees records collection should be the first result. @ccleeton looping you in too.

**Comment by ccleeton** [comment]
Yes, since the words Board of Trustees are in the collection name it should appear first.
This one is doing the same thing Search office of the president and the collection comes second https://findingaids-beta.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=office+of+the+president
Not to mention there are many other office of the president collections not showing

**Comment by tpendragon** [comment]
I spent a ridiculously long time trying to boost items which had collections that exactly matched the given query and was not successful. Instead, for now, I think I'm going to adjust the "mm" parameter to limit the number of results that get returned and return to this at some other time.

Relevant things I tried:

http://robotlibrarian.billdueber.com/2012/03/using-localparams-in-solr-sst-2/
https://stackoverflow.com/questions/20217686/multiple-boost-queries-in-solr/20345687#20345687

**Comment by tpendragon** [comment]
Another example: McCosh Hall

**Comment by tpendragon** [comment]
Add the quotes support back.

**Comment by tpendragon** [comment]
I've got some changes that I think get this a lot closer, if not closes this: https://pulfalight-staging.princeton.edu

**Comment by tpendragon** [comment]
@faithc @ccleeton This is our last blocking release ticket. When you get a chance can you review with relevant people and see if we're in good shape now?

**Comment by ccleeton** [comment]
I did a bit more poking around and it looks great! I did ask the PS take a look and give me feedback. I will feed that over when I get it!

**Comment by faithc** [comment]
+1. And now that I'm seeing how much better the search seems to be, I'm wondering if we should keep the default view as "grouped by collection" despite what I suggested yesterday since that's what we had been planning to do. @ccleeton @tpendragon

**Comment by tpendragon** [comment]
@faithc Your call! I'll mark the pull request that changes it back as a draft, and we can merge it in if we decide to make all results the default view.

**Comment by faithc** [comment]
Ok, yeah, let's maybe keep it as is? @ccleeton What say you?

**Comment by ccleeton** [comment]
I think keeping it works. We can encourage staff and users to toggle between the two.

**Comment by tpendragon** [comment]
Great! I'm gonna close this and that one then.
