### ISSUE TITLE
Searching by call number does not work without capitalizing alphas

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#562]
When searching for MC097 if you do not capitalize MC and use mc the search results are incorrect
https://findingaids-beta.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=mc097
Search with capital letters goes directly to - https://findingaids-beta.princeton.edu/catalog/MC097

**Comment by faithc** [comment]
Just want to add that capitalization doesn't affect results on pulfa 2.0: https://findingaids.princeton.edu/?v1=mc097&f1=kw&b1=AND&v2=&f2=kw&b2=AND&v3=&f3=kw&year=before&ed=&ld=&rpp=10&start=0.

**Comment by hackartisan** [comment]
duplicate of #525

**Comment by escowles** [comment]
Closing as duplicate of #525
