### ISSUE TITLE
Display Call Number in search results at collection level

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#568]
In the main search we need to see the call number displayed at the collection level. 
Example: https://findingaids-beta.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=tarkington show call number with the Booth Tarkington Papers

**Comment by tpendragon** [comment]
![Screen Shot 2021-01-20 at 2 50 49 PM](https://user-images.githubusercontent.com/2806645/105250615-e85d8b80-5b2e-11eb-99de-4b388d3ef921.png)
@ccleeton Something like this?

**Comment by ccleeton** [comment]
@tpendragon yes this should be fine. @faithc are you good with this?

**Comment by faithc** [comment]
Yes. Can the call number come before the box count?
