### ISSUE TITLE
Overview tab bug?

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#570]
Once in a collection and you select a component you can not get back to the overview of the collection level description
https://findingaids-beta.princeton.edu/catalog/aspace_AC109_c00001

**Comment by tpendragon** [comment]
@ccleeton You have to hit the title of the collection. This is probably a UX issue - where did you expect to hit to be able to return to the collection?

**Comment by ccleeton** [comment]
@tpendragon I and others want to be able to use the top navigation "Overview" to go back to overview. All the other top navigations go back to where you would think they would. Does that make sense?

**Comment by tpendragon** [comment]
I think we're using "Overview" now as "Overview of whichever thing you're on at the moment" - was the intention that it always have the collection overview?

**Comment by ccleeton** [comment]
The response has been that yes it would go back to the collection overview. I think it would be confusing to use the same wording twice. @faithc thoughts?
