### ISSUE TITLE
Collection-level title display is showing dates incorrectly.

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#571]
Mock-up:![Screen Shot 2021-08-30 at 10 27 00 AM](https://user-images.githubusercontent.com/65608/131355128-c6291ea5-356f-4e1d-9918-235839842140.png)

Inclusive dates appear twice and bulk dates have a slash (probably coming from the encoding, normalized formatting) as opposed to a dash between beginning and end dates (DACS formatting). Example: https://findingaids-beta.princeton.edu/catalog/C0062_c000001087. 

Should look like https://pulfa.princeton.edu/collections/C0062/c000001087

The title for this should be

`Booth Tarkington Papers, 1812-1956 (mostly 1899-1946)`

**Comment by tpendragon** [comment]
@faithc I'm real confused, I'm seeing dashes. Maybe the new index fixed this? Can you take a look again and maybe screenshot what's wrong?

**Comment by ccleeton** [comment]
MC001 and related are still showing dashed https://findingaids-beta.princeton.edu/catalog/MC001-02-03

**Comment by faithc** [comment]
<img width="1064" alt="Screen Shot 2021-01-21 at 3 02 31 PM" src="https://user-images.githubusercontent.com/8058702/105406470-7a7e9600-5bfa-11eb-90b3-5ddc0f6bfd01.png">

**Comment by tpendragon** [comment]
OH, in the title! Thank you.

**Comment by faithc** [comment]
Oh, yes; sorry, that probably would have been useful to articulate. Sorry for the confusion!

**Comment by tpendragon** [comment]
@faithc Looking at this now. The bulk date is definitely different from the old site, but I'm seeing duplicate dates in pulfa too. Do you know what the deal is there? https://findingaids.princeton.edu/collections/C0062

**Comment by faithc** [comment]
Oh, I guess it's pulling the data from `unittitle` and `unitdate`? Guess I didn't notice the repetition in pulfa since the font is different for the `untidate`s. Wondering if it should just display what's in `titleproper` to eliminate the redundancy?

**Comment by regineheberlein** [comment]
titleproper has no nested elements in ASpace--it's a string.

on pulfa, titleproper has one or several nested date elements with type attributes for the inclusive and bulk dates. https://findingaids.princeton.edu/collections/C0062 is what we've always had. It displays the string value of titleproper (including the string value of the nested date), and after that, the values of the `@type` ("bulk" and "inclusive") respectively in smaller gray font.

```
<titleproper>
Booth Tarkington Papers,
<date normal="1812/1956" type="inclusive">1812-1956</date>
(bulk
<date normal="1899/1946" type="bulk">1899-1946</date>
): Finding Aid
</titleproper>
```

**Comment by tpendragon** [comment]
This is true, but the constituent parts are in aspace:
```
<titleproper>Noël Riley Fitch Papers, 1858-2012 (bulk 1965-1995): Finding Aid <num>C0841</num></titleproper>
```
```
    <unittitle>Noël Riley Fitch Papers</unittitle>
    <unitid>C0841</unitid>
    <unitdate datechar="creation" normal="1858/2012" type="inclusive">1858-2012</unitdate>
    <unitdate datechar="creation" normal="1965/1995" type="bulk">1965-1995</unitdate>

```

**Comment by regineheberlein** [comment]
yup, you can get it from archdesc/did/unitdate.

**Comment by tpendragon** [comment]
It looks like we generate the title from the unitdate/unittitle, so if you have some example records as well as what you want the title to be we can make it happen.

**Comment by faithc** [comment]
Well now I'm wondering if it should remain as is for now since that's how it's displayed on pulfa. Maybe the date info could be a smaller font similar to how it appears on pulfa?

**Comment by tpendragon** [comment]
@sdellis Thoughts? I'm not sure what the accessibility implications are there.
