### ISSUE TITLE
Call number for subseries using dashes not "." in URL

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#572]
Will the fact that the call number has dashes in the URL now instead of "." be an issue?
Example:
https://findingaids-beta.princeton.edu/catalog/MC001-02-01
https://findingaids.princeton.edu/collections/MC001.02.01

**Comment by tpendragon** [comment]
@ccleeton @faithc Is this an issue? Adding dots is quite a pain in this framework.

**Comment by ccleeton** [comment]
For me, I guess it comes down to that is not the way it is in figgy. So is that an issue?

**Comment by tpendragon** [comment]
Oh. Uh. Yes, but I can make it not an issue. 😂

**Comment by tpendragon** [comment]
Created https://github.com/pulibrary/figgy/issues/4394

**Comment by tpendragon** [comment]
Closed via https://github.com/pulibrary/figgy/pull/4395
