### ISSUE TITLE
Child Components should be requestable and sortable from their parent's show screen

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#573]
When viewing components with children, users need to be able to sort child components by title, date, and container. They should also be able to request child components (end-node, without children) from this screen simply by adding them to their cart. See examples below:

Wireframes ([URL](https://xd.adobe.com/view/a54bb217-10ff-43b2-72f6-6c3cadf376a4-d37a/screen/2aeefae6-aee7-4ec5-929a-64f600503129)):
<img width="1267" alt="Screen Shot 2020-12-14 at 4 47 06 PM" src="https://user-images.githubusercontent.com/609368/102140335-14e5ff80-3e2d-11eb-870d-c0233fed69fa.png">

Current PULFA site ([URL](https://findingaids.princeton.edu/collections/C0108/c00584)) :
<img width="1376" alt="Screen Shot 2020-12-14 at 4 48 02 PM" src="https://user-images.githubusercontent.com/609368/102140341-17e0f000-3e2d-11eb-874e-0a1e943235bc.png">

**Comment by tpendragon** [comment]
@sdellis Is there a lux component for this sort of thing already or should I just use datatables for the sorting?

**Comment by sdellis** [comment]
@tpendragon sorry, I missed the notification on this. There is a LUX component for this. You should be able to use https://pulibrary.github.io/lux/docs/#/Elements/DataTable

(I noticed a visual regression with the checkbox alignment that I will address right away, but you can go ahead and use it.)
