### ISSUE TITLE
Series/component-level notes are not displaying

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#574]
This is likely being addressed as part of the indexing work, but just wanted to note that component-level notes aren't displaying, only collection-level notes. Ex: https://findingaids-beta.princeton.edu/catalog/aspace_C1619_c24. 

This also includes missing origination and bioghists at series/component levels, ex. https://findingaids-beta.princeton.edu/catalog/aspace_C0033_c001

Relates to #279

**Comment by tpendragon** [comment]
I have origination and scopecontent working in #616. I can't do bioghist yet because the EADs that get exported from ASpace don't include the component's bioghist, just the collection's.

**Comment by tpendragon** [comment]
@faithc It might be a lot to ask, but if there are other series notes could you find examples like you did for those three? It helps a lot.

**Comment by faithc** [comment]
Another example: https://findingaids-beta.princeton.edu/catalog/C1596; none of the series/component-level notes are displaying, only some of the Collection overview notes. 
https://findingaids-beta.princeton.edu/catalog/C1596_c1 vs. https://findingaids.princeton.edu/collections/C1596/c1
https://findingaids-beta.princeton.edu/catalog/C1596_c78 vs. https://findingaids.princeton.edu/collections/C1596/c78

**Comment by tpendragon** [comment]
@faithc I think I've got this locked up. Can you check again?

**Comment by faithc** [comment]
Hmm, there are no paragraph breaks here either and some wonky formatting.

**Comment by tpendragon** [comment]
In which fields? It might be the source data no longer has the breaks

**Comment by faithc** [comment]
All of the scopecontent notes.

**Comment by faithc** [comment]
But yes, the data is now displaying. :)

**Comment by faithc** [comment]
Looks like ASpace does have the paragraph breaks. I just checked.

**Comment by tpendragon** [comment]
That's an easy fix - https://findingaids-beta.princeton.edu/catalog/C1596_c1 should be better now.

**Comment by faithc** [comment]
http://gph.is/1OXRUog

**Comment by tpendragon** [comment]
@faithc Safe to close this?

**Comment by faithc** [comment]
Yes, I think so. Thanks.

**Comment by faithc** [comment]
Actually, sorry, this is not resolved as other component-specific notes and elements are not displaying; rather collection-level elements and notes appear. For example, see https://findingaids-beta.princeton.edu/catalog/C0140_c03411 and https://findingaids.princeton.edu/collections/C0140/c03411, specifically creator, acquisition, and names and subjects. Related matter: the subjects associated with this specific component appear in the Find Related Materials as opposed to the record/main body of the page. Find Related Materials should only have the collection-level subjects.

**Comment by tpendragon** [comment]
Thank you for the example!

So "Find Related Materials" should only have collection-level subjects, and the component page should have the subjects for that component? I'm gonna make another ticket for that.

**Comment by faithc** [comment]
Yes, I guess so since those tabs at the top should only have collection-level notes. Thanks.

**Comment by tpendragon** [comment]
@faithc @ccleeton https://findingaids-beta.princeton.edu/catalog/C0033_c001 Look better?

**Comment by ccleeton** [comment]
This seems to look good to me but I will wait for @faithc since she put in the issue.

**Comment by faithc** [comment]
Yup, think this looks ok now. Thanks.
