### ISSUE TITLE
Search results are increasing results when using filters not decreasing

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#578]
Example of a search:
For Frederick Vinton (1817-1890). I know there at least a few files, possibly within various collections.

The first search box is a general one, so typing in “Frederick Vinton” to start got 416 very general results; it appears to be every Vinton or Frederick. Adding his dates makes it worse, 693 results, including every 1817 or 1890.

When I clicked on the pull-down menu hoping to specify, the NAME search for “Frederick Vinton” or “Vinton, Frederick” both got 0 results.

I did better searching only keyword = Vinton, 76 results, but the more general search shouldn’t be getting more specific results.

**Comment by tpendragon** [comment]
@ccleeton This should be significantly better now. Can you check `findingaids-beta.princeton.edu` and confirm, closing this if so?

**Comment by ccleeton** [comment]
This does seem to be better! Thanks!
