### ISSUE TITLE
Statement on Archival Language links

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#582]
Requesting that a link to the Statement on Archival Language (currently located on the Help page) be added to every finding aid page/component as part of the bottom navigation bar along with the Suggest a Correction and Ask a Question buttons/links.

**Comment by sdellis** [comment]
@faithc I will add this link to every component, but that bar is reserved for "action" items. I will find a better place for it. Also, I don't see a "Help" page. Can you provide a link to the Statement? Is the intention to bring the user to another site when they click the button?

**Comment by faithc** [comment]
Thanks, Shaun. Yeah, this page/section needs some work. It's currently only discoverable via the home page in the Request Materials section:  https://findingaids-beta.princeton.edu/research_help. Assuming we want a persistent link at the top of the site too like in pulfa (maybe next to the request cart?) with text that reads something like Site Information, since the content will be more than just helpful tips and such. 

@ccleeton looping you in. We should probably review the content here. The AV materials note can be deleted for example since that's now on the website.

**Comment by ccleeton** [comment]
The AV links to the website which is what we had said would work incase we change anything related to the policy so I'd like to keep that.
The whole grouping of the help page needs alot of work. The FAQs could use a hyperlinks in alot of the sections. @faithc should we go back to our drafts in the drive and work from there?

**Comment by faithc** [comment]
Oh that's right re: AV, forgot it just links to the website now. I didn't even check (clearly). haha

**Comment by ccleeton** [comment]
Just looked at this doc https://docs.google.com/document/d/15gzcQT36NttEVjvxNcUEZ2iFdZhkhp4vkfngJ--MYxs/edit
Looks like none of the hyperlinks there are showing on the new site. I did add a few new ones though.

**Comment by sdellis** [comment]
@faithc and @ccleeton since the FAQs/Help was not a part of the wireframes, and it appears that there's more content work to be done here, is this really MVP or not? I feel like this is being rushed. If it needs to happen for MVP, perhaps we should meet about this?

**Comment by faithc** [comment]
I think it's important to have a Help/Site info section with at least some content for the MVP, to be revised and enhanced as appropriate we move forward. (I think a good deal of content will be managed and generated by PS staff.) We do have some finalized content, such as the statement, which staff had initially requested be added to the current site in December 2019, so it would be great if this could be implemented. I'd be happy to meet to discuss.

**Comment by faithc** [comment]
Thanks, Shaun!

**Comment by faithc** [comment]
Hi @sdellis - where did you add the link to the harmful language statement? Don't think I'm seeing it?

**Comment by sdellis** [comment]
@faithc it's under "Research Help", which aggregates other statements, policies, and guides in one place.

**Comment by faithc** [comment]
Right, yes, that will be the statement's home, but staff were wondering if we could add a persistent link to that statement on every page of the site for heightened visibility. That's why we were wondering if a link could be added to the bottom navigation bar or somewhere else you think might be appropriate. Thanks.

**Comment by sdellis** [comment]
That statement does not currently have a persistent link. We will need to give the statement it's own page to do this. Should all of the statements under Research Help have persistent links? Perhaps the footer would be a better place for this information. Right now it has a lot of links that don't have much to do with archives and special collections.

**Comment by faithc** [comment]
Ah, perhaps it should have it's own page then. And yes, it seems like all of the content here should perhaps have their own pages. @ccleeton? At least for now, I think the statement on harmful language should. And yeah, there's a LOT going on in the footer. Does all of that need to be there? I worry that the link to the harmful language statement will be lost if it's added there.

**Comment by sdellis** [comment]
That is the standard Library footer, but we can change the links/sections to be whatever we want. I think that's the most appropriate place. It would be appropriate to put in the nav with "Ask a Question" and "Make A Correction" if it's a _call to action_, such as "Report Harmful Language". You ask users to do this in the statement, which can be included in the form instructions for context.

Also, can you clarify the title for me? You're referring to it as a "Statement on Harmful Language" but it's referred to in the site and in the title of this issue as a "Statement on Archival Language". "Statement on Harmful Language" seems a more appropriate title for the content, but I want to confirm with you.

**Comment by faithc** [comment]
Ok, we're asking folks to use Suggest a Correction to report harmful language so it's not actionable in that sense. (Actually, we may ask that the message for the suggest a correction form be updated to reflect this.) Maybe we could add a section footer titled something like "About Archival Collections"? 

And sorry, not sure why I keep changing the statement's title; "Statement on Archival Language" is correct.

**Comment by faithc** [comment]
Just had a meeting with the Inclusive Description WG, and there's consensus about adding a section "About Archival Collections" to the footer with a link to the statement. Folks mentioned that other content would be appropriate to add to that section at a later date.

**Comment by sdellis** [comment]
@faithc thank you for pulling the details together so quickly. I have enough to work with now. 👍

**Comment by sdellis** [comment]
@faithc  and @ccleeton two things: 
1. We should move the FAQs into LibAnswers. https://faq.library.princeton.edu/special-collections/
2. The Statement on AV Materials link should have the same title, but it's about Digitization and Publication Services. This is not good UX. Can we include the copy in the Finding Aids site? Also, "AV" should be spelled out (or at least use periods) as per the [University's Editorial Styleguide](https://communications.princeton.edu/guides-tools/princeton-editorial-style-guide#abbreviations).

**Comment by faithc** [comment]
Thanks, @sdellis. I defer to @ccleeton. :)

**Comment by ccleeton** [comment]
@sdellis Not sure if you saw my response in slack. Moving the FAQs to libanswers works for me. And agree to spelling out AV. I changed the SC website to remove the  / between the words. 
I would be fine to copy the brief statement into the finding aids. Is it possible to do that only in collections where AV is known? @faithc Thoughts?

**Comment by faithc** [comment]
I think @sdellis is asking about the site, not specific finding aids? (ADAPT is planning to replace current AV notes in finding aids with a boilerplate note (once we get the language from public svs) and link to the statement/policy from there.)

**Comment by sdellis** [comment]
@faithc the Statement on Audiovisual Materials seems like something that we might want to include in the Access and Use notes.

**Comment by faithc** [comment]
We do currently have notes for AV materials in finding aids; however, ADAPT and PS recently agreed to change this approach to only having a brief note, something like "see SC's policy on..." with a link out to the statement/policy so that when the policy is revised, which often happens, we're not having to change the finding aid notes.
