### ISSUE TITLE
Updated fixtures are in the wrong repository

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#594]
According to Will Clements, there was a problem with the most recent ArchiveSpace test load and a handful of finding aids wound up in the wrong repository. This is reflected in the most recent Pulfalight fixture update and should be reverted when the ArchiveSpace records are fixed.

Example (should be 'mss' and not 'rarebooks'):
https://github.com/pulibrary/pulfalight/pull/586/files#diff-80c393c8db04e992bc55354420bdc424f2ee2d9f75224926b78c09011e00f640L399

From Will:

> We've noticed a couple of resources that are in the wrong repository, even though the respository id is correct. We happened upon these and so can't be sure how many other resources are affected. Any idea what's causing this and how widespread it might be?
> 
> Examples: 
> WC058 in rare books (should be in mss)
> WC064 in rare books (should be in mss)

> Likewise these: WC001, WC003, WC004, WC005, WC007, WC008, WC009, WC019

**Comment by tpendragon** [comment]
Yeah i talked to them about this a little, we should just be able to regenerate fixtures again for the final test load.
