### ISSUE TITLE
Sylvia Beach Papers Collection Boxes are not indexed properly

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#6]
During the indexing process for the Sylvia Beach Papers Collection, there are containers indexed without titles such as "/catalog/C0108C0108_i1".  I suspect that these are generated from the following:
```
<c level="otherlevel" otherlevel="physicalitem" id="C0108_i181">
    <did>
        <container type="object">1</container>
        <unitid type="barcode">32101080848573</unitid>
        <physloc type="code">mss</physloc>
        <physloc type="text">compartment C, East wall</physloc>
    </did>
</c>
```

**Comment by jrgriffiniii** [comment]
This needs to be reproduced or closed, as this may have been encountered due to the limitations imposed by the previous, Nokogiri-based indexing strategy.

**Comment by tpendragon** [comment]
Indexing and source data are different, aspace containers are more reliable. Closing.
