### ISSUE TITLE
Containers in the Toni Morrison Papers collection have invalid titles

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#60]
This might not be specific to this collection, but the more obvious cases can be found within this. Please see https://plantain-staging.princeton.edu/catalog/C1491C1491_c4622 (indexed as `"'00 /t.Ω:> e lit", 2000 April 18`) for an example of this.

**Comment by tpendragon** [comment]
That's just what the title is, and it's displaying fine. Closing.
