### ISSUE TITLE
Navigation from Component to Collection-Level view results in Request Cart being displayed at the wrong level.

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#609]
If one clicks on any of the collection-level tabs, the `show_default` partial should change to `show_collection` partial. The Request Cart link should not be present on most collection-level views.

Clicking on Access tab in this example should result in the Request Cart disappearing from the page (unless the collection can be requested in full):
https://findingaids-beta.princeton.edu/catalog/aspace_C0543_c002

**Comment by tpendragon** [comment]
There seems to be this expectation that the "collection" tabs pop you back up to the collection. I was under the impression these were just shortcuts for constant information about the collection, and the context of the page (and the only way to navigate away) is always what's reflected in the table of contents, so the buttons at the bottom if you're on the collection tab don't reference the collection, but the component.

**Comment by sdellis** [comment]
I don't think this interface works for what you're suggesting, @tpendragon. Since the collection tab content uses the same content pane as the components, and the buttons on the bottom are visually tied to that pane, the "actions" a user can take via the buttons need to be related to the content in that pane.
