### ISSUE TITLE
transform Aspace output to PULFA

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/pulfalight#623]
for the transition to pulfalight

**Comment by regineheberlein** [comment]
https://github.com/pulibrary/archivesspace-development/tree/main/data-prep/XML_prep/aspace2pulfa

**Comment by regineheberlein** [comment]
* Storage note doesn't display: output is missing `address/@id`
* Languages look funky if more than one: output uses text() not `@langcode`

**Comment by faithc** [comment]
- This data seems to have been added <daodesc><p>View digital content</p></daodesc>. At the least, the text shouldn't display.

**Comment by regineheberlein** [comment]
@faithc can you give me an example?

**Comment by faithc** [comment]
https://findingaids.princeton.edu/collections/WC064/c0017 the text displays under acquisition notes or under the description note if there is no `acqinfo`.

**Comment by faithc** [comment]
I mean, it's minor, but something I noticed and a bit confusing.

**Comment by faithc** [comment]
- For WC064, the collection tabs aren't working; they just bring one back to the site's homepage.

**Comment by regineheberlein** [comment]
Thanks!

**Comment by regineheberlein** [comment]
@faithc What do you mean by "collection tabs"?

**Comment by faithc** [comment]
Sorry, the `descgrp`s: Description, Collection History, Access and Use, etc.

**Comment by regineheberlein** [comment]
Oh--those display for me. Perhaps the tree was still loading when you tried it?

**Comment by faithc** [comment]
Huh, perhaps. That EAD seems to be loading even slower than usual (and it's usually fairly slow). ha

**Comment by regineheberlein** [comment]
All fixed.
