### ISSUE TITLE
Repository info: email address is wonky 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#625]
Are the email addresses supposed to be spelled out as such: https://findingaids-beta.princeton.edu/?f%5Bcollection_sim%5D%5B%5D=&f%5Brepository_sim%5D%5B%5D=Manuscripts+Division&group=true&q=brendan+behan&search_field=all_fields?

**Comment by ccleeton** [comment]
Additionally we are getting away from using the email addresses as the department is trying to have one central ticketing system. Could both email addresses be replaced with a link to the Ask Us form? https://library.princeton.edu/special-collections/ask-us

**Comment by tpendragon** [comment]
@faithc @ccleeton Should every repository email point to that ask us form? They're all here: https://github.com/pulibrary/pulfalight/blob/58dc6481b7c7a28d1648932374c2285e2d1ff386/config/repositories.yml

**Comment by ccleeton** [comment]
Everything EXCEPT Engineering.
