### ISSUE TITLE
Hyperlinks in Access and Use do not link to beta site

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#628]
When looking at the Access and Use Tab here - https://findingaids-beta.princeton.edu/catalog/AC107
Scrolling down you will see Other Finding Aids
These are all linking to the old site.
There are quite a few collections where this is the case. 
Will redirects happen or can these link correctly to the beta site?

Other examples:
https://findingaids-beta.princeton.edu/catalog/AC198
https://findingaids-beta.princeton.edu/catalog/MC001

**Comment by tpendragon** [comment]
These will eventually redirect, yes, as soon as the site goes live.

For now I could maybe mutate them at index time so it replaces findingaids links with their beta equivalents.

**Comment by ccleeton** [comment]
Hmmm, so I am thinking this will come up as a question as we ask staff to use the site so if you could mutate them for now it would be helpful.

**Comment by tpendragon** [comment]
Closing this as these links will work come Monday.
