### ISSUE TITLE
Requests for "/collections/eadid/componentid" should redirect to "/catalog/eadid_componentid"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#639]
This should be pretty easy, and matching up the URL will make replacing findingaids.princeton.edu much easier.

**Comment by jrgriffiniii** [comment]
For clarification, an `eadid` here refers to the finding aid identifier. In cases such as https://findingaids-beta.princeton.edu/catalog/C0101_c013317, `C0101` is the finding aid identifier/EAD ID.

**Comment by jrgriffiniii** [comment]
Component IDs are individual levels of nested archival material items within a collection description. Component IDs are "levels" of archival collection description. For example:

- Archives of Charles Scribner's Sons, 1786-2004, bulk 1880/1979
  - Series 1: Advertising Records, 1917-1964 (large gaps), 1917-1964
    - Subseries 1A: Advertising Records, 1917-1950
    
...where each component leads to a more nested level of description. As each collection description is a tree node, the leaf node for each is typically a level of description which indicates that a physical box or folder is being described.
