### ISSUE TITLE
Aeon Call Slip issue

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#653]
During my testing of the interaction with the finding aids and aeon and the printing of the call slips I found some abnormalities.

In the Box Field it is printing a "Box 1 NBox" for many collections. I have provided a few pictures of call slips I printed here.

![20210205_085343](https://user-images.githubusercontent.com/9676616/107042748-175f3880-6790-11eb-8859-52e5692ed5f1.jpg)
![20210205_085349](https://user-images.githubusercontent.com/9676616/107042770-1d551980-6790-11eb-82af-d7777aee4529.jpg)
![20210205_085339](https://user-images.githubusercontent.com/9676616/107042771-1d551980-6790-11eb-9efc-d5ae5d174177.jpg)
![20210205_085335](https://user-images.githubusercontent.com/9676616/107042773-1dedb000-6790-11eb-9fee-0fbbcc480392.jpg)

**Comment by tpendragon** [comment]
Can you enumerate what the values should be for each of these, which items are being requested, and which parts of the slips are off? I can kind of guess, but I never saw the old slips so I don't know which parts are just display issues that have always been there. 

The NBox thing is because every container has a profile in Aspace now, and Will asked that they display. Should only the types that aren't NBox show up?

**Comment by ccleeton** [comment]
I crossed out the "NBox" part that was never there before. I am not sure where it is coming from. If you can get into the back end of the callslip it works as a mail merge you might be able to see the code of where it is pulling from. 
![20210205_085335](https://user-images.githubusercontent.com/9676616/107062546-6a90b580-67a7-11eb-9876-87963212c0fa.jpg)

**Comment by ccleeton** [comment]
OOOOOHhhh wait i think i get it now. So if this were oversize is would show that. I guess that works, but its not showing on all of them. Also the folder used to display in the Folder not box.

**Comment by faithc** [comment]
Yeah, that's the AbID indicator, @ccleeton, which indicates the size/location of the container.

**Comment by ccleeton** [comment]
Ok so I am good with it for now but it would be really helpful if we could make some size/font changes to the call slip so it prints a bit better. 
Also still not sure why the folder is not printing correctly

**Comment by tpendragon** [comment]
@ccleeton When you get a chance could you check call slips again? The folder bit should be fixed. I'm not sure what exactly else needs changed to close this ticket.

**Comment by ccleeton** [comment]
@tpendragon this one looks good but I did open a new ticket about a new issue. I will close this one.
