### ISSUE TITLE
Display Creator/Collector in their own fields.

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#655]
Should only display once; for example: https://findingaids-beta.princeton.edu/catalog/C0140.

**Comment by tpendragon** [comment]
Yeah this is because they're in the EAD as both creator and collector. Should we make sure not to index collectors?

**Comment by faithc** [comment]
Hmm, it shouldn't be listed in the finding aid as both so perhaps something that needs to be remedied in ASpace? There will be cases when the creator and collector differ so not indexing the collectors wouldn't work.

**Comment by tpendragon** [comment]
I can either put them in different display fields (Collector: yada yada, Creator: yada yada), or I can keep them both in creator and make it so there's only unique strings. Which would you prefer? Also, blocking release?

**Comment by faithc** [comment]
Yeah, I guess display in different fields. Not sure why that data would be in ASpace twice though in this specific case, and whether this might be a larger issue. And no, don't think so?

**Comment by tpendragon** [comment]
Yeah in this case it may be a migration issue. https://aspace.princeton.edu/staff/resources/3950#tree::resource_3950 is the resource (mss repository)

**Comment by faithc** [comment]
Ok, I see. This might need review later on; but yeah, for now I think displaying them in different fields makes sense. Thanks. (And ok, I'm signing off now, dammit! haha)

**Comment by tpendragon** [comment]
@faithc Do you have an example record where this is a problem I can work off of? The one above doesn't have a collector anymore.

**Comment by faithc** [comment]
https://findingaids-beta.princeton.edu/catalog/C1165

(We're gonna be getting rid of the duplicate PUL record, hopefully soon, per some data cleanup work with name records in ASpace.)

**Comment by tpendragon** [comment]
@faithc Collector doesn't seem to display in PULFA 2.0, do we want to display it?

**Comment by faithc** [comment]
It does display in pulfa2: https://pulfa.princeton.edu/collections/C1165. We most often used @ role ="cre" twice rather than using "cre" and/or "col" since "creator" and "collector" really can be used interchangeably/ are kind of the same thing. One entity created the collection, one created the materials. Does that makes sense? Sorry, not being super articulate here. So yes, please display both/all.

**Comment by tpendragon** [comment]
That example is exactly what I needed, thanks!
