### ISSUE TITLE
PUL erroneously showing up as creator/collector 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#659]
I'm noticing that PUL is displaying as a creator/collector, even when this is not the case, for example, personal papers and organizational records. Seems like this has something to do with how EAD data was imported into ASpace. Ex: https://findingaids-beta.princeton.edu/catalog/C1596 Behan is the only creator. Wondering if the repository corpname in the EAD was imported as a creator. 

This relates to #655.

**Comment by faithc** [comment]
Confirmed that this is a data issue; staff are currently looking into it.

**Comment by tpendragon** [comment]
@faithc Does this mean we don't need to do anything? Should we keep this ticket around?

**Comment by faithc** [comment]
Yup, you can close this. Thanks.
