### ISSUE TITLE
Ignore subjects with @type "topical"

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#660]
Staff are no longer using local topic headings; however as of now these headings are still associated with resource records in ASpace. Until they are removed from ASpace, we're wondering if they can not be exported to pulfalight. I believe they can be identified with the @type "topical" value. Trey mentioned that he wasn't sure whether type comes through in the EAD export.

**Comment by tpendragon** [comment]
@faithc Blocking release?

**Comment by faithc** [comment]
No, I don't think so.

**Comment by faithc** [comment]
No, sorry, my thought about how to locate these was totally wrong. I think we may just delete them in ASpace. Closing this issue. Thanks anyway! :)
