### ISSUE TITLE
Landing page image

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#661]
Could the landing page image be changed to this photo - https://drive.google.com/file/d/1XbiRLXORUHx2dpCOBVC89ej_iqZPCGJn/view
If possible we would prefer to not have the students covered by the search bar.

Would it be possible to do this on the staging site first so we can get leadership approval?

**Comment by tpendragon** [comment]
@ccleeton Blocking release?

**Comment by ccleeton** [comment]
I would say yes since the image has been approved by Leadership and Communications. So as long as its done by March??

**Comment by bess** [comment]
@ccleeton Please take a look at https://pulfalight-staging.princeton.edu/ when you get a chance. I'm also pasting a screenshot. What is the process for getting sign off on this?  Thanks!

![Screen Shot 2021-03-01 at 9.59.54 AM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/9d743319-b11c-42ea-b2fe-e9990e98001a)

**Comment by ccleeton** [comment]
Looks good to me. Let me see if I can get approval on this quickly.

**Comment by ccleeton** [comment]
@bess Approved from Sara and Alexis. This can be pushed to the beta site whenever you can.

**Comment by bess** [comment]
Great, thank you, @ccleeton !

**Comment by bess** [comment]
Merged and deployed to beta site!
