### ISSUE TITLE
Location codes display in addition to text 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#678]
For example, see https://findingaids-beta.princeton.edu/catalog/C1387. For the field "Located in," rcpxr and mss, which are values of physloc @code, should not be displaying; just the interpretive text. 

See also info about the physloc element here: https://docs.google.com/spreadsheets/d/1fKd5t9Xk_Ph1MD5zt2O2LwSWfLeNQjBYtDM6fk8qH9k/edit#gid=0

**Comment by faithc** [comment]
Related, the Storage note on the Collection overview page is incorrect; the information in Located in is the correct info. Relates to #683

**Comment by tpendragon** [comment]
@faithc Should there just not be a "Located in" and that should be wrapped up in storage note like the old site?

**Comment by tpendragon** [comment]
OH, nevermind, okay I see what's going on. It's rendering the component display for collections on first load.
