### ISSUE TITLE
Viewer that can nest multiple files under one component

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#680]
Digitized audio in particular -- many components with multiple files (two sides of a cassette, for example)

**Comment by tpendragon** [comment]
The viewer can do this now. It can't mix file types is all, so you can't go from a picture to an audio file.

**Comment by ccleeton** [comment]
This is something that we were looking for for the VRR (virtual reading room) task force. Not blocking but something we need worked on for our deliverables in that group.
