### ISSUE TITLE
2 different collection overview pages showing based on how you search

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#683]
When you search for a collection by name and the landing page takes you to a collection overview that has more information than the collection overview tab. I have included a few screen shots to explain
![collection overview](https://user-images.githubusercontent.com/9676616/108898979-df585200-75e5-11eb-9257-859fadb46bfc.jpg)
![landing page](https://user-images.githubusercontent.com/9676616/108898980-df585200-75e5-11eb-8578-57b18a59792a.jpg)

Both have different information and we don't even know how to get back to it if we navigate off of it.

**Comment by tpendragon** [comment]
I think https://github.com/pulibrary/pulfalight/pull/677 is going to clear this up.

**Comment by ccleeton** [comment]
@tpendragon Will that also fix the storage note on the overview tab? Here it is not showing that some of this collection is at recap.

**Comment by ccleeton** [comment]
@faithc I feel like the storage note should be displaying at the component level too. If a researcher gets to a component via a keyword they are not going to know it might not be onsite.

**Comment by faithc** [comment]
@ccleeton Yes, the collection-level storage note should display with child components as well like it does now. The note also indicates at which location/library materials are stored/accessible; this should continue to display in pulfalight as well. Ex.
https://findingaids.princeton.edu/collections/C1596/c6 vs. https://findingaids-beta.princeton.edu/catalog/C1596_c6.

**Comment by tpendragon** [comment]
Closing this and opening #701 instead.
