### ISSUE TITLE
Collections merging in call slip when the box number and component is same

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#696]
We have had a few instances of the merging of requests into one transaction when the collection information is different. This is seeming to happen when the box is the same and the component is the same but from different collection.
Example: Requesting AC109_c00003; AC168_c00003
This is an issue because we need separate call slips for each collection. 
![merging collections](https://user-images.githubusercontent.com/9676616/109165306-65d97480-7749-11eb-9877-ce4c4da2b5fb.jpg)

**Comment by ccleeton** [comment]
This is another example that Annalee and Rosalba experienced
https://findingaids-beta.princeton.edu/catalog/C0035_c021 and https://findingaids-beta.princeton.edu/catalog/C0230_c021

**Comment by ccleeton** [comment]
It is also adding all of the info to the call slip. 2 barcodes, all that info in the notes field.
[tn 291225.docx](https://github.com/pulibrary/pulfalight/files/6043624/tn.291225.docx)

**Comment by tpendragon** [comment]
Oof. Yeah I just copied all the merging fields to pass to Aeon from PULFA2, but it wouldn't be a problem there because you can't request cross-collection. I'll take a look.
