### ISSUE TITLE
Typographical errors may exist for certain container and component titles

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#70]
Perhaps this preserves the error from the primary material, but cases like `Delpeted` in https://plantain-staging.princeton.edu/catalog/AC230AC230_c56 might interfere with content discovery. Might there be another element in the EAD which is parsed for these?

**Comment by tpendragon** [comment]
Closing as container handling is different now with aspace. We can open another ticket if, once all our data is indexed, we find discovery concerns.
