### ISSUE TITLE
Collection level storage note should display on component pages.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#701]
See https://findingaids.princeton.edu/collections/C1596/c6 vs https://findingaids-beta.princeton.edu/catalog/C1596_c6.

Discovered in #683

This needs to work for Collections that have multiple locations, per @ccleeton 
Collection that has both multiple locations and components needing a Storage Note display: https://findingaids-beta.princeton.edu/catalog/MC076

**Comment by jrgriffiniii** [comment]
`This collection is stored at Firestone Library.` is the collection level note on https://findingaids.princeton.edu/collections/C1596/c6. I am not certain where this is parsed within the XML, but it might already be partially stored into the Solr Document in `location_code_ssm` for https://findingaids-beta.princeton.edu/catalog/C1596_c6/raw

**Comment by bess** [comment]
![Screen Shot 2021-03-02 at 4.35.53 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/0c06ab03-c0b0-4de8-a844-b6801853823b)

**Comment by bess** [comment]
![Screen Shot 2021-03-05 at 4 59 13 PM](https://user-images.githubusercontent.com/65608/110336075-8380c680-7ff2-11eb-9552-d5b86454acd1.png)
