### ISSUE TITLE
Develop workflow to add finding aids to PACSCL's finding aids website 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#709]
There is currently a workflow for automatically sending EADs in SVN to PACSCL's web folder to include Princeton's finding aids on their [website](http://dla.library.upenn.edu/dla/pacscl/index.html). @regineheberlein and @escowles likely know the most about the current workflow and how it might be revised to work with ASpace exports. I marked this as MVP, though not blocking release, since this is something that happens currently, similar to MARC record generation. 

## Things we know:

Every finding aid is run through XSLT, the equivalence of which for ASpace is (thanks @regineheberlein ) the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ead="urn:isbn:1-931666-22-9"
  exclude-result-prefixes="xs"
  version="1.0">
  
  
  <xsl:template match="@*|node()">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>
  
  <xsl:template match="ead:dsc//ead:container"/>
  
</xsl:stylesheet>
```

That process runs on a cron job on the PULFA box and then those files are shared at https://pulfa.princeton.edu/pacscl/.

## Implementation Proposal

I just spoke to @magibney who says their harvester just grabs every XML link on a page and downloads it.

So my proposal is the following:

* Implement and close #107 

* Add a path to download the XML for a finding aid but without containers.

* Implement `/pacscl/production` to just show a link to every finding aid's XML without containers. The links have to end in ".xml"

No cron jobs!

**Comment by escowles** [comment]
I'm not sure I know the details, but I think the main processing we did for our EADs was to remove the DSC[2] — does that sound right?

**Comment by faithc** [comment]
I believe so.

**Comment by escowles** [comment]
👍🏻 this seems much simpler than exporting them periodically, and having to setup a static content directory and cron job.

**Comment by regineheberlein** [comment]
Much better! Thanks @tpendragon !
