### ISSUE TITLE
Clear division is needed when there are bioghist notes for multiple creators 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#718]
When there are two (or more) creator agents attached to a resource record there needs to be a clear division between the notes for each creator. See for example: https://findingaids-beta.princeton.edu/catalog/C0292#description. 

# Technical implementation

* Update our aspace plugin (https://github.com/pulibrary/princeton_ead_exporter) to export bioghistnotes with links to the agents that they're for.
* Index notes alongside the user they're for in some sort of JSON structure for display.
* Display the user alongside the note.

**Comment by tpendragon** [comment]
This is tough. A few options I've come up with so far:

Indent:

![Screen Shot 2021-03-16 at 2 50 16 PM](https://user-images.githubusercontent.com/2806645/111384608-f0d1ce80-8666-11eb-8f75-ad49c0950dc1.png)

Horizontal Rule:

![Screen Shot 2021-03-16 at 2 51 26 PM](https://user-images.githubusercontent.com/2806645/111384781-1d85e600-8667-11eb-891c-06df3ed798e0.png)

Bullets:

![Screen Shot 2021-03-16 at 2 52 31 PM](https://user-images.githubusercontent.com/2806645/111384896-43ab8600-8667-11eb-8e22-96049223ce65.png)


I'm not a huge fan of any of them, personally. Thoughts, @sdellis ?

**Comment by tpendragon** [comment]
For personal reference, work is here: https://github.com/pulibrary/pulfalight/tree/separate_bioghist

**Comment by faithc** [comment]
Hmm, if I had to choose, I'd say maybe the horizontal rule? Would it be possible to add the name of the creator with whom the bioghist is associated as a header before the note? Also curious what @sdellis thinks. 

Wonder if this is something we'll be able to improve even more once we begin to review name record integration in the site generally?

**Comment by tpendragon** [comment]
We can associate the creator with the bioghist if we find an attribute tag to put in the bioghist in which to put the person it's in relation to in the EAD. I assume there's no way to do that in valid EAD? @regineheberlein ?

**Comment by faithc** [comment]
We had been doing this actually using the ptr element, but had to abandon it per the aspace migration.

**Comment by tpendragon** [comment]
That might be possible, I'll have to fiddle with the plugin again.

**Comment by regineheberlein** [comment]
Yeah, we did an ugly mixed-content hack where we added a <ptr target="C001_b1"/> to the value of the name tag, and then gave the corresponding bio an id <bioghist id="C001_b1">. Those hooks were lost in the migration, which is ok, since we migrated the bioghists to the Agent records in ASpace wherever possible, so they are associated. We'd have to reconstruct that or a similar hook/hack on export if we want to go back to that association in EAD.

**Comment by tpendragon** [comment]
This is gonna be harder than some other higher impact things in on-deck, so I'm gonna put this back into ready.
