### ISSUE TITLE
Allow front page to load even if solr is down

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#72]
It seems like we should still be able to serve the front page of the app. Perhaps with a flash or other warning that searching will be broken.

**Comment by tpendragon** [comment]
Solr's much more stable since we made this ticket, and it would be pretty difficult and be in direct confrontation with features like showing recently added items. Can we not? What do you think @hackartisan @jrgriffiniii ?

**Comment by hackartisan** [comment]
I still want this. I think it's nuts for the front page of a site to go down because a service it uses is down. I think we could get around it when implementing those features.

I agree it's lower priority than it was before. I wonder if it's something we could look to do upstream.

**Comment by tpendragon** [comment]
I'd like to at least pull this out of MVP. It's definitely a new feature when compared to the old site. Acceptable @hackartisan?

**Comment by hackartisan** [comment]
Yep!

**Comment by escowles** [comment]
When OL or Pulfalight are down, the Library bento search fails gracefully e.g., displaying "Catalog results are not available at this time."

**Comment by tpendragon** [comment]
Our uptime is very high, closing.
