### ISSUE TITLE
Biographical/historical notes do not always appear in finding aids 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#731]
For newly published Resources in ASpace, the biographical/historical note from the linked Creator Agent record is not showing up in the finding aid on PulfaLight for some records (C1667, C1657) but it is for others (C1661).

**Comment by tpendragon** [comment]
Hm, it seems likely this is a timing issue. It may be that because indexing new resources every hour aspace hasn't finished indexing the agent when we pull the EAD. I'm not sure if we'd need to index less often (nightly again, probably) to fix or if there's some other way to handle this.

**Comment by faithc** [comment]
Ah. Could indexing perhaps happen somewhere in between every hour and nightly?

**Comment by tpendragon** [comment]
If it's solely a timing issue then probably not - there's always the chance that during the day our scheduled time would coincide with when the record was edited recently. I can look into seeing if we can schedule a "double-check index job" or something, or if maybe we can track changes for agents and see if when they change we can reindex attached EADs.

**Comment by faithc** [comment]
Thanks, Trey.

**Comment by tpendragon** [comment]
@faithc 

Oh wow, this is pretty bad UX in aspace. I'm sure it has a reason, but yeah.

Okay, so it's a user entry issue that I also would have done. The agent for C1667 has a bioghist note which is published, but the sub note (which has the actual content), is NOT published. If you edit the agent and check that box it should reindex with the bioghist.

![Screen Shot 2021-03-09 at 2 56 44 PM](https://user-images.githubusercontent.com/2806645/110549963-b5c02000-80e7-11eb-90aa-fb6a4f0586b5.png)

**Comment by tpendragon** [comment]
@faithc Can I close this?

**Comment by faithc** [comment]
Sure. Thanks again for figuring out what the issue is. And now I'm mad at ASpace...haha
