### ISSUE TITLE
Map data in container locations note to Aeon + display on call slips

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#744]
Data that was just added to the top container locations note (container_location note) in ASpace needs to be mapped to Aeon and appear on call slips as it provides additional info that allows staff to know where an item in located in the stacks. This data had been mapped to Aeon previously; in EADs, it's the physloc @ type "text" note.

**Comment by regineheberlein** [comment]
E.g.
```
"container_locations"=>[{"jsonmodel_type"=>"container_location",
"status"=>"current",
"start_date"=>"2020-11-10",
"note"=>"this is a test",
"system_mtime"=>"2020-11-10 18:00:59 UTC",
"user_mtime"=>"2020-11-10 18:00:59 UTC",
"ref"=>"/locations/16979"}]
```

**Comment by tpendragon** [comment]
Current plan: Store this in `container@note` and index it. Will have to update the aspace plugin.

**Comment by tpendragon** [comment]
The plugin's updated and I've contacted Lyrasis, this issue is blocked until they get our updates into our ASpace instance.

**Comment by regineheberlein** [comment]
So fast! Thank you!
