### ISSUE TITLE
Outdated terminology

### ISSUE THREAD

**Issue by escowles** [pulibrary/pulfalight#751]
Received feedback:
> Unfortunately, when I tried this out the first issue that I saw was that collection requests “will be delivered to Manuscripts Division, RBSC Reading Room”. There is no Manuscripts Division nor does the RBSC Reading Room exist.

**Comment by tpendragon** [comment]
@faithc @ccleeton Do you know where this would be? I'm not seeing it anywhere - I think this used to be in the storage note in PULFA2? Maybe this was feedback for the wrong site?

**Comment by ccleeton** [comment]
Um, what?
I feel like I need more context of where this came from.

**Comment by faithc** [comment]
I'm confused.

**Comment by faithc** [comment]
Oh yeah, they're looking at pulfa2...

We should have put "end of day Monday" and "next week" in bold and all caps...

**Comment by faithc** [comment]
We can close this issue.

**Comment by tpendragon** [comment]
Closing.

**Comment by escowles** [comment]
Thanks @faithc !
