### ISSUE TITLE
Oversize folders should create a transaction in aeon per folder if there's multiple folders in a component

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#755]
AC154_c03425 should create three transactions, one per folder.

Unfortunately ASpace isn't embedding the extra container information for those child containers to the EAD, so we'll have to update our plugin.

**Comment by ccleeton** [comment]
Oversize folders are considered a top container

**Comment by faithc** [comment]
Just to clarify, oversize folders, like boxes, are top containers and should be managed in the same way.

**Comment by hackartisan** [comment]
In the example given, "Folder Oversize" is the location and we should be able to use that string to know it's an oversize folder. The info needed is folder, cabinet, and drawer -- all part of the top-level container.
