### ISSUE TITLE
Search results/relevancy still need some tweaking

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#756]
From a library colleague:

I just did what everyone does: trying to find the record one is used t use. In the old one, type gest library. The very first result is the one one would need: series 17, admirable represented, how the boxes relate to each other. https://findingaids.princeton.edu/collections/AC123/c9365, with 4 subsets. Exactly how it should be.

In the new site? Type Gest Library, and one gets a hotch potch of folders, not the above, and it took me quite some time to even find a box part of the above set. Only because I knew what I was looking for, I realized I should select one box, and then use the links there to get an overview of series 17, and get the above presentation. Perhaps I did something wrong, but I found the old one, where the organization of the files is the primary record given to the user, much better.

**Comment by tpendragon** [comment]
We made the decision in Pulfalight to weight titles more heavily, meaning exact matches for "Gest Library" in the title will float to the top. Closing this ticket would require weighting series higher than everything else as long as there's any match at all, potentially pushing out good component matches. As such, we're going to mark this #wontfix.

For reference, the only reference to Gest Library in that series is the description. Searching for "Gest Library Records" actually makes Series 17 show up as the third result, and searching for "East Asian Library Records" results in it being the first result.
