### ISSUE TITLE
Physical Description not appearing

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#776]
The "Physical Description" field is not showing in Plight as it did in 2.0 
This is helpful to note the type of item especially in cases that it is Audio Visual.
Example:
https://pulfa.princeton.edu/collections/C1491/c5239 
https://findingaids.princeton.edu/catalog/C1491_c5239

## Implementation Notes

Index and display `physdesc/physfacet` with the label "Physical Description"

**Comment by phoebeno** [comment]
another example, would like the "phystech" to display: 
https://findingaids.princeton.edu/catalog/AC317_c42486-98902.xml

https://findingaids.princeton.edu/catalog/AC317_c42486-98902

**Comment by tpendragon** [comment]
Yup looks like we don't have this one indexed - we need `physdesc/physfacet` with the label "Physical Description" I think.

**Comment by tpendragon** [comment]
@phoebeno What do you want the label for "phystech" to be? "Physical Characteristics and Technical Requirements"?

**Comment by phoebeno** [comment]
Hi Trey,

Looks like phystech is already displaying as “Special Requirements for Access”, which is fine, and Faith says that “physfacet” should display as “Physical Description”.

Good?

Phoebe
