### ISSUE TITLE
Access notes are showing up twice on Aeon call slip

### ISSUE THREAD

**Issue by sdellis** [pulibrary/pulfalight#782]
Currently, it's a dupe of the Access notes (or perhaps a cascade of collection vs. component access notes?) That should be removed from the general Notes field at the bottom of the call slip, and replaced with the note the user supplies with their request.

![C1491 call slip 1](https://user-images.githubusercontent.com/609368/112682006-defde180-8e45-11eb-87ba-0787b5fa9e4d.jpg)

**Comment by tpendragon** [comment]
@ccleeton Can we get an example of a record that builds these duplicate access notes?

**Comment by tpendragon** [comment]
@ccleeton confirmed this is fixed.
