### ISSUE TITLE
[PULFALight/production] URI::InvalidURIError: bad URI(is not URI?): "/catalog/MC121|Walter"

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#783]
When parsing an eadid and component id, we need more processing.
- [x] Drop anything after a pipe (|) in the eadid
- [x] Drop anything after a space in the componentid

Another example of an erroring component id:   "componentid" => "c00003 Scheduled Date"

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/78580571)

**Comment by tpendragon** [comment]
The instances of this have all been bad links by bots attempting to break things. Closing, ignoring in honeybadger.
