### ISSUE TITLE
Workflow to export finding aids to ArchiveGrid 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#786]
I'm copypasting an email from Bruce Washburn at OCLC. We'll need to create a new workflow to include our finding aids in ArchiveGrid. This was not even on my radar. :/ 

"I work in the OCLC Research division and operate its ArchiveGrid discovery system, which includes in its index archival material descriptions obtained from WorldCat as well as finding aids harvested from contributing institutions’ websites.

I have a question about an issue with retrieving EAD XML finding aids from the Princeton University Library website and wondered if you could answer it, or direct me to someone who could assist me.

For the past several years, Princeton has provided access to RDF XML files that included links to EAD finding aids, which I would use to harvest and index the files in ArchiveGrid.  I think this configuration was established by Dan Santamaria, quite a while ago, prior to his departure from Princeton.  Here’s an example URL for one of the RDF XML link files: https://findingaids.princeton.edu/catalog/eng.rdf

These links are no longer resolving, and I wondered if there was a way to either reinstate them or to provide another path that the ArchiveGrid web harvester could follow to retrieve and index the EAD XML documents." 

@regineheberlein Do you (or do you think Jon or DT) happen to know what the former workflow was? Thinking that will help inform how it's revised?

**Comment by tpendragon** [comment]
:joy: Do we have to support this quickly? It looks like the way this worked was (deconstructing the logic):

Every repository has an RDF link (https://pulfa.princeton.edu/collections/eng.rdf), which points to every collection page. Presumably after that they'd harvest the XML EAD of those links (IE https://findingaids.princeton.edu/collections/MC124.xml)

We'd have to close #107 first, for sure, and then I guess re-implement that RDF link page.

**Comment by faithc** [comment]
Ahhh, yeah, I had zero clue how this was happening. Ha And I don't think it's urgent. #107 is definitely more pressing. :)

**Comment by regineheberlein** [comment]
I think the workflow was entirely on their end (I didn't even know they were harvesting! Way cool!), with the exception of the content negotiation piece to provide the rdf, or am I missing something?

**Comment by escowles** [comment]
@faithc Now that we have a solution in place that works for PACSCL, do you think it would be worth asking if it would also work for ArchiveGrid? I find it hard to believe that RDF in the format that PULFA produced was actually useful beyond just being a list of links.

**Comment by faithc** [comment]
Sure, @escowles. Would you or Trey want to contact Bruce (washburb@oclc.org), or I can copy you in a response to him per the email chain I was looped into? I'm not sure I'd be able to explain what the PACSCL workflow is to see if that would work for OCLC as well.

**Comment by escowles** [comment]
@faithc Can you forward the email to me? I'm happy to respond to Bruce and give a brief explanation of how the PACSCL feature works.

**Comment by faithc** [comment]
Yup, will do. Thanks, @escowles!

**Comment by escowles** [comment]
Bruce reported that he was able to use the PACSCL feature to index our finding aids, so I'm going to close this issue. Here's our finding aids in ArchiveGrid: https://researchworks.oclc.org/archivegrid/?q=contributor:462&sort=title_sort+asc
