### ISSUE TITLE
Error going to /catalog/suggest

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#794]
[PULFALight/production] RSolr::Error::Http: RSolr::Error::Http - 500 Internal Server ErrorError: {  "responseHeader":{    "zkConnected":true,    "status":500,    "QTime":0},  "error":{    "msg":"suggester was not built",    "trace":"java.lang.IllegalStateException: suggester was not built\n\tat org.apache.lucene.search.suggest.analyzing.AnalyzingInfixSuggester.lookup(AnalyzingInfixSuggester.java:555)\n\tat org.apache.lucene.search.suggest.analyzing.AnalyzingInfixSuggester.lookup(AnalyzingInfixSug...

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/70813592)

This seems to be some sort of issue around requesting the suggest while the core is rebuilding.

This won't show to the user, and auto suggest likely has changes coming to it in the future as per #499 

## Potential Fix

A deploy of pul_solr to lib-solr8-prod will probably fix this.

**Comment by ccleeton** [comment]
@hackartisan is this still an issue?

**Comment by hackartisan** [comment]
doesn't look like it, thanks!
