### ISSUE TITLE
Right clicking a item in the Contents and Arrangement does not open to page that is representative of that click

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#798]
Example: https://findingaids.princeton.edu/catalog/C0159
If I right click on Signed Typescript in the contents the expected action is that it would open that component in a new tab. It currently just reopens the same screen.

**Comment by faithc** [comment]
This worked when I tried it, @ccleeton, i.e. right-clicked and selected "open in new tab"? Curious if this is a common use case?

**Comment by ccleeton** [comment]
That is so odd @faithc , I just tried it again and nothing. Are you using a Mac? and what browser?

**Comment by faithc** [comment]
Weird. I'm using a Mac and Firefox.

**Comment by ccleeton** [comment]
Well in any case this for me is not a top level issue and can wait. Seems like a browser issue possibly.
