### ISSUE TITLE
Ampersands in scopecontent are escaped out of ASpace, but not unescaped at index time.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#806]
![Screen Shot 2021-08-26 at 3 00 48 PM](https://user-images.githubusercontent.com/65608/131020888-11d86da5-d049-4874-b087-6c95623c1fa4.png)

See scope content note for https://findingaids.princeton.edu/catalog/C0140_c83445-31032 (Under "Description")

## Note

ASpace complains about ampersands, but it'll output &amp;. If we can't figure out the nice way to just decode all the special characters (because some may not be encoded), then just replace `&amp;` with &.

**Comment by faithc** [comment]
I think this issue extends beyond scope and content notes?

**Comment by tpendragon** [comment]
@faithc It looks like the above record got fixed. Do you have a broken one somewhere?

**Comment by faithc** [comment]
I think this is because Kelly had just decided to use "and" rather than "&amp;" to avoid the issue. I just switched it back to the latter (since that's still what ASpace expects; hopefully they resolve this soon); the issue remains.

**Comment by tpendragon** [comment]
Thank you!

**Comment by faithc** [comment]
I used "&" rather than "&amp;" in the description note for this record ("...care of Messrs. Spottiswoode & Co. Ltd,...") and it is still displaying "&amp;" in pulfalight: https://findingaids.princeton.edu/catalog/C0140_c51395-47892.
