### ISSUE TITLE
display physical location of Top Containers in finding aid

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/pulfalight#807]
![Screen Shot 2021-09-01 at 4 14 05 PM](https://user-images.githubusercontent.com/65608/131742289-c5eb570f-7157-43fc-a521-8dba68095fd3.png)

An instance of how we have collated this information manually in the past at the collection level, see physloc text note: https://findingaids.princeton.edu/catalog/C1491
Other examples look like this: 
•	AC154   Boxes 87 through 97 (Series 2: Architectural Drawings, Microforms), are stored offsite.
•	AC161   Boxes 42-50 (Series 8) are stored offsite.
•	AC180   Boxes 30 through 103 (Series 5: Audio, Motion Picture and Video Recordings) of this collection are stored offsite.
•	AC195   Boxes 234 through 384 of this collection are stored offsite.
•	AC297   This collection, with the exception of Box 1, is stored offsite.
We wonder if we can get this kind of information on the Top Containers and make it visible to researchers--at the component level (Christa notes that call slips also print MULTIPLE locations, rather than just the correct one for the box on the call slip)--but also at the collection level, in some kind of listy generated note.

## Reminder:

This is the magic one.

**Comment by tpendragon** [comment]
## Development Notes

At index time of a collection we should be able to grab all `<container>` nodes within the collection, group by `altrender`, and generate some sort of descriptive string from that. Maybe something like "This collection is stored in multiple locations. Firestone Library Vault: Boxes 1-11; 13-19; 22-29; 32-47; 50-56;, ReCAP: Boxes 1-11; 13-19."

**Comment by faithc** [comment]
Awesome! And just to clarify, at the collection level, this information should display as the Storage note.

**Comment by tpendragon** [comment]
Attempted to do this once in https://github.com/pulibrary/pulfalight/pull/849, but https://findingaids.princeton.edu/catalog/C0280_c0005 should have displayed "Folder 1" and no longer was. No folders were displaying for any resources (folders don't have locations, so they're not in container_information)
