### ISSUE TITLE
Collections with "Item Numbers" are not displaying

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#812]
We have 2 collections as example for this issue.
You will see here - https://pulfa.princeton.edu/collections/C0704/c2768 there is an individual item number for the component. That item number is not displaying in Pulfalight - https://findingaids.princeton.edu/catalog/C0704_c2768
2nd example - https://pulfa.princeton.edu/collections/AC362/c01738 vs https://findingaids.princeton.edu/catalog/AC362_c01738

## Technical Implementation

Display `unitid_ssm` in component display with the label "Item Number"

This field should also be in the Aeon Request in ItemVolume. This example's ItemVolume should be "Item Number: 5795 Box 182"

Relevant line:

https://github.com/pulibrary/pulfalight/blob/740604e22dfc81a805dc89efdc556a30e0e10ea5/app/values/aeon_request.rb#L64

**Comment by faithc** [comment]
Looks like the Component Unique Identifier ASpace field or unitid element is not displaying. This info will need to be sent to Aeon/visible on call slips, correct @ccleeton?

**Comment by ccleeton** [comment]
Yes it will need to be on the call slips.

**Comment by ccleeton** [comment]
Is there the ability to switch the item number and box number so that it views "Box 182 Item Number: 5795"

The other way is causing some confusion when paging.
