### ISSUE TITLE
Labels for description notes should display for collection records

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#817]
Data/headings that are added to the Label field in multipart notes are not displaying in pulfalight. For example, the Processing Info Conservation note in this mss repo resource record: https://aspace.princeton.edu/staff/resources/4187/edit#tree::resource_4187 does not display as such: https://findingaids.princeton.edu/catalog/C1664#collection-history. Generally, label headings in ASpace should export; rather than the default heading. 

## Technical Implementation

We store the headings in a `processinfo_heading_ssim` etc. Prefer those headings. For instance, the second processinfo note in this example should have the heading of "Conservation"

## Example of Collection Record

https://findingaids.princeton.edu/catalog/TC040#description

This should have a Content Warning header.

**Comment by tpendragon** [comment]
It seems like people who do this are defining custom ViewComponents, but I don't think Arclight uses that Blacklight release yet.

**Comment by ccleeton** [comment]
@tpendragon Can you let us know if this is still blocked? If so we will take it out of the list.

**Comment by tpendragon** [comment]
I'd consider it still blocked, yes.

**Comment by faithc** [comment]
Dang it. Any idea when ArcLight might adopt the Blacklight release that allows for this? (If I'm understanding your previous comment.)

**Comment by tpendragon** [comment]
Oh, it looks like maybe they do have it now - we'd have to update Arclight. If this is a high priority you can keep it on deck, but be forewarned that it's going to be hard.

**Comment by tpendragon** [comment]
The example given still doesn't have the right headings, even though it worked in staging and some others are working.

**Comment by tpendragon** [comment]
Oh, yes it is, I must have had it cached.

**Comment by faithc** [comment]
Out of curiosity, could this functionality be applied to Dates as well as notes fields? We typically use the "creation" label, but may also use others as appropriate from ASpace's drop-down menu as appropriate. Would I need to create another ticket for this? Thanks.

**Comment by hackartisan** [comment]
@faithc yes a new ticket please thank you!

**Comment by faithc** [comment]
This functionality is not being applied at the collection level as it should be. Please see for example, the [description note here](https://findingaids.princeton.edu/catalog/TC040#description) does not include the "Content Warning" label even though it's employed in ASpace: https://aspace.princeton.edu/staff/resources/2543#resource_notes_  (mss repo)

**Comment by tpendragon** [comment]
@faithc I think this is only a problem for scopecontent and it's because we told it to use a special collection description Field. If I change it to use scopecontent it'll look like this, is that okay @faithc ?

![Screen Shot 2023-07-03 at 3 36 45 PM](https://github.com/pulibrary/pulfalight/assets/2806645/3d6c56d1-cc3c-41f7-b598-40371f404d18)

**Comment by faithc** [comment]
Do you mean the header/label would read "Scope and Contents" as opposed to "Description," which is what currently displays?

**Comment by tpendragon** [comment]
@faithc Yes

**Comment by faithc** [comment]
I think that should be ok. Thanks.

**Comment by faithc** [comment]
I'm still not sure I totally get the logic behind it. You're saying that any scopecontent note currently gets a "description" header applied to it. Would it be too complicated to say to use "description" unless the "content warning" label exists? I don't think it's a huge deal either way. I just want to make sure I understand how these headers are currently being applied. Thanks.

**Comment by tpendragon** [comment]
> I'm still not sure I totally get the logic behind it. You're saying that any scopecontent note currently gets a "description" header applied to it. Would it be too complicated to say to use "description" unless the "content warning" label exists? I don't think it's a huge deal either way. I just want to make sure I understand how these headers are currently being applied. Thanks.

In components we're taking the header that's in ASpace always, for collections we're not splitting out headers at all - all scopecontent notes are getting the "Description" header. I'm saying it would be easy to make collections take the headers always, but then it'll say whatever the header is in ASpace instead - in this case, "Scope & Contents" instead of "Description"

**Comment by faithc** [comment]
Ah ok, gotcha. Thanks!
