### ISSUE TITLE
PACSCL Repository showing up as "Manuscripts Division", "Public Policy Papers", and "University Archives"

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#825]
We may want to adjust the EADs we export to PACSCL to have the repository name prefixed by Princeton University Library.

http://dla.library.upenn.edu/dla/pacscl/browse.html?browse=repository_facet&fq=name_facet%3A%22Princeton%20university%22

## Success Criteria

EADSs pulled from https://findingaids.princeton.edu/pacscl/production have

```
<repository>
      <corpname>Princeton University Library: Public Policy Papers</corpname>
</repository>
```
instead of just `Public Policy Papers`

## Sudden Priority Justification

PACSCL is about to launch a new interface publicly with a bunch of press, and our materials aren't clearly attributed.

**Comment by tpendragon** [comment]
Example: "Princeton University Library: Manuscripts Division". When we change this ping @magibney to give them a heads up.

**Comment by faithc** [comment]
@tpendragon - my colleague at Penn reached out about this issue again as the new PACSCL site will be going live soon and will likely be getting some publicity. Could I put you in touch with Penn's new IT person overseeing the site to see if this issue can be resolved? (Michael Gibney is no longer at Penn.) 

Assuming this is a related issue, but Princeton's name doesn't display on the site's list of repos: https://findingaids.library.upenn.edu/repositories.

Thanks.

**Comment by tpendragon** [comment]
@faithc Sure, please do.

**Comment by faithc** [comment]
Thanks!

**Comment by tpendragon** [comment]
@faithc `Princeton University Library: Public Policy Papers` or `Princeton University: Public Policy Papers`?

**Comment by faithc** [comment]
The former please.
