### ISSUE TITLE
Error in record show in search results.

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/pulfalight#826]
April Armstrong reported that a [search within the site](https://findingaids.princeton.edu/?f%5Bhas_direct_online_content_ssim%5D%5B%5D=online&group=true&q=Helen+Zia&search_field=all_fields) gave a result where the link to one of the results resulted in an error

https://findingaids.princeton.edu/catalog/AC465_c69/track?counter=0&search_id=1303510

Esmé noted that the "track" part is something that we add via JavaScript and perhaps that was the problem. We could not replicate the issue:

```
i see the track  URL in a data-context-href property, and the actual working URL in the href element — 
so maybe there is javascript that's malfunctioning that's intending to track links?

<a data-context-href="/catalog/AC465_c69/track?counter=0&amp;search_id=1303885" 
href="/catalog/AC465_c69">Zia, Helen (Class of 1973), 2017</a>
```

**Comment by escowles** [comment]
Looks like Blacklight is adding that: https://github.com/projectblacklight/blacklight/blob/master/app/helpers/blacklight/url_helper_behavior.rb#L89

**Comment by tpendragon** [comment]
We haven't seen this in a while, seems like a JS malfunction that has since been fixed.
