### ISSUE TITLE
Evaluate and improve the testing for the EAD indexing using RSpec

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#84]
The EAD indexing for Plantain isn't thoroughly tested, and providing more granular tests which ensure that the XML transformation is valid at the element level would be ideal.

Useful files:
 - [Traject config](https://github.com/pulibrary/plantain/blob/master/lib/plantain/traject/ead2_config.rb)
- [EAD XML fixture](https://github.com/pulibrary/plantain/blob/master/spec/fixtures/ead/mudd/publicpolicy/MC221.EAD.xml)
 - [Existing Traject rspec test](https://github.com/pulibrary/plantain/blob/master/spec/features/traject/ead2_indexing_spec.rb)

**Comment by tampakis** [comment]
Checklist of tasks:
 - [ ] Write a test that asserts the `title_teim` field contains the fixtures unittitle value
 - [ ] Write a test that asserts the `title_filing_si` field is missing from the Traject output for the fixture.
- [ ] Test that the [YearRange normalizer(https://github.com/pulibrary/plantain/blob/1370d5b959e3cf0b968f20b3c8df8af8c10aac32/lib/plantain/year_range.rb) works. The value is used in the `date_range_sim` field.
- [ ] Test the output of the `normalized_date_ssm` field.
- [ ] Test that the `normalized_title_ssm` field includes a combination of the `title_ssm` with the normalized date.
