### ISSUE TITLE
Location code data source for Aeon/call slips 

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#865]
Location info that is passed onto Aeon/shows up on call slips should come from the Top Container location, not physical location notes in Resource records. 

@ccleeton tagging you here in case there are possible issues I'm overlooking with this.

**Comment by tpendragon** [comment]
@faithc Can you provide an example of a record that's putting the wrong location in, and what it should be?

**Comment by faithc** [comment]
I'm going to close this for now as the issue hasn't been able to be replicated.
