### ISSUE TITLE
Implement the design for the Expanded Collection View defined by the Summer 2020 wireframes

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#89]
This should enable users to be able to perform a CTRL+F browser-based search for a string for content within any given component. *This should be supported for all finding aids in the app.*

If a user is in a show page for a component, they should be able to navigate to the single-page view of the Finding Aid.

**Comment by jrgriffiniii** [comment]
ArcLight does not come with this out of the box, hence, we are going to need to implement an entirely separate view for this.

**Comment by jrgriffiniii** [comment]
This is termed as the "expanded view" in the design documents.

**Comment by jrgriffiniii** [comment]
This also ensures that users can use in-browser search (CTRL+F) in order to search within the finding aids.

**Comment by jrgriffiniii** [comment]
Please see https://xd.adobe.com/view/c3b49814-866d-449f-44e7-2479ff0cbb30-b585/screen/7366cbcf-3a86-41ae-86e6-432e3d1e35b6 for the design of this interface.

**Comment by tpendragon** [comment]
Closed by #435
