### ISSUE TITLE
Born-digital content should be supported

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#90]
Currently born-digital media is not supported in PULFA 2.0, there are methods for accessing the content on the  Isilon. Systems staff, for certain content, can provide access to content currently stored on hard-drives, but the hope is that there will be, in the future, a platform dedicated to storing and providing access for this.

Arkivum will help manage this content and provide access for PDF content, but how audiovisual media is to be accessed remains to be determined at this time.

**Comment by tpendragon** [comment]
We have VRR and OARSC. No solid use cases yet that's different, closing.
