### ISSUE TITLE
Display ranges for consecutively-numbered containers with AbIDs

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#901]
Top containers with AbIDs are currently displaying separately rather than as ranges when there are consecutive numbers. See for example https://findingaids.princeton.edu/catalog/C1643.  

Related to #897 (storage notes)

**Comment by m-ichelleliu** [comment]
More examples:
https://findingaids.princeton.edu/catalog/LAE006
https://findingaids.princeton.edu/catalog/C1513

**Comment by m-ichelleliu** [comment]
Hi @faithc, there are a couple things regarding the storage notes that I'm curious about:
1. What do the letter prefixes mean in front of the boxes? (e.g. C1513 has P-000100; B-001168; L-000023)
2. Why do the majority of collections have storage note "Boxes 1-n" (where n is the number of boxes in the collection), while the collections that would be affected by this ticket (e.g. C1513 and C1643) have storage notes with box names that are much longer and don't always start from 1?
Thanks for your time!

**Comment by faithc** [comment]
Hi @m-ichelleliu- 

1. The prefixes designate location areas in our onsite stacks. 
2. We use two different numbering systems for boxes depending on their location: AbID (those with prefixes) and traditional numbers. We only began using AbID a few years ago. 

Please let me know if you have any additional questions.
