### ISSUE TITLE
Automatically pull all locations from top container records

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#904]
Staff request that all locations from top containers be automatically pulled so that they no longer have to manually add physical location notes/codes at the collection level. Currently, if there's no code at the collection level the location defaults to rbsc.

**Comment by tpendragon** [comment]
## Implementation Notes

This is the physloc_code. The goal is to make the Site value sent to aeon be determined by the top container locations.

**Comment by faithc** [comment]
Per info Will just shared, it seems like this isn't possible due to how MARC records will be generated from ASpace, correct? @tpendragon If so, we can close this issue.

**Comment by tpendragon** [comment]
I'm not sure? I'd need to know more about the MARC records from ASpace strategy being talked about here.

**Comment by faithc** [comment]
Ahh, sorry. For some reason I assumed you would have been a part of the most recent conversation. Basically, we need to have that note/those codes at the collection level. So I think it's safe to say that we can delete this ticket/that this request is no longer valid.

**Comment by tpendragon** [comment]
@faithc Sounds good.
