### ISSUE TITLE
Links to Original volumes for Board of Trustees Minutes needs to be updated to migrated content in figgy

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pulfalight#921]
We have figgy ids for all volumes of the board of trustees minutes that have been migrated from the PUDL to Figgy, but all of them are still showing the link to PUDL instead of the viewer.  They probably need to have the PUDL link removed from ASpace as well.   [spreadsheet] @escowles added information to (https://docs.google.com/spreadsheets/d/1gPiRwISKJXfT5TQUxqgVlbpoRYDQ1M4VE5y8EK6ZXlY/edit?usp=sharing) for your reference.

**Comment by escowles** [comment]
After removing the existing DAOs and resyncing the objects, they are all showing up now.
