### ISSUE TITLE
Accessrestrict notes aren't inheriting from their parent, but from the root instead.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#924]
https://findingaids.princeton.edu/catalog/MC147_c07283-24964 should have pulled its accessrestrict note from its series, but it grabbed it from the collection instead. 

I think https://github.com/pulibrary/pulfalight/blob/fd732501daaa487df4bf0b1747d5bf41f214709a/lib/pulfalight/traject/ead2_component_config.rb#L572 should be `settings[:parent]` instead of using the clipboard, but it will need a test.

**Comment by phoebeno** [comment]
Yes, true. At the moment we don't want to add component-level restriction notes as a temporary fix, as that could mess with the cleanup Regine is doing. So the restrictions will be incorrect on the finding aid above for a while, and potentially on other finding aids with series-level restrictions.

**Comment by phoebeno** [comment]
Also, after RH removes all the child accessrestrict components that are the same as their parent, this could become more urgent, as the note inheritance should really be more active at that point.

**Comment by faithc** [comment]
Yes, we plan to tag this as "sudden priority" once Regine finishes up the data cleanup since many notes will be incorrect, which will significantly impact users and public svs staff.

**Comment by phoebeno** [comment]
Now that RH has completed the cleanup for University Archives, here is a series that inherits from grandaddy rather than parent: https://findingaids.princeton.edu/catalog/AC129_c03472
This component has the parent Series 10, whose note reads "Series 10 is open for research use."

**Comment by phoebeno** [comment]
Here is another example of this too-grandfathered inheritance giving users problems (this box is up for a duplicative restriction review; the review status was clear in old PULFA): 
https://pulfa.princeton.edu/collections/MC001.04/c12726
https://findingaids.princeton.edu/catalog/MC001-04_c12726

**Comment by phoebeno** [comment]
@regineheberlein, just want to check whether fixing this bug, as a priority, would interfere with any of your restriction-related work on the mss repository. my gut feeling is no? 
@tpendragon may we prioritize this during the maintenance cycle?

**Comment by regineheberlein** [comment]
No concerns on my end, thanks for checking!

**Comment by tpendragon** [comment]
Confirmed to be fixed by #963, reindexing in prod is kicked off now.
