### ISSUE TITLE
Resources updated in Pulfalight should update their metadata in Figgy automatically

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#926]
Proxy for https://github.com/pulibrary/figgy/issues/4774

It's fine for this to be a nightly update.

See figgy issue for api specification.

AspaceIndexJob takes a flag for whether to tell figgy. When the aspaceindexjob is done, it sends the component id to the figgy endpoints. The full reindex routines set the flag to false.

**Comment by faithc** [comment]
Related, one should be able to sync metadata from an unpublished FA. In most cases, staff will want to associate digital content before publishing everything.

**Comment by ccleeton** [comment]
Anytime things are updated in Aspace we want figgy to sync to update automatically.
