### ISSUE TITLE
Location info not routing to Aeon/call slips

### ISSUE THREAD

**Issue by faithc** [pulibrary/pulfalight#931]
Top container profiles don't appear if multiple folders from a box are requested so staff won't know where the item is located. Not sure if this is a result of a character limit? In the example, "elephant size box" is missing. 
[containerprofilemissing.docx](https://github.com/pulibrary/pulfalight/files/7565610/containerprofilemissing.docx)
[containerprofilemissing2.docx](https://github.com/pulibrary/pulfalight/files/7565611/containerprofilemissing2.docx)

## Sudden Priority Justification

> This issue will result in items being very difficult to locate in the stacks.

Without this designation staff are forced to randomly browse stacks on the off chance material is there.

**Comment by tpendragon** [comment]
@faithc This is marked sudden priority - for the sake of documentation can you put on this ticket why that's the case? Presumably it's impossible to find these materials when this happens?

**Comment by faithc** [comment]
This issue will result in items being very difficult to locate.

**Comment by ccleeton** [comment]
To add a follow up to Faith's comment, items are shelved in size categories at both SC locations. This could result in having to search multiple vaults and or floors to find where a single box is physically located.
