### ISSUE TITLE
Index fields acqinfo and processinfo under "Collection History"

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/pulfalight#935]
We would like to make these fields searchable. Not a high priority.

Any collection should have these fields, "Aquisitions" and "processing information", e.g. https://findingaids.princeton.edu/catalog/C0159#collection-history

**Comment by ccleeton** [comment]
They are displaying but they are not included in the searching

**Comment by tpendragon** [comment]
@ccleeton When you say "searchable", do you mean in the dropdowns? Because if I search for Hilde Craeger (which is in that processinfo) it returns: https://findingaids.princeton.edu/?utf8=%E2%9C%93&group=true&f%5Bcollection_sim%5D%5B%5D=14+Africans+vs.+One+American+by+Frederic+Fox%2C+1962&search_field=all_fields&q=Hilde+Creager

**Comment by ccleeton** [comment]
So this is another example of a search for something in the notes but, it is not highlighting or going to where it is found 
Example: Searching for the word "mold" - this is commonly added when physical mold has been found and treated in a collection.
[https://findingaids.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=mold](url)

The results are showing that somewhere in the collections have mold but its not going to the page where the word mold is found. Nor is it highlighted.

Not sure if @phoebeno or @faithc have other examples?

**Comment by faithc** [comment]
@tpendragon not in the dropdowns. The example you provided is correct. Staff will also frequently search for accession numbers, for example "AM 20449" that's noted in this collection.

**Comment by eliotjordan** [comment]
`acqinfo` is already searchable and appears in the highlighting.
Need to add:
- processinfo_processing_ssm
- processinfo_conservation_ssm

**Comment by eliotjordan** [comment]
Closing this ticket. If feedback warrants we can re-open.
