### ISSUE TITLE
[PULFALight/production] MultiXml::ParseError: 25:84: ERROR: Namespace prefix xlin for href on extref is not defined

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#938]
[PULFALight/production] MultiXml::ParseError: 25:84: ERROR: Namespace prefix xlin for href on extref is not defined

## Backtrace

    line 60 of [PROJECT_ROOT]/app/services/aspace/client.rb: get_resource_description_xml
    line 46 of [PROJECT_ROOT]/app/jobs/aspace_index_job.rb: perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/82704069)

## Sudden Priority Justification

Archivists need to be able to see their changes.

**Comment by tpendragon** [comment]
The record had a new note and there was a user typo - should have been `xlink` and instead it was `xlin`. Told them about it and fixed it.
