### ISSUE TITLE
Collection abstract fields don't convert extref to links

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#941]
## Sudden Priority Justification

PUDL is going down and the only way to link to the exhibits from the finding aids site is with a link in the abstract, which right now renders as unclickable.

**Comment by phoebeno** [comment]
Trey, can we add this in the scopenote as well? Need to cover some more angles to get people to find these DPUL sites. In AC111 a link in scope is not rendering: https://findingaids.princeton.edu/catalog/AC111#description
