### ISSUE TITLE
json for nonexistent record should not 500

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#944]
It returns json with a 404 status, but honeybadger still logs an error.

example url: https://findingaids-beta.princeton.edu/catalog/L99114260743506421.json 

## Backtrace

    line 19 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/70813262)

**Comment by tpendragon** [comment]
It's not doing it now.
