### ISSUE TITLE
Access Denied/broken links in Ask A Question 

### ISSUE THREAD

**Issue by ccleeton** [pulibrary/pulfalight#953]
When in a component there are the "Ask a Question" and "Suggest a Correction" options. 

If you click on any of the 3 links in the box they are showing as Access Denied
These went to a FAQ at one point. Seems like its a URL issue. Please make the following adjustments.

1. How can I access Special Collections? OLD URL: https://library.princeton.edu/special-collections/faqs/how-can-i-access-special-collections NEW URL [https://faq.library.princeton.edu/special-collections/faq/338780?m=p](url)
2. How can I purchase copies from Rare Books & Special Collections?
--This one the text needs to be changed to the following Q. [What digitization services do you offer for material in Special Collections?](https://faq.library.princeton.edu/special-collections/faq/64876?m=p)
4. - Do I need permission to quote or publish from Special Collections material? Corrected URL: [https://faq.library.princeton.edu/special-collections/faq/56766?m=p](url)

**Comment by hackartisan** [comment]
The forms still work and patrons can still communicate with staff. So I'm not sure I agree this is a sudden priority. But it's not a good look and it's also very easy to change these so I'm going to go ahead and make the fix.
