### ISSUE TITLE
Add text welcoming feedback on items to the home page of the site.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#962]
Library Communications wants to advertise the "Suggest a Correction" buttons in Pulfalight in their January newsletter.

Text recommended by @faithc:

> PUL welcomes your feedback on the description of its archival collections. Please use the Suggest a Correction button found on every page of this site to report errors or omissions as well as [harmful or offensive language](https://findingaids.princeton.edu/archival_language) that you encounter.

We'll need to figure out a nice way to display this text - maybe with a pointer towards the button we're talking about, somehow?

## Text of email for reference

> The Dean for Research publishes a quarterly newsletter where PUL features a brief headline and a link to a resource. For January, we plan to feature the new Finding Aids site and draw attention to the descriptive language feedback buttons. (Example newsletter: https://research.princeton.edu/sites/research/files/media/dfr_newsletter_-_april_2020.pdf)
> 
> Here is the language we plan to submit:
> 
> PUL’s Finding Aids website offers enhanced content access and features descriptive language feedback buttons
> 
> Would it be possible for you to add language on the landing page that refers to the descriptive language feedback buttons? Maybe something like: PUL welcomes your feedback on descriptive language found in the archives. A feedback button can be found on each item’s entry page. (Or something like that) If you are okay with adding something like, what do you think the timeframe would be?

**Comment by tpendragon** [comment]
This'll no longer be going in the January newsletter. Leaving ticket around for POs to handle.

**Comment by hackartisan** [comment]
We need to figure out where to put this.

**Comment by ccleeton** [comment]
If I am reading/remembering it needs to be on the main landing page? Not that I like this idea but maybe a smaller banner?

**Comment by hackartisan** [comment]
Maybe a 3rd column after hours and "request materials"? we could move the create account button below the text saying you'll need to create an account.

**Comment by ccleeton** [comment]
I don't hate that idea. :)
