### ISSUE TITLE
Users should be able to search for collections by call number

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#97]

**Comment by tampakis** [comment]
Example: https://pulfalight-staging.princeton.edu/?utf8=%E2%9C%93&search_field=all_fields&q=MC001.04_c01621

Should retrieve: https://pulfalight-staging.princeton.edu/catalog/MC001-04MC001-04_c01621

**Comment by faithc** [comment]
Just to clarify, this request is for users to be able to search call numbers/collection codes as keywords as they can on the current site; so, just "MC001.04" or "C0108", for example; not a component ID necessarily.

**Comment by jrgriffiniii** [comment]
This may be fully resolved by https://github.com/pulibrary/pul_solr/pull/210

**Comment by jrgriffiniii** [comment]
This should provide users with the ability to search collections or components by call number. No users really reference the components by this number.

**Comment by jrgriffiniii** [comment]
This is still not functioning as expected.

**Comment by eliotjordan** [comment]
Closed in favor of #407
