### ISSUE TITLE
Index shard size discrepancy

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#974]
The index is much bigger on lib-solr-prod4 than on 5 or 6.
```
130G    ./pulfalight-production_shard1_replica_n9  # prod4
25G	./pulfalight-production_shard1_replica_n1      # prod5
27G	./pulfalight-production_shard1_replica_n2      # prod6
```

We should figure out whether it needs to be much bigger.
* If yes, why? We should probably increase disk size on that machine.
* If no, bring the replicants into uniformity. 

We notice the tlog directory is very big on prod4

We expect we could reindex into a new core and it would fix the problem.

**Comment by tpendragon** [comment]
I'm putting this on deck so we can look at it during our next pulfalight cycle, if we don't get to it during a maintenance week. It will become a higher priority if disk space becomes a big issue on our solr box.

**Comment by hackartisan** [comment]
They're now all 11-12G. No one did anything as far as we know.
