### ISSUE TITLE
Results missing from search when limited by repository

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pulfalight#975]
Reported by April:

The materials on Evelyn College that appear in a search of this specific collection do not show up in a general search of the finding aids that is limited to University Archives as repository: https://findingaids.princeton.edu/?utf8=%E2%9C%93&group=true&f%5Bcollection_sim%5D%5B%5D=Historical+Subject+Files+Collection%2C+1746-2019&search_field=all_fields&q=evelyn

Here's the limit to repository search: https://findingaids.princeton.edu/?f%5Brepository_sim%5D%5B%5D=Princeton+University+Archives&group=true&q=Evelyn+College&search_field=all_fields

They do come up in a generic search of the finding aids, however. https://findingaids.princeton.edu/?utf8=%E2%9C%93&group=true&search_field=all_fields&q=Evelyn+College

Does this mean that AC109 somehow got hidden from University Archives as a repository?

These appear to be the same collections referenced in #968

## Sudden priority justification
Patrons may be unable to find materials

**Comment by phoebeno** [comment]
Search for [marching band](https://findingaids.princeton.edu/?f%5Brepository_sim%5D%5B%5D=Princeton+University+Archives&group=true&q=marching+band&search_field=all_fields). 17 total results, 8 of them are at PUA. But when you limit by repository, you only get 2 of these collections (NOT AC126, AC112, AC109. AC362, AC047, AC053).
