### ISSUE TITLE
Test ASpace EAD Plugin with ASpace 3.2

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#976]
Email from Lyrasis:

> Custom Plugins: 
 
> As always, BE SURE TO TEST your custom plugins, if you have any. 
 
> If you have supplied us with a custom plugin to install please do local testing ASAP to ensure that the plugin is compatible with the new version of ArchivesSpace. We will assume that any plugins provided to us remain compatible. If the plugin breaks your site, it is your responsibility to implement a patch and notify us when it is available. In extreme cases of instability caused by a custom plugin we may disable it in the hosted environment. 

## Success Criteria / Process

Spin up a local ArchivesSpace version 3.2 (Instructions: https://archivesspace.github.io/tech-docs/development/dev.html), install our plugin (plugin: https://github.com/pulibrary/princeton_ead_exporter, install like this: https://github.com/hudmol/extended_advanced_search#getting-started)

We should also add documentation on installing the plugin.

Import an EAD from our ASpace, then export that EAD and make sure a few things show up:

* Location code in `altrender` of `<container>`s
* Container notes in `note` of `<container>`s
* Right restriction code in `rights-restriction` of `<accessrestrict>`

Generally if the EAD parses when it comes out it's probably fine.

## Sudden Priority Justification

They're rolling the update out this month.

**Comment by regineheberlein** [comment]
Data import steps I've taken:
- create a repository
- edit the CVL for accessrestrictions (probably not necessary; I did it because I wasn't getting expected behaviour)
- import an EAD (that I previously exported from production ASpace)
- create location "mss" and container profile "NBox" and link them to a container
- add a note to a container

I nuked my database and started over; nevertheless, I'm getting the same results as described in my previous comment.

**Comment by tpendragon** [comment]
That data looks like the plugin's not working at all - as if maybe the methods to override have changed.

**Comment by regineheberlein** [comment]
The way I know the plugin is installed correctly and doing something is `<container altrender="NBox"' -- that's the plugin at work; except it shouldn't be `@altrender` but `encodinganalog`, so it's weird.

**Comment by tpendragon** [comment]
We overrode what goes in altrender - I think the default is that it was the container type.

**Comment by regineheberlein** [comment]
I tried a `plugin-init.rb` file following the NYU model, to no effect

**Comment by regineheberlein** [comment]
Aha! It seems one needs to enable the plugin in two places: 
`./config/config.rb` AND 
`./common/config/config-defaults.rb`

With that, I'm getting correct container output, though still no `accessrestrict/@rights-restriction`, so I'm still following up on that:
```
<container 
   altrender="mss" 
   encodinganalog="NBox"	
   id="aspace_4b258a3d8c9fa0c6d645d53efd72aaf3"
   label="mixed materials [32101037706916]" 
   note="D-Zone" 
   type="box">1</container>
```

**Comment by regineheberlein** [comment]
Confirming this also produces correct accessrestrict output:
<accessrestrict 
   id="aspace_89b0fda07485cf5d118590432a3c8750"
   rights-restriction="Restricted">
	<head>Conditions Governing Access</head>
	<p>This file is restricted</p>
</accessrestrict>
