### ISSUE TITLE
Indexing error when missing a parent id

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#978]
Problem is here: https://github.com/pulibrary/pulfalight/blob/e5f614f56c74376db6d0cde616c43f20afc1377b/lib/pulfalight/traject/ead2_component_config.rb#L500

Potential solution: Exit if parent_ids is nil or empty.

## Backtrace

    line 500 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_component_config.rb: block (2 levels) in load_config_file
    line 446 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_config.rb: block (3 levels) in load_config_file
    line 440 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_config.rb: block (2 levels) in load_config_file

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/83955967)

**Comment by tpendragon** [comment]
Maybe the EAD was fixed and staging needs a not-soft reindex?

**Comment by hackartisan** [comment]
It only failed once. Does this job not retry?

**Comment by tpendragon** [comment]
We think this is fixed.
