### ISSUE TITLE
Code to fetch parent repository fails when parent repository value is nil 

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulfalight#979]
[PULFALight/production] TypeError: no implicit conversion of nil into Array

https://github.com/pulibrary/pulfalight/blob/e5f614f56c74376db6d0cde616c43f20afc1377b/lib/pulfalight/traject/ead2_component_config.rb#L153

## Backtrace

    line 153 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_component_config.rb: concat
    line 153 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_component_config.rb: block (2 levels) in load_config_file
    line 446 of [PROJECT_ROOT]/lib/pulfalight/traject/ead2_config.rb: block (3 levels) in load_config_file

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/65922/faults/83946216)

## Sudden priority justification

This is marked as "Sudden Priority" because it is a bug introduced after resolving another sudden priority ticket https://github.com/pulibrary/pulfalight/issues/975. It is preventing indexing from completing.

**Comment by tpendragon** [comment]
Parent repository should never be nil, so we'll have to figure out why it is.

This resource is EA01: https://aspace.princeton.edu/staff/resources/1467#tree::resource_1467 (ea repository)

**Comment by hackartisan** [comment]
This record is from the `ea` / "East Asian Collection" repository. there's not an `Arclight::Repository` for this repository which I think is what's causing the error.
