### ISSUE TITLE
Evaluate and ensure that Aeon Activity support is integrated with request functionality

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pulfalight#98]
Currently Aeon supports the linking of requests with Activities (used for modeling classes or events) in which materials are used by patrons. Reports outlining usage of materials are generated from this information.

This is heavily Aeon-driven, so I am uncertain as to what is needed from the standpoint of UI development for this feature (set).

**Comment by sdellis** [comment]
@jrgriffiniii I think this is something we will have to test out with the External Requests approach we are currently taking and see if we might be able to map a value to [the "Request For" field](https://support.atlas-sys.com/hc/en-us/articles/360011819214-Submitting-Requests-for-Activities). Good news is that Aeon [plans on releasing enhancements for both the API and Requests from External Systems in Q3 of this year](https://support.atlas-sys.com/hc/en-us/articles/360011819214-Submitting-Requests-for-Activities).

**Comment by sdellis** [comment]
It looks like we can supply the `ForActivity` field when Requests are submitted. The Activity must already have been created in Aeon and we need to send the ActivityID. See the _Special Request Parameters_ section on the [External Requests Documentation Page](https://support.atlas-sys.com/hc/en-us/articles/360011820054-External-Request-Endpoint).

**Comment by tpendragon** [comment]
@ccleeton @faithc @sdellis This is marked as for MVP, but I don't see how to close this or work towards it even. Unless one of you have an idea of what this means for the user interface of Pulfalight, can we just close this?

**Comment by sdellis** [comment]
@tpendragon I agree. The use case is to request an item for a class or event, correct? The only way I could see this working is if we had a static list of known Activities that PULFALight could present to the user when they are ready to submit the request. 

Would a static list serve Public Services' needs? What will Public Services do with the Activity information when they get it? Perhaps we could list examples that would make the need more clear?

**Comment by ccleeton** [comment]
Activities in aeon are used for classes as they come up as well as exhibitions, tours etc. 
Example: An activity is created when we have a class visit, which can come up last minute or be planned far in advance, it all depends on the faculty member. So, we do not have a static list of these items, but we could create a single static activity in Aeon for testing. 

Overall a static list in an everyday workflow is not functional as the classes change all the time. 

How we use them: If we create an activity for a class, then all the class members and faculty can request items for that class. It can create a list of what we need to physically pull. Alternatively, staff will request materials for the activity and can batch process requests in aeon. 
The grouping of these transactions for an exhibit is also important for the movement of the items, basically a chain of evidence as it moves physically through processes and even across physical locations.

PS uses the data from this for statistical information, items circulated, number of attendees, overall number of classes in a given time period.

**Comment by tpendragon** [comment]
@ccleeton That sounds useful. `findingaids.princeton.edu` doesn't do anything with that right now, right? Assuming this is some sort of interface for creating codes or something that users can then request out of, can we push that to post-MVP? It seems like we'd have to do some research and use case gathering into the best implementation here.

**Comment by ccleeton** [comment]
Right now when users want to associate a request with an activity they have to select it in a drop down in the request form. As long as users can do that part similarly to now it can be post-MVP

**Comment by tpendragon** [comment]
@ccleeton Oh, this is supported now? Should I be seeing something here?

![Screen Shot 2020-11-20 at 11 18 26 AM](https://user-images.githubusercontent.com/2806645/99840868-2be14c80-2b22-11eb-89c4-910705f6acbd.png)

**Comment by ccleeton** [comment]
@tpendragon after you hit submit request it goes to the aeon request and it lives there.

**Comment by tpendragon** [comment]
@ccleeton Oh! Excellent. If that's the case can I close this issue?
