### ISSUE TITLE
publish URIs on component page

### ISSUE THREAD

**Issue by phoebeno** [pulibrary/pulfalight#984]
From @regineheberlein and Will Clements. Need to display object uri to staff on PULFA, so that they can input the uri at the point of doing restriction review (or any other bulk legacy cleanup project). Component id has not turned out to be sufficient for RH to run these bulk updates. Public services staff needs to review folders, and be able to enter the uris at this point into a spreadsheet, without the additional step of consulting ASpace. Our current large restriction review project, and restriction review processes going forward, depends on this.

**Comment by tpendragon** [comment]
@regineheberlein We have some concern about having a link to an interface in the UI that patrons won't ever be able to access. Can you describe the workflow you're trying to enable here? Maybe we can do something else to support it?

**Comment by regineheberlein** [comment]
We basically need to treat the uri as our main identifier for archival entities coming out of ASpace. This shouldn't be a link though, just the id from the ['uri'] field, e.g. `repositories/3/resources/1596`.

Archivists use pulfalight to do data analysis, and compile data that needs to be updated from there into spreadsheets. These spreadsheets are handed to us and become the input files for updates run in ArchivesSpace. However, they don't have uri's, so aren't immediately actionable. Having to query for the uri's first takes so long it's not practical.

FYI Will is working with Hudson Molonglo on a plugin that will put the uri's in the EAD export (to be added to ASpace core code later on), so this ticket can wait until that's in place and then just focus on displaying them.
