### ISSUE TITLE
enable OARSC functionality for zip downloads

### ISSUE THREAD

**Issue by kellybolding** [pulibrary/pulfalight#985]
Adding this ticket for prioritization following a discussion at the virtual reading room WG meeting and follow-up conversation with Faith.

Zip downloads mediated by the OARSC is the primary born-digital access use case for Firestone archival collections. Collections with this access level will be inaccessible until functionality is implemented.  

## Success Criteria

When viewing a page with reading room zip content (OARSC) (https://findingaids.princeton.edu/catalog/C1436_c547) it should display the same yellow banner you get for viewer OARSC content asking you to sign in. An example of the view you get for logging in can see in incognito here: https://findingaids.princeton.edu/catalog/C1491_c1886

**Comment by ccleeton** [comment]
Looking for this for zip downloads only

**Comment by tpendragon** [comment]
https://findingaids.princeton.edu/catalog/C1436_c547

**Comment by faithc** [comment]
https://findingaids.princeton.edu/catalog/C1520_c35174-39458

**Comment by faithc** [comment]
https://findingaids.princeton.edu/catalog/C1436_c551

**Comment by hackartisan** [comment]
Plan:

Move from polling the manifest for authorization to getting all the info we need from the graphql endpoint
Update the getResourcesByOrangelightIds query to return an object like

```
{ ...
  embed: {
    html: 
    status:
  }
}
```

Where html is either an iframe or a link and status could be "unauthenticated", "unauthorized", or "authorized".

If unauthenticated or unauthorized then html is nil unless the resource is public.

**Comment by hackartisan** [comment]
More Plan.

- If it's a DAO that's not a figgy link, render it as a button on the page.
- If it's a DAO that is a figgy link, stash the url and label on the page
- query graphql to get the embed info
- if we stashed a label, replace the text of the link we got back with the label we stashed on the page
- render what we got back from figgy, modified or not

- If there's no DAO
- query graphql and get a link (it's a private resource, I'm logged in)
- Insert the link
