### ISSUE TITLE
Add and provision three new frontend boxes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pulfalight#997]
We're publishing some content on April 4th that may get a lot of traffic. We should be prepared in case we do - if it turns out it's fine we can decommission these after.

## Sudden Priority Justification

We need capacity ready by April 4th. We can do this next maintenance cycle.

**Comment by acozine** [comment]
Current pulfalight prod boxes have 2 CPUs, 16 GB of memory, and a 40 GB hard drive each. Both are on hosts in `b` datacenter, so new VMs should go on hosts in `a` datacenter.

**Comment by tpendragon** [comment]
There's a good chance that CPU caps out well before RAM and we can lower the RAM there. Let me slam the servers real quick and see.

**Comment by tpendragon** [comment]
Sieging it as hard as I could I couldn't get memory to rise above like 6GB:

![Screen Shot 2022-03-09 at 1 19 51 PM](https://user-images.githubusercontent.com/2806645/157537966-8ed4fa8e-3ee0-4654-a430-fbf935acd020.png)

**Comment by tpendragon** [comment]
Unable to SSH to pulfalight-prod3/4/5 right now to provision them.
